/-
Copyright (c) 2026 Tilemachos Vassias. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tilemachos Vassias (formalization assisted by Claude)
-/
import LeanDring.Theory.DRing.Induced
import LeanDring.P4.ModelPow

/-!
# The A-block of the species table for the (xii)/(xiii) model

The Gauss-sum layer lives on the **unique abelian
maximal subgroup** `A ≅ C_{p²} × C_p`. In the model's normal-form
coordinates `a^α s^u b^v`, that subgroup is **not** `⟨a, b⟩` (which is
nonabelian here: `b a b⁻¹ = a^{1+p}`) but the kernel of the residue map

  `toQuot : Model p d →* Multiplicative (ZMod p)`, `x ↦ redp α`,

i.e. `A = ⟨aᵖ, s, b⟩ = {x : redp x.α = 0}`, with `G/A ≅ C_p` generated by
the image of `a`.

Main results (sorry-free):

* `DRing.species_basisElt_of_normal` — for `K ⊴ G` and `h ∈ K`, Müller's
  species formula collapses to a **full coset sum with arbitrary
  representatives**: `φ_{K,h}[K,χ] = ∑_{q ∈ G/K} χ(r(q)⁻¹ h r(q))`
  (all cosets are `K`-fixed, and characters are invariant under inner
  conjugation by `K` because `ℂˣ` is commutative).
* `P4.Model.toQuot`, `P4.Model.subA` — the residue hom and `A := ker`,
  with `card_subA : |A| = p³` and `A ⊴ G` for free.
* `P4.Model.species_A_block` — **the A-block entries are τ-orbit
  character sums**: for every character `χ` of `A` and every `h ∈ A`,
  `φ_{A,h}[A,χ] = ∑_{t : ZMod p} χ(a^{-t} h a^{t})` — the raw form of
  the `G₁`/`G₂` Gauss-sum expressions.
-/

namespace LeanDring

open MulAction

universe u

namespace DRing

variable {G : Type u} [Group G] [Fintype G]

omit [Fintype G] in
/-- Conjugation by `g⁻¹ · g` stays in a normal subgroup. -/
theorem conj_mem_of_normal {K : Subgroup G} [hN : K.Normal] {x : G}
    (hx : x ∈ K) (g : G) : g⁻¹ * x * g ∈ K := by
  have := hN.conj_mem x hx g⁻¹
  rwa [inv_inv] at this

omit [Fintype G] in
/-- Characters are invariant under conjugation by elements of the
subgroup itself (the target `ℂˣ` is commutative). -/
theorem char_conj_eq (K : Subgroup G) (l : K →* ℂˣ) {x k : G}
    (hx : x ∈ K) (hk : k ∈ K) (hconj : k⁻¹ * x * k ∈ K) :
    l ⟨k⁻¹ * x * k, hconj⟩ = l ⟨x, hx⟩ := by
  have hsplit : (⟨k⁻¹ * x * k, hconj⟩ : K) =
      (⟨k, hk⟩ : K)⁻¹ * ⟨x, hx⟩ * ⟨k, hk⟩ := rfl
  rw [hsplit, map_mul, map_mul, map_inv]
  calc (l ⟨k, hk⟩)⁻¹ * l ⟨x, hx⟩ * l ⟨k, hk⟩
      = l ⟨x, hx⟩ * ((l ⟨k, hk⟩)⁻¹ * l ⟨k, hk⟩) := by
        rw [mul_comm (l ⟨k, hk⟩)⁻¹ (l ⟨x, hx⟩), mul_assoc]
    _ = l ⟨x, hx⟩ := by rw [inv_mul_cancel, mul_one]

omit [Fintype G] in
/-- For normal `K`, every coset is `K`-fixed. -/
theorem coset_mem_fixedPoints (K : Subgroup G) [K.Normal] (q : G ⧸ K) :
    q ∈ fixedPoints K (G ⧸ K) := by
  intro k
  obtain ⟨g⟩ := q
  change ((k : G) * g : G) = (g : G ⧸ K)
  refine (QuotientGroup.eq).mpr ?_
  have h1 : ((k : G) * g)⁻¹ * g = g⁻¹ * (k : G)⁻¹ * g := by group
  rw [h1]
  exact conj_mem_of_normal (K.inv_mem k.2) g

/-- **The species formula on a normal subgroup, with free choice of coset
representatives**: for `K ⊴ G`, `h ∈ K`, a character `χ : K →* ℂˣ`, and any
system of representatives `r : G/K → G`,
`φ_{K,h}[K,χ] = ∑_{q ∈ G/K} χ(r(q)⁻¹ h r(q))`. -/
theorem species_basisElt_of_normal (K : Subgroup G) [K.Normal]
    [Fintype (G ⧸ K)] (l : K →* ℂˣ) (h : K) (r : G ⧸ K → G)
    (hr : ∀ q : G ⧸ K, ((r q : G) : G ⧸ K) = q)
    (hmem : ∀ q : G ⧸ K, (r q)⁻¹ * (h : G) * r q ∈ K) :
    species K h (basisElt K l) =
      ∑ q : G ⧸ K, ((l ⟨(r q)⁻¹ * (h : G) * r q, hmem q⟩ : ℂˣ) : ℂ) := by
  classical
  rw [species_basisElt]
  refine Finset.sum_bij (fun q _ => (q.1 : G ⧸ K)) (fun q _ => Finset.mem_univ _)
    (fun q₁ _ q₂ _ hq => Subtype.ext hq)
    (fun q _ => ⟨⟨q, coset_mem_fixedPoints K q⟩, Finset.mem_univ _, rfl⟩)
    (fun q _ => ?_)
  -- both sides evaluate `l` at conjugates of `h` by representatives of the
  -- same coset `q.1`; they differ by an inner conjugation from `K`
  refine congrArg (Units.coeHom ℂ) ?_
  have hq : ((r q.1 : G) : G ⧸ K) = ((q.1.out : G) : G ⧸ K) := by
    rw [hr q.1, QuotientGroup.out_eq']
  have hκ : q.1.out⁻¹ * r q.1 ∈ K := QuotientGroup.eq.mp hq.symm
  have hrq : r q.1 = q.1.out * (q.1.out⁻¹ * r q.1) := by group
  have hconj : (r q.1)⁻¹ * (h : G) * r q.1 =
      (q.1.out⁻¹ * r q.1)⁻¹ * (q.1.out⁻¹ * (h : G) * q.1.out) *
        (q.1.out⁻¹ * r q.1) := by group
  have hmid : q.1.out⁻¹ * (h : G) * q.1.out ∈ K :=
    MonGSet.sectionConj_mem K K h q.1 (q.2 h)
  calc l ⟨q.1.out⁻¹ * (h : G) * q.1.out, _⟩
      = l ⟨(q.1.out⁻¹ * r q.1)⁻¹ * (q.1.out⁻¹ * (h : G) * q.1.out) *
          (q.1.out⁻¹ * r q.1),
          hconj ▸ hmem q.1⟩ :=
        (char_conj_eq K l hmid hκ _).symm
    _ = l ⟨(r q.1)⁻¹ * (h : G) * r q.1, hmem q.1⟩ := by
        refine congrArg l (Subtype.ext ?_)
        exact hconj.symm

end DRing

namespace P4

namespace Model

open DRing

variable {p : ℕ} [Fact p.Prime] [Fact (Odd p)] {d : ZMod p}

instance : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩

instance : Fintype (Model p d) :=
  Fintype.ofEquiv _ (toProd (p := p) (d := d)).symm

omit [Fact (Odd p)] in
/-- `(t.val : ZMod p) = t`. -/
theorem val_cast_id (t : ZMod p) : ((t.val : ℕ) : ZMod p) = t := by
  rw [ZMod.natCast_val, ZMod.cast_id]

variable (p d) in
/-- The residue map `a^α s^u b^v ↦ α mod p`: a surjective homomorphism onto
`C_p` whose kernel is the abelian maximal subgroup `A = ⟨aᵖ, s, b⟩`. -/
def toQuot : Model p d →* Multiplicative (ZMod p) where
  toFun x := Multiplicative.ofAdd (redp p x.α)
  map_one' := by
    change Multiplicative.ofAdd (redp p (0 : ZMod (p ^ 2))) = 1
    rw [map_zero]
    rfl
  map_mul' x y := by
    have hα : (x * y).α = x.α + y.α +
        liftp p (tauP p d (redp p y.α) x.u x.v) +
        dc d * carryF p x.u y.u := congrArg Model.α (mul_def x y)
    have hred : redp p (x * y).α = redp p x.α + redp p y.α := by
      rw [hα, map_add, map_add, map_add, redp_liftp, map_mul, redp_carryF,
        mul_zero, add_zero, add_zero]
    change Multiplicative.ofAdd (redp p (x * y).α) = _
    rw [hred]
    rfl

variable (p d) in
theorem toQuot_surjective : Function.Surjective (toQuot p d) := by
  intro m
  refine ⟨⟨dc (m.toAdd), 0, 0⟩, ?_⟩
  change Multiplicative.ofAdd (redp p (dc (m.toAdd))) = m
  rw [redp_dc]
  rfl

variable (p d) in
/-- **The abelian maximal subgroup** `A = ker(toQuot) = ⟨aᵖ, s, b⟩`. -/
noncomputable def subA : Subgroup (Model p d) := (toQuot p d).ker

instance : (subA p d).Normal := MonoidHom.normal_ker _

theorem mem_subA_iff {x : Model p d} : x ∈ subA p d ↔ redp p x.α = 0 := by
  change x ∈ (toQuot p d).ker ↔ _
  rw [MonoidHom.mem_ker]
  constructor
  · intro h
    have := congrArg Multiplicative.toAdd h
    exact this
  · intro h
    change Multiplicative.ofAdd (redp p x.α) = 1
    rw [h]
    rfl

variable (p d) in
/-- `|A| = p³`. -/
theorem card_subA : Nat.card (subA p d) = p ^ 3 := by
  have hp : p.Prime := Fact.out
  have hcard : Nat.card (Model p d) = p ^ 4 := card_model (p := p) (d := d)
  have hquot : Nat.card (Model p d ⧸ subA p d) = p := by
    change Nat.card (Model p d ⧸ (toQuot p d).ker) = p
    rw [Nat.card_congr (QuotientGroup.quotientKerEquivOfSurjective
      (toQuot p d) (toQuot_surjective p d)).toEquiv]
    rw [Nat.card_eq_fintype_card, Fintype.card_multiplicative, ZMod.card]
  have hmul := Subgroup.card_eq_card_quotient_mul_card_subgroup (subA p d)
  rw [hcard, hquot] at hmul
  have hp4 : p ^ 4 = p * p ^ 3 := by ring
  rw [hp4] at hmul
  exact (Nat.eq_of_mul_eq_mul_left (Nat.pos_of_ne_zero hp.ne_zero)
    hmul.symm)

omit [Fact (Nat.Prime p)] [Fact (Odd p)] in
/-- **`A` is abelian**: on `A = {redp α = 0}`
the `τ`-cocycle and the `redp·u` twist both vanish, leaving only the
symmetric `carryF` — so any two elements of `A` commute. -/
theorem model_mul_comm_of_mem_subA {x y : Model p d}
    (hx : redp p x.α = 0) (hy : redp p y.α = 0) : x * y = y * x := by
  rw [mul_def, mul_def, hx, hy]
  refine Model.ext ?_ ?_ ?_
  · change x.α + y.α + liftp p (tauP p d 0 x.u x.v) + dc d * carryF p x.u y.u =
        y.α + x.α + liftp p (tauP p d 0 y.u y.v) + dc d * carryF p y.u x.u
    rw [tauP_zero_left, tauP_zero_left, liftp_zero, carryF_comm y.u x.u]
    ring
  · change x.u + y.u = y.u + x.u
    ring
  · change x.v + y.v + 0 * x.u = y.v + x.v + 0 * y.u
    ring

theorem subA_mul_comm (x y : subA p d) : x * y = y * x :=
  Subtype.ext (model_mul_comm_of_mem_subA (mem_subA_iff.mp x.2)
    (mem_subA_iff.mp y.2))

/-- The abelian maximal subgroup `A` as a commutative group. -/
noncomputable instance : CommGroup (subA p d) :=
  { (inferInstance : Group (subA p d)) with mul_comm := subA_mul_comm }

/-- **The center of the model**: `Z(G) = ⟨aᵖ⟩ ≅ C_p`.
An element is central iff its `s`- and `b`-exponents vanish and its
`a`-exponent is a multiple of `p` — i.e. it lies in `⟨aᵖ⟩`. -/
theorem mem_center_iff_model {x : Model p d} :
    x ∈ Subgroup.center (Model p d) ↔
      x.u = 0 ∧ x.v = 0 ∧ redp p x.α = 0 := by
  rw [Subgroup.mem_center_iff]
  constructor
  · intro h
    -- from `y = ⟨0,1,0⟩` (`s`): the `b`-component forces `redp α = 0`
    have hα : redp p x.α = 0 := by
      have key := congrArg Model.v (h ⟨0, 1, 0⟩)
      rw [congrArg Model.v (mul_def ⟨0, 1, 0⟩ x),
        congrArg Model.v (mul_def x ⟨0, 1, 0⟩)] at key
      change (0 : ZMod p) + x.v + redp p x.α * 1 =
        x.v + 0 + redp p (0 : ZMod (p ^ 2)) * x.u at key
      rw [map_zero] at key
      linear_combination key
    -- from `y = ⟨1,0,0⟩` (`a`): the `b`-component forces `u = 0`
    have hu : x.u = 0 := by
      have key := congrArg Model.v (h ⟨1, 0, 0⟩)
      rw [congrArg Model.v (mul_def ⟨1, 0, 0⟩ x),
        congrArg Model.v (mul_def x ⟨1, 0, 0⟩)] at key
      change (0 : ZMod p) + x.v + redp p x.α * 0 =
        x.v + 0 + redp p (1 : ZMod (p ^ 2)) * x.u at key
      rw [map_one] at key
      linear_combination -key
    -- then the `a`-component forces `v = 0`
    have hv : x.v = 0 := by
      have key := congrArg Model.α (h ⟨1, 0, 0⟩)
      rw [congrArg Model.α (mul_def ⟨1, 0, 0⟩ x),
        congrArg Model.α (mul_def x ⟨1, 0, 0⟩)] at key
      change (1 : ZMod (p ^ 2)) + x.α +
          liftp p (tauP p d (redp p x.α) 0 0) + dc d * carryF p 0 x.u =
        x.α + 1 + liftp p (tauP p d (redp p (1 : ZMod (p ^ 2))) x.u x.v) +
          dc d * carryF p x.u 0 at key
      simp only [hu, map_one, tauP_zero_right, liftp_zero, carryF_zero,
        mul_zero, add_zero] at key
      -- key : 1 + x.α = x.α + 1 + liftp (tauP d 1 0 x.v)
      have htau : tauP p d 1 0 x.v = x.v := by unfold tauP tri; ring
      rw [htau] at key
      refine liftp_eq_zero_iff.mp ?_
      linear_combination -key
    exact ⟨hu, hv, hα⟩
  · rintro ⟨hu, hv, hα⟩ y
    rw [mul_def, mul_def, hu, hv, hα]
    refine Model.ext ?_ ?_ ?_
    · change y.α + x.α + liftp p (tauP p d 0 y.u y.v) + dc d * carryF p y.u 0 =
        x.α + y.α + liftp p (tauP p d (redp p y.α) 0 0) + dc d * carryF p 0 y.u
      rw [tauP_zero_left, tauP_zero_right, liftp_zero, carryF_zero,
        carryF_zero']
      ring
    · change y.u + 0 = 0 + y.u
      ring
    · change y.v + 0 + 0 * y.u = 0 + y.v + redp p y.α * 0
      ring

omit [Fact (Odd p)] in
theorem liftp_injective : Function.Injective (liftp p) := by
  haveI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  intro k₁ k₂ h
  have h2 : k₁.val = k₂.val :=
    Nat.eq_of_mul_eq_mul_left (Fact.out : p.Prime).pos
      (by rw [← liftp_val, ← liftp_val, h])
  rw [← val_cast_id k₁, ← val_cast_id k₂, h2]

/-- **`|Z(G)| = p`**: the center
`⟨aᵖ⟩` has exactly `p` elements, parametrized by `k ↦ aᵖᵏ = ⟨liftp k, 0, 0⟩`. -/
theorem card_center : Nat.card (Subgroup.center (Model p d)) = p := by
  haveI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  have hf : Function.Bijective (fun k : ZMod p =>
      (⟨⟨liftp p k, 0, 0⟩,
          mem_center_iff_model.mpr ⟨rfl, rfl, redp_liftp k⟩⟩ :
        Subgroup.center (Model p d))) := by
    constructor
    · intro k₁ k₂ hk
      exact liftp_injective
        (congrArg (fun z : Subgroup.center (Model p d) => (z.1).α) hk)
    · rintro ⟨⟨α, u, v⟩, hx⟩
      obtain ⟨hu, hv, hα⟩ := mem_center_iff_model.mp hx
      exact ⟨(α.val / p : ℕ),
        Subtype.ext (Model.ext (liftp_of_redp_zero hα) hu.symm hv.symm)⟩
  rw [← Nat.card_eq_of_bijective _ hf, Nat.card_eq_fintype_card, ZMod.card]

/-- **`A` is the unique abelian maximal subgroup**: any
abelian subgroup of order `p³` equals `A`. If `M ≠ A` were another, then
`A ⊓ M` (order `≥ p²`) would lie in the center (since `G = A·M` with both
factors abelian), contradicting `|Z(G)| = p`. -/
theorem eq_subA_of_abelian_maximal (M : Subgroup (Model p d))
    (hMcard : Nat.card M = p ^ 3)
    (hab : ∀ x ∈ M, ∀ y ∈ M, x * y = y * x) : M = subA p d := by
  haveI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  have hp : p.Prime := Fact.out
  have hG : Nat.card (Model p d) = p ^ 4 := card_model (p := p) (d := d)
  by_contra hne
  -- both have index `p`
  have hMidx : M.index = p := by
    have h := M.card_mul_index; rw [hMcard, hG] at h
    exact Nat.eq_of_mul_eq_mul_left (pow_pos hp.pos 3) (by rw [h]; ring)
  have hAidx : (subA p d).index = p := by
    have h := (subA p d).card_mul_index; rw [card_subA p d, hG] at h
    exact Nat.eq_of_mul_eq_mul_left (pow_pos hp.pos 3) (by rw [h]; ring)
  -- `A ⊔ M = ⊤` (distinct index-`p` subgroups join to the top)
  have hsup : subA p d ⊔ M = ⊤ := by
    have hdvd : (subA p d ⊔ M).index ∣ p := by
      have h := Subgroup.index_dvd_of_le (le_sup_right : M ≤ subA p d ⊔ M)
      rwa [hMidx] at h
    rcases hp.eq_one_or_self_of_dvd _ hdvd with h1 | hpp
    · exact Subgroup.index_eq_one.mp h1
    · exfalso
      have hcardSup : Nat.card (subA p d ⊔ M : Subgroup (Model p d)) = p ^ 3 := by
        have h := (subA p d ⊔ M).card_mul_index; rw [hpp, hG] at h
        exact Nat.eq_of_mul_eq_mul_right hp.pos (by rw [h]; ring)
      have hMeq : M = subA p d ⊔ M :=
        Subgroup.eq_of_le_of_card_ge le_sup_right
          (le_of_eq (by rw [hcardSup, hMcard]))
      have hAle : subA p d ≤ M :=
        le_trans le_sup_left (le_of_eq hMeq.symm)
      exact hne (Subgroup.eq_of_le_of_card_ge hAle
        (le_of_eq (by rw [hMcard, card_subA p d]))).symm
  -- `A ⊓ M ⊆ Z(G)`: it commutes with both abelian factors, and `G = A·M`
  have hcentral : subA p d ⊓ M ≤ Subgroup.center (Model p d) := by
    intro x hx
    obtain ⟨hxA, hxM⟩ := Subgroup.mem_inf.mp hx
    rw [Subgroup.mem_center_iff]
    intro g
    have hgtop : M ⊔ subA p d = ⊤ := by rw [sup_comm]; exact hsup
    have hg : g ∈ (↑(M ⊔ subA p d) : Set (Model p d)) := by
      rw [hgtop]; trivial
    rw [Subgroup.mul_normal M (subA p d)] at hg
    obtain ⟨m, hm, s, hs, rfl⟩ := Set.mem_mul.mp hg
    have h1 : x * m = m * x := hab x hxM m hm
    have h2 : x * s = s * x :=
      model_mul_comm_of_mem_subA (mem_subA_iff.mp hxA) (mem_subA_iff.mp hs)
    calc m * s * x = m * (s * x) := by rw [mul_assoc]
      _ = m * (x * s) := by rw [h2]
      _ = (m * x) * s := by rw [mul_assoc]
      _ = (x * m) * s := by rw [h1]
      _ = x * (m * s) := by rw [mul_assoc]
  -- `|A ⊓ M| ≤ |Z| = p` but `|A ⊓ M| ≥ p²`
  have hle : Nat.card (subA p d ⊓ M : Subgroup (Model p d)) ≤ p := by
    have h := Subgroup.card_le_of_le hcentral
    rwa [card_center (p := p) (d := d)] at h
  have hge : p ^ 2 ≤ Nat.card (subA p d ⊓ M : Subgroup (Model p d)) := by
    have hidx : (subA p d ⊓ M).index ≤ p ^ 2 := by
      calc (subA p d ⊓ M).index ≤ (subA p d).index * M.index :=
            Subgroup.index_inf_le
        _ = p ^ 2 := by rw [hAidx, hMidx]; ring
    have hcard := (subA p d ⊓ M).card_mul_index
    rw [hG] at hcard
    have hstep : p ^ 2 * p ^ 2 ≤ Nat.card (subA p d ⊓ M : Subgroup (Model p d)) * p ^ 2 :=
      calc p ^ 2 * p ^ 2 = p ^ 4 := by ring
        _ = Nat.card (subA p d ⊓ M : Subgroup (Model p d)) * (subA p d ⊓ M).index := hcard.symm
        _ ≤ Nat.card (subA p d ⊓ M : Subgroup (Model p d)) * p ^ 2 := by
            gcongr
    exact Nat.le_of_mul_le_mul_right hstep (pow_pos hp.pos 2)
  have hcontra : p ^ 2 ≤ p := le_trans hge hle
  nlinarith [hp.two_le]

variable (p d) in
/-- The generator `a` of `G/A`. -/
def aGen : Model p d := ⟨1, 0, 0⟩

theorem toQuot_aGen_pow (n : ℕ) :
    toQuot p d (aGen p d ^ n) = Multiplicative.ofAdd ((n : ZMod p)) := by
  have h1 : toQuot p d (aGen p d) = Multiplicative.ofAdd (1 : ZMod p) := by
    change Multiplicative.ofAdd (redp p (1 : ZMod (p ^ 2))) = _
    rw [map_one]
  rw [map_pow, h1, ← ofAdd_nsmul]
  congr 1
  rw [nsmul_eq_mul, mul_one]

theorem mk_eq_mk_iff_toQuot {x y : Model p d} :
    ((x : Model p d ⧸ subA p d) = (y : Model p d ⧸ subA p d)) ↔
      toQuot p d x = toQuot p d y := by
  rw [QuotientGroup.eq]
  change x⁻¹ * y ∈ (toQuot p d).ker ↔ _
  rw [MonoidHom.mem_ker, map_mul, map_inv]
  constructor
  · intro h
    have := congrArg (fun z => toQuot p d x * z) h
    simpa [mul_inv_cancel_left] using this.symm
  · intro h
    rw [h, inv_mul_cancel]

variable (p d) in
/-- The conjugation map `τ_g : A → A`, `x ↦ g⁻¹ x g` (`A` is normal). -/
noncomputable def conjA (g : Model p d) (x : subA p d) : subA p d :=
  ⟨g⁻¹ * (x : Model p d) * g, conj_mem_of_normal x.2 g⟩

noncomputable instance : Fintype (Model p d ⧸ subA p d) :=
  Fintype.ofFinite _

/-- **The A-block species entries are τ-orbit character sums**: for every
character `χ` of `A` and every `h ∈ A`,
`φ_{A,h}[A,χ] = ∑_{t<p} χ(a^{-t} h a^{t})`. This is the raw form of the
Gauss-sum expressions of the `G₁`/`G₂` entries. -/
theorem species_A_block (χ : subA p d →* ℂˣ) (h : subA p d) :
    species (subA p d) h (basisElt (subA p d) χ) =
      ∑ t : ZMod p, ((χ (conjA p d (aGen p d ^ t.val) h) : ℂˣ) : ℂ) := by
  -- representatives: `r q := a^{t(q)}` where `t(q)` is the residue of `q.out`
  set r : (Model p d ⧸ subA p d) → Model p d :=
    fun q => aGen p d ^ ((toQuot p d q.out).toAdd).val with hrdef
  have hr : ∀ q : Model p d ⧸ subA p d, ((r q : Model p d) : _ ⧸ subA p d) = q := by
    intro q
    rw [hrdef]
    have h1 : toQuot p d (aGen p d ^ ((toQuot p d q.out).toAdd).val) =
        toQuot p d q.out := by
      rw [toQuot_aGen_pow, val_cast_id]
      rfl
    calc ((aGen p d ^ ((toQuot p d q.out).toAdd).val : Model p d) :
          _ ⧸ subA p d)
        = ((q.out : Model p d) : _ ⧸ subA p d) :=
          mk_eq_mk_iff_toQuot.mpr h1
      _ = q := QuotientGroup.out_eq' q
  have hmem : ∀ q : Model p d ⧸ subA p d,
      (r q)⁻¹ * (h : Model p d) * r q ∈ subA p d :=
    fun q => conj_mem_of_normal h.2 (r q)
  rw [species_basisElt_of_normal (subA p d) χ h r hr hmem]
  -- reindex the coset sum by `t : ZMod p` via `t ↦ mk (a^t)`
  have hbij : Function.Bijective
      (fun t : ZMod p => ((aGen p d ^ t.val : Model p d) : _ ⧸ subA p d)) := by
    constructor
    · intro t s hts
      have h1 := mk_eq_mk_iff_toQuot.mp hts
      rw [toQuot_aGen_pow, toQuot_aGen_pow, val_cast_id, val_cast_id] at h1
      exact Multiplicative.ofAdd.injective h1
    · intro q
      refine ⟨(toQuot p d q.out).toAdd, ?_⟩
      exact hr q
  refine (Fintype.sum_bijective _ hbij _ _ fun t => ?_).symm
  -- at the coset `mk (a^t)`, the chosen representative is again `a^t`
  have hout : toQuot p d (((aGen p d ^ t.val : Model p d) :
      _ ⧸ subA p d)).out = Multiplicative.ofAdd t := by
    have h1 : ((((aGen p d ^ t.val : Model p d) : _ ⧸ subA p d)).out :
        _ ⧸ subA p d) = ((aGen p d ^ t.val : Model p d) : _ ⧸ subA p d) :=
      QuotientGroup.out_eq' _
    have h2 := mk_eq_mk_iff_toQuot.mp h1
    rw [h2, toQuot_aGen_pow, val_cast_id]
  have hrval : r (((aGen p d ^ t.val : Model p d) : _ ⧸ subA p d)) =
      aGen p d ^ t.val := by
    rw [hrdef]
    change aGen p d ^ ((toQuot p d _).toAdd).val = aGen p d ^ t.val
    rw [hout]
    rfl
  refine congrArg (Units.coeHom ℂ) (congrArg χ (Subtype.ext ?_))
  change (aGen p d ^ t.val)⁻¹ * (h : Model p d) * aGen p d ^ t.val =
    (r (((aGen p d ^ t.val : Model p d) : _ ⧸ subA p d)))⁻¹ * (h : Model p d) *
      r (((aGen p d ^ t.val : Model p d) : _ ⧸ subA p d))
  rw [hrval]

/-! ## The τ-action in coordinates: the exponential-sum form -/

theorem aGen_pow (n : ℕ) :
    aGen p d ^ n = (⟨(n : ZMod (p ^ 2)), 0, 0⟩ : Model p d) := by
  induction n with
  | zero =>
    change (1 : Model p d) = _
    rw [one_def]
    ext <;> simp
  | succ n ih =>
    rw [pow_succ, ih]
    change (⟨(n : ZMod (p ^ 2)), 0, 0⟩ : Model p d) * ⟨1, 0, 0⟩ = _
    rw [mul_def]
    ext
    · change (n : ZMod (p ^ 2)) + 1 + liftp p (tauP p d (redp p 1) 0 0) +
        dc d * carryF p 0 0 = ((n + 1 : ℕ) : ZMod (p ^ 2))
      rw [tauP_zero_right, liftp_zero, carryF_zero, mul_zero, add_zero,
        add_zero]
      push_cast
      ring
    · change (0 : ZMod p) + 0 = 0
      ring
    · change (0 : ZMod p) + 0 + redp p 1 * 0 = 0
      ring

/-- Conjugation by `aⁿ` on `A`, in coordinates: with `m = n mod p`,
`a^{-n} (a^α s^u b^v) a^{n} = a^{α + p·P(m;u,v)} s^u b^{v + mu}` where
`P(m; u, v) = dmu + mv + T(m)u` is the τ-cocycle polynomial. -/
theorem conjA_aGen_pow (n : ℕ) (x : subA p d) :
    ((conjA p d (aGen p d ^ n) x : subA p d) : Model p d) =
      ⟨(x : Model p d).α +
          liftp p (tauP p d ((n : ZMod p)) (x : Model p d).u (x : Model p d).v),
        (x : Model p d).u,
        (x : Model p d).v + ((n : ZMod p)) * (x : Model p d).u⟩ := by
  have hp : p.Prime := Fact.out
  set g : Model p d := aGen p d ^ n with hg
  set y : Model p d :=
    ⟨(x : Model p d).α +
        liftp p (tauP p d ((n : ZMod p)) (x : Model p d).u (x : Model p d).v),
      (x : Model p d).u,
      (x : Model p d).v + ((n : ZMod p)) * (x : Model p d).u⟩ with hy
  change g⁻¹ * (x : Model p d) * g = y
  rw [mul_assoc, inv_mul_eq_iff_eq_mul]
  -- both sides computed by `mul_def` with `g = ⟨n, 0, 0⟩`
  have hgc : g = (⟨(n : ZMod (p ^ 2)), 0, 0⟩ : Model p d) := by
    rw [hg, aGen_pow]
  have hredn : redp p ((n : ZMod (p ^ 2))) = (n : ZMod p) := map_natCast _ n
  rw [hgc, mul_def, mul_def]
  ext
  · change (x : Model p d).α + (n : ZMod (p ^ 2)) +
        liftp p (tauP p d (redp p ((n : ZMod (p ^ 2)))) (x : Model p d).u
          (x : Model p d).v) +
        dc d * carryF p (x : Model p d).u 0 =
      (n : ZMod (p ^ 2)) + y.α + liftp p (tauP p d (redp p y.α) 0 0) +
        dc d * carryF p 0 y.u
    rw [hredn, tauP_zero_right, liftp_zero, carryF_zero, carryF_zero', hy]
    ring
  · change (x : Model p d).u + 0 = 0 + y.u
    rw [hy]
    ring
  · change (x : Model p d).v + 0 + redp p ((n : ZMod (p ^ 2))) * (x : Model p d).u =
      0 + y.v + redp p y.α * 0
    rw [hredn, hy]
    ring

theorem shift_mem_subA (x : subA p d) (z : ZMod p) (u' v' : ZMod p) :
    (⟨(x : Model p d).α + liftp p z, u', v'⟩ : Model p d) ∈ subA p d := by
  rw [mem_subA_iff]
  change redp p ((x : Model p d).α + liftp p z) = 0
  rw [map_add, redp_liftp, add_zero]
  exact mem_subA_iff.mp x.2

/-- **The A-block entries as explicit exponential sums**: in coordinates,
`φ_{A,h}[A,χ] = ∑_{m<p} χ(a^{p·P(m;u,v)} · h-shifted)` with the τ-cocycle
polynomial `P(m; u, v) = dmu + mv + T(m)u` — the raw Gauss-sum form of the
`G₁`/`G₂` entry formulas. -/
theorem species_A_block_expsum (χ : subA p d →* ℂˣ) (h : subA p d) :
    species (subA p d) h (basisElt (subA p d) χ) =
      ∑ m : ZMod p,
        ((χ ⟨⟨(h : Model p d).α +
              liftp p (tauP p d m (h : Model p d).u (h : Model p d).v),
            (h : Model p d).u,
            (h : Model p d).v + m * (h : Model p d).u⟩,
          shift_mem_subA h _ _ _⟩ : ℂˣ) : ℂ) := by
  rw [species_A_block]
  refine Finset.sum_congr rfl fun m _ => ?_
  refine congrArg (Units.coeHom ℂ) (congrArg χ (Subtype.ext ?_))
  rw [conjA_aGen_pow m.val h]
  rw [val_cast_id]

/-! ## Splitting the orbit sum: one-parameter subgroups of `A`

The shifted element factors as `h · z(P(m)) · b(mu)` where
`z : ZMod p → A`, `z(t) = a^{pt}` (central) and `b : ZMod p → A`,
`b(w) = b^w`. Any character `χ` of `A` therefore splits the A-block entry
into `χ(h)` times a sum of **two additive characters of `ZMod p`**
evaluated on the quadratic polynomial `P(m; u, v) = dmu + mv + T(m)u`. -/

variable (p d) in
/-- The central one-parameter subgroup `t ↦ a^{pt}` of `A`. -/
noncomputable def zElt (z : ZMod p) : subA p d :=
  ⟨⟨liftp p z, 0, 0⟩, by
    rw [mem_subA_iff]
    change redp p (liftp p z) = 0
    exact redp_liftp z⟩

variable (p d) in
/-- The one-parameter subgroup `w ↦ b^w` of `A`. -/
noncomputable def bElt (w : ZMod p) : subA p d :=
  ⟨⟨0, 0, w⟩, by
    rw [mem_subA_iff]
    change redp p (0 : ZMod (p ^ 2)) = 0
    exact map_zero _⟩

theorem zElt_add (z z' : ZMod p) :
    zElt p d (z + z') = zElt p d z * zElt p d z' := by
  refine Subtype.ext ?_
  change (⟨liftp p (z + z'), 0, 0⟩ : Model p d) =
    (⟨liftp p z, 0, 0⟩ : Model p d) * ⟨liftp p z', 0, 0⟩
  rw [mul_def]
  ext
  · change liftp p (z + z') = liftp p z + liftp p z' +
        liftp p (tauP p d (redp p (liftp p z')) 0 0) +
        dc d * carryF p 0 0
    rw [redp_liftp, tauP_zero_right, liftp_zero, carryF_zero, liftp_add]
    ring
  · change (0 : ZMod p) = 0 + 0
    ring
  · change (0 : ZMod p) = 0 + 0 + redp p (liftp p z') * 0
    ring

theorem bElt_add (w w' : ZMod p) :
    bElt p d (w + w') = bElt p d w * bElt p d w' := by
  refine Subtype.ext ?_
  change (⟨0, 0, w + w'⟩ : Model p d) =
    (⟨0, 0, w⟩ : Model p d) * ⟨0, 0, w'⟩
  rw [mul_def]
  ext
  · change (0 : ZMod (p ^ 2)) = 0 + 0 +
        liftp p (tauP p d (redp p (0 : ZMod (p ^ 2))) 0 w) +
        dc d * carryF p 0 0
    rw [map_zero, tauP_zero_left, liftp_zero, carryF_zero]
    ring
  · change (0 : ZMod p) = 0 + 0
    ring
  · change (w + w' : ZMod p) = w + w' + redp p (0 : ZMod (p ^ 2)) * 0
    ring

/-- The τ-shift factors through the one-parameter subgroups:
`shifted(m) = h · z(P(m; u, v)) · b(mu)`. -/
theorem shifted_eq (h : subA p d) (m : ZMod p) :
    (⟨⟨(h : Model p d).α +
          liftp p (tauP p d m (h : Model p d).u (h : Model p d).v),
        (h : Model p d).u,
        (h : Model p d).v + m * (h : Model p d).u⟩,
      shift_mem_subA h _ _ _⟩ : subA p d) =
      h * zElt p d (tauP p d m (h : Model p d).u (h : Model p d).v) *
        bElt p d (m * (h : Model p d).u) := by
  refine Subtype.ext ?_
  set P : ZMod p := tauP p d m (h : Model p d).u (h : Model p d).v with hP
  have h1 : (h : Model p d) * (zElt p d P : Model p d) =
      ⟨(h : Model p d).α + liftp p P, (h : Model p d).u,
        (h : Model p d).v⟩ := by
    change (h : Model p d) * ⟨liftp p P, 0, 0⟩ = _
    rw [mul_def]
    ext
    · change (h : Model p d).α + liftp p P +
          liftp p (tauP p d (redp p (liftp p P)) (h : Model p d).u
            (h : Model p d).v) +
          dc d * carryF p (h : Model p d).u 0 =
        (h : Model p d).α + liftp p P
      rw [redp_liftp, tauP_zero_left, liftp_zero, carryF_zero]
      ring
    · change (h : Model p d).u + 0 = (h : Model p d).u
      ring
    · change (h : Model p d).v + 0 + redp p (liftp p P) * (h : Model p d).u =
        (h : Model p d).v
      rw [redp_liftp]
      ring
  change _ = ((h : Model p d) * (zElt p d P : Model p d)) *
    (bElt p d (m * (h : Model p d).u) : Model p d)
  rw [h1]
  change _ = (⟨(h : Model p d).α + liftp p P, (h : Model p d).u,
      (h : Model p d).v⟩ : Model p d) * ⟨0, 0, m * (h : Model p d).u⟩
  rw [mul_def]
  ext
  · change (h : Model p d).α + liftp p P =
      (h : Model p d).α + liftp p P + 0 +
        liftp p (tauP p d (redp p (0 : ZMod (p ^ 2))) (h : Model p d).u
          (h : Model p d).v) +
        dc d * carryF p (h : Model p d).u 0
    rw [map_zero, tauP_zero_left, liftp_zero, carryF_zero]
    ring
  · change (h : Model p d).u = (h : Model p d).u + 0
    ring
  · change (h : Model p d).v + m * (h : Model p d).u =
      (h : Model p d).v + m * (h : Model p d).u +
        redp p (0 : ZMod (p ^ 2)) * (h : Model p d).u
    rw [map_zero]
    ring

/-- **The Gauss-sum reduction of the A-block**: for any character `χ` of
`A` and any `h = a^α s^u b^v ∈ A`,
`φ_{A,h}[A,χ] = χ(h) · ∑_{m<p} ψ(dmu + mv + T(m)u) · φ(mu)`
where `ψ(t) = χ(a^{pt})` and `φ(w) = χ(b^w)` are additive characters of
`ZMod p`. The entry is `χ(h)` times a quadratic exponential sum — the
`G₁`/`G₂` entry formulas evaluate exactly these. -/
theorem species_A_block_reduced (χ : subA p d →* ℂˣ) (h : subA p d) :
    species (subA p d) h (basisElt (subA p d) χ) =
      ((χ h : ℂˣ) : ℂ) *
        ∑ m : ZMod p,
          ((χ (zElt p d (tauP p d m (h : Model p d).u (h : Model p d).v)) :
            ℂˣ) : ℂ) *
          ((χ (bElt p d (m * (h : Model p d).u)) : ℂˣ) : ℂ) := by
  rw [species_A_block_expsum, Finset.mul_sum]
  refine Finset.sum_congr rfl fun m _ => ?_
  rw [shifted_eq h m, map_mul, map_mul]
  rw [Units.val_mul, Units.val_mul]
  ring

end Model

end P4

end LeanDring
