/-
Copyright (c) 2026 Tilemachos Vassias. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tilemachos Vassias (formalization assisted by Claude)
-/
import LeanDring.P4.ABlock
import Mathlib.NumberTheory.GaussSum
import Mathlib.NumberTheory.LegendreSymbol.QuadraticChar.Basic

/-!
# Quadratic character sums and the Gauss-sum form of the A-block

Generic layer: for a nontrivial additive character `ψ` of `ZMod p`
(`p` odd prime) and `A ≠ 0`,

* `sum_addChar_sq`     : `∑ₘ ψ(m²) = g(χ₂, ψ)` (square-counting via
  `quadraticChar_card_sqrts`),
* `sum_addChar_mul_sq` : `∑ₘ ψ(Am²) = χ₂(A)·g(χ₂, ψ)`,
* `sum_addChar_quad`   : `∑ₘ ψ(Am² + Bm) = ψ(−B²/4A)·χ₂(A)·g(χ₂, ψ)`
  (completing the square),
* `addChar_eq_mulShift`: the dual of `ZMod p` is generated by any
  nontrivial `ψ`: every `φ` is `ψ.mulShift κ`.

Model layer (**the `G₁` entry shape**): `species_A_block_gauss` —
for a character `χ` of `A` nontrivial on the central `a^p` (so `ψ ≠ 1`),
`h = a^α s^u b^v` with `u ≠ 0`, and `κ` the dual coordinate of `χ` on `b`:

  `φ_{A,h}[A,χ] = χ(h) · ψ(−B²/4A) · χ₂(A) · g(χ₂, ψ)`

with `A = u/2`, `B = du + v − u/2 + κu`. The quadratic character of `2⁻¹u`
and the Gauss sum `g(χ₂, ψ)` — with `d` inside the phase `ψ(−B²/4A)` — are
exactly the objects compared between (xii) and (xiii).
-/

namespace LeanDring

namespace P4

open Finset AddChar

variable {p : ℕ} [Fact p.Prime] [Fact (Odd p)]

/-- The quadratic character of `ZMod p`, valued in `ℂ`. -/
noncomputable def χq (p : ℕ) [Fact p.Prime] : MulChar (ZMod p) ℂ :=
  (quadraticChar (ZMod p)).ringHomComp (Int.castRingHom ℂ)

omit [Fact (Odd p)] in
theorem χq_isQuadratic : (χq p).IsQuadratic :=
  (quadraticChar_isQuadratic (ZMod p)).comp _

theorem ringChar_zmod_ne_two : ringChar (ZMod p) ≠ 2 := by
  have hodd : Odd p := Fact.out
  rw [ZMod.ringChar_zmod_n]
  intro h
  rw [h, Nat.odd_iff] at hodd
  omega

omit [Fact (Odd p)] in
/-- Any additive character of `ZMod p` is `ψ x = ψ(1)^x.val`. -/
theorem addChar_apply_val (ψ : AddChar (ZMod p) ℂ) (x : ZMod p) :
    ψ x = ψ 1 ^ x.val := by
  have hx : x = x.val • (1 : ZMod p) := by
    rw [nsmul_eq_mul, mul_one, ZMod.natCast_val, ZMod.cast_id]
  conv_lhs => rw [hx]
  exact map_nsmul_eq_pow ψ x.val 1

omit [Fact (Odd p)] in
/-- Additive characters of `ZMod p` are determined by their value at `1`. -/
theorem addChar_ext_of_apply_one (ψ φ : AddChar (ZMod p) ℂ)
    (h : ψ 1 = φ 1) : ψ = φ := by
  refine DFunLike.ext _ _ fun x => ?_
  rw [addChar_apply_val ψ x, addChar_apply_val φ x, h]

omit [Fact (Odd p)] in
/-- `ψ(1)^p = 1` for any additive character of `ZMod p`. -/
theorem addChar_one_pow (ψ : AddChar (ZMod p) ℂ) : ψ 1 ^ p = 1 := by
  rw [← map_nsmul_eq_pow ψ p 1]
  have h1 : p • (1 : ZMod p) = 0 := by
    rw [nsmul_eq_mul, mul_one, ZMod.natCast_self]
  rw [h1, map_zero_eq_one]

omit [Fact (Odd p)] in
/-- **The dual of `ZMod p` is generated by any nontrivial character**:
every additive character `φ` is a `mulShift` of `ψ`. -/
theorem addChar_eq_mulShift (ψ φ : AddChar (ZMod p) ℂ) (hψ : ψ ≠ 1) :
    ∃ κ : ZMod p, φ = ψ.mulShift κ := by
  have hp : p.Prime := Fact.out
  have hζ1 : ψ 1 ≠ 1 := (zmod_char_ne_one_iff p ψ).mp hψ
  have hord : orderOf (ψ 1) = p := orderOf_eq_prime (addChar_one_pow ψ) hζ1
  have hprim : IsPrimitiveRoot (ψ 1) p := by
    have := IsPrimitiveRoot.orderOf (ψ 1)
    rwa [hord] at this
  obtain ⟨k, -, hk⟩ := hprim.eq_pow_of_pow_eq_one (addChar_one_pow φ)
  refine ⟨(k : ZMod p), addChar_ext_of_apply_one φ (ψ.mulShift (k : ZMod p))
    ?_⟩
  rw [mulShift_apply, mul_one, addChar_apply_val ψ ((k : ZMod p)),
    ZMod.val_natCast, ← hk]
  conv_lhs => rw [← pow_mod_orderOf, hord]

/-- Square-counting: `∑ₘ ψ(m²) = g(χ₂, ψ)` for nontrivial `ψ`. -/
theorem sum_addChar_sq (ψ : AddChar (ZMod p) ℂ) (hψ : ψ ≠ 1) :
    ∑ m : ZMod p, ψ (m ^ 2) = gaussSum (χq p) ψ := by
  classical
  have hfib : ∑ m : ZMod p, ψ (m ^ 2) =
      ∑ x : ZMod p, ∑ m ∈ univ.filter (fun m : ZMod p => m ^ 2 = x),
        ψ (m ^ 2) :=
    (Finset.sum_fiberwise_of_maps_to (fun m _ => mem_univ _) _).symm
  have hinner : ∀ x : ZMod p,
      (∑ m ∈ univ.filter (fun m : ZMod p => m ^ 2 = x), ψ (m ^ 2)) =
        (χq p x + 1) * ψ x := by
    intro x
    have hval : ∀ m ∈ univ.filter (fun m : ZMod p => m ^ 2 = x),
        ψ (m ^ 2) = ψ x := by
      intro m hm
      rw [(Finset.mem_filter.mp hm).2]
    rw [Finset.sum_congr rfl hval, Finset.sum_const, nsmul_eq_mul]
    congr 1
    -- the fiber count is `χ₂(x) + 1`
    have hcount := quadraticChar_card_sqrts (F := ZMod p)
      ringChar_zmod_ne_two x
    have hset : {y : ZMod p | y ^ 2 = x}.toFinset =
        univ.filter (fun m : ZMod p => m ^ 2 = x) := by
      ext y
      simp
    rw [hset] at hcount
    have : ((univ.filter (fun m : ZMod p => m ^ 2 = x)).card : ℂ) =
        (((univ.filter (fun m : ZMod p => m ^ 2 = x)).card : ℤ) : ℂ) := by
      push_cast
      rfl
    rw [this, hcount]
    push_cast
    rfl
  rw [hfib, Finset.sum_congr rfl fun x _ => hinner x]
  have hsplit : ∑ x : ZMod p, (χq p x + 1) * ψ x =
      (∑ x : ZMod p, χq p x * ψ x) + ∑ x : ZMod p, ψ x := by
    rw [← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun x _ => ?_
    ring
  rw [hsplit, AddChar.sum_eq_zero_of_ne_one hψ, add_zero]
  rfl

/-- `∑ₘ ψ(Am²) = χ₂(A)·g(χ₂, ψ)` for `A ≠ 0`, nontrivial `ψ`. -/
theorem sum_addChar_mul_sq (ψ : AddChar (ZMod p) ℂ) (hψ : ψ ≠ 1)
    {A : ZMod p} (hA : A ≠ 0) :
    ∑ m : ZMod p, ψ (A * m ^ 2) = χq p A * gaussSum (χq p) ψ := by
  have hAu : IsUnit A := Ne.isUnit hA
  have hshift : ∀ m : ZMod p, ψ (A * m ^ 2) = (ψ.mulShift A) (m ^ 2) := by
    intro m
    rw [mulShift_apply]
  have hne : ψ.mulShift A ≠ 1 := (IsPrimitive.of_ne_one hψ) hA
  rw [Finset.sum_congr rfl fun m _ => hshift m, sum_addChar_sq _ hne]
  have hgs := gaussSum_mulShift (χq p) ψ hAu.unit
  have hAcoe : ((hAu.unit : (ZMod p)ˣ) : ZMod p) = A := hAu.unit_spec
  rw [hAcoe] at hgs
  -- multiply `hgs` by `χq A` and use `χq(A)² = 1`
  have hsq : χq p A * χq p A = 1 := by
    have h1 : quadraticChar (ZMod p) A ^ 2 = 1 := quadraticChar_sq_one hA
    have h2 : χq p A = ((quadraticChar (ZMod p) A : ℤ) : ℂ) := rfl
    rw [h2, ← Int.cast_mul, ← pow_two, h1, Int.cast_one]
  calc gaussSum (χq p) (ψ.mulShift A)
      = 1 * gaussSum (χq p) (ψ.mulShift A) := (one_mul _).symm
    _ = χq p A * (χq p A * gaussSum (χq p) (ψ.mulShift A)) := by
        rw [← mul_assoc, hsq]
    _ = χq p A * gaussSum (χq p) ψ := by rw [hgs]

/-- **Completing the square**: for `A ≠ 0` and nontrivial `ψ`,
`∑ₘ ψ(Am² + Bm) = ψ(−B²·(4A)⁻¹) · χ₂(A) · g(χ₂, ψ)`. -/
theorem sum_addChar_quad (ψ : AddChar (ZMod p) ℂ) (hψ : ψ ≠ 1)
    {A : ZMod p} (hA : A ≠ 0) (B : ZMod p) :
    ∑ m : ZMod p, ψ (A * m ^ 2 + B * m) =
      ψ (- B ^ 2 * (4 * A)⁻¹) * (χq p A * gaussSum (χq p) ψ) := by
  have h2 : (2 : ZMod p) ≠ 0 := two_ne_zero'
  have h4 : (4 : ZMod p) ≠ 0 := by
    have : (4 : ZMod p) = 2 * 2 := by norm_num
    rw [this]
    exact mul_ne_zero h2 h2
  set c : ZMod p := B * (2 * A)⁻¹ with hc
  have hkey : ∀ n : ZMod p, A * (n - c) ^ 2 + B * (n - c) =
      A * n ^ 2 + - B ^ 2 * (4 * A)⁻¹ := by
    intro n
    rw [hc]
    have h2A : (2 * A) ≠ 0 := mul_ne_zero h2 hA
    have h4A : (4 * A) ≠ 0 := mul_ne_zero h4 hA
    field_simp
    ring
  have hre : ∑ m : ZMod p, ψ (A * m ^ 2 + B * m) =
      ∑ n : ZMod p, ψ (A * (n - c) ^ 2 + B * (n - c)) :=
    (Fintype.sum_bijective (fun n : ZMod p => n - c)
      (Equiv.subRight c).bijective _ _ fun n => rfl).symm
  rw [hre, Finset.sum_congr rfl fun n _ => congrArg ψ (hkey n)]
  have hsplit : ∀ n : ZMod p, ψ (A * n ^ 2 + - B ^ 2 * (4 * A)⁻¹) =
      ψ (- B ^ 2 * (4 * A)⁻¹) * ψ (A * n ^ 2) := by
    intro n
    rw [← map_add_eq_mul]
    congr 1
    ring
  rw [Finset.sum_congr rfl fun n _ => hsplit n, ← Finset.mul_sum,
    sum_addChar_mul_sq ψ hψ hA]

namespace Model

open DRing

variable {d : ZMod p}

/-- The additive character `ψ(t) = χ(a^{pt})` of `ZMod p` attached to a
character `χ` of `A` (its restriction to the central `⟨aᵖ⟩`). -/
noncomputable def zChar (χ : subA p d →* ℂˣ) : AddChar (ZMod p) ℂ where
  toFun z := ((χ (zElt p d z) : ℂˣ) : ℂ)
  map_zero_eq_one' := by
    have h0 : zElt p d 0 = 1 := by
      refine Subtype.ext ?_
      change (⟨liftp p 0, 0, 0⟩ : Model p d) = 1
      rw [one_def, liftp_zero]
    change ((χ (zElt p d 0) : ℂˣ) : ℂ) = 1
    rw [h0, map_one]
    rfl
  map_add_eq_mul' a b := by
    change ((χ (zElt p d (a + b)) : ℂˣ) : ℂ) = _
    rw [zElt_add, map_mul]
    rfl

/-- The additive character `φ(w) = χ(b^w)` of `ZMod p` attached to a
character `χ` of `A` (its restriction to `⟨b⟩`). -/
noncomputable def bChar (χ : subA p d →* ℂˣ) : AddChar (ZMod p) ℂ where
  toFun w := ((χ (bElt p d w) : ℂˣ) : ℂ)
  map_zero_eq_one' := by
    have h0 : bElt p d 0 = 1 := by
      refine Subtype.ext ?_
      change (⟨0, 0, 0⟩ : Model p d) = 1
      rw [one_def]
    change ((χ (bElt p d 0) : ℂˣ) : ℂ) = 1
    rw [h0, map_one]
    rfl
  map_add_eq_mul' a b := by
    change ((χ (bElt p d (a + b)) : ℂˣ) : ℂ) = _
    rw [bElt_add, map_mul]
    rfl

/-- The `tauP`-exponent plus the `b`-twist is an explicit quadratic:
`P(m; u, v) + κ·mu = (u/2)·m² + (du + v − u/2 + κu)·m`. -/
theorem tauP_add_twist (m u v κ : ZMod p) :
    tauP p d m u v + κ * (m * u) =
      (u * (2 : ZMod p)⁻¹) * m ^ 2 +
        (d * u + v - u * (2 : ZMod p)⁻¹ + κ * u) * m := by
  have hinv : (2 : ZMod p) * (2 : ZMod p)⁻¹ = 1 :=
    ZMod.mul_inv_of_unit _ two_isUnit'
  unfold tauP tri
  have hexp : m * (m - 1) * (2 : ZMod p)⁻¹ * u =
      (u * (2 : ZMod p)⁻¹) * m ^ 2 - (u * (2 : ZMod p)⁻¹) * m := by
    ring
  rw [hexp]
  ring

/-- **The Gauss-sum evaluation of the A-block (the `G₁` entry
shape)**: if `χ` is nontrivial on the center (`ψ := zChar χ ≠ 1`),
`h = a^α s^u b^v ∈ A` has `u ≠ 0`, and `κ` is the dual coordinate of `χ`
on `b` (i.e. `bChar χ = ψ.mulShift κ`), then with
`A₀ = u/2`, `B₀ = du + v − u/2 + κu`:

  `φ_{A,h}[A,χ] = χ(h) · ψ(−B₀²/(4A₀)) · χ₂(A₀) · g(χ₂, ψ)`.

The parameter `d` sits inside the phase `ψ(−B₀²/(4A₀))`; the quadratic
character and the Gauss sum carry the square-class information. -/
theorem species_A_block_gauss (χ : subA p d →* ℂˣ) (h : subA p d)
    (hψ : zChar χ ≠ 1) (hu : (h : Model p d).u ≠ 0)
    (κ : ZMod p) (hκ : bChar χ = (zChar χ).mulShift κ) :
    species (subA p d) h (basisElt (subA p d) χ) =
      ((χ h : ℂˣ) : ℂ) *
        (zChar χ (- (d * (h : Model p d).u + (h : Model p d).v -
            (h : Model p d).u * (2 : ZMod p)⁻¹ + κ * (h : Model p d).u) ^ 2 *
            (4 * ((h : Model p d).u * (2 : ZMod p)⁻¹))⁻¹) *
          (χq p ((h : Model p d).u * (2 : ZMod p)⁻¹) *
            gaussSum (χq p) (zChar χ))) := by
  have h2 : (2 : ZMod p) ≠ 0 := two_ne_zero'
  have hA0 : (h : Model p d).u * (2 : ZMod p)⁻¹ ≠ 0 :=
    mul_ne_zero hu (inv_ne_zero h2)
  rw [species_A_block_reduced]
  congr 1
  -- the sum: summands combine into a single quadratic ψ-sum
  have hterm : ∀ m : ZMod p,
      ((χ (zElt p d (tauP p d m (h : Model p d).u (h : Model p d).v)) :
        ℂˣ) : ℂ) *
      ((χ (bElt p d (m * (h : Model p d).u)) : ℂˣ) : ℂ) =
      zChar χ (((h : Model p d).u * (2 : ZMod p)⁻¹) * m ^ 2 +
        (d * (h : Model p d).u + (h : Model p d).v -
          (h : Model p d).u * (2 : ZMod p)⁻¹ + κ * (h : Model p d).u) * m) := by
    intro m
    have h1 : ((χ (zElt p d (tauP p d m (h : Model p d).u
        (h : Model p d).v)) : ℂˣ) : ℂ) =
        zChar χ (tauP p d m (h : Model p d).u (h : Model p d).v) := rfl
    have hb : ((χ (bElt p d (m * (h : Model p d).u)) : ℂˣ) : ℂ) =
        bChar χ (m * (h : Model p d).u) := rfl
    rw [h1, hb, hκ, mulShift_apply, ← map_add_eq_mul, ← tauP_add_twist]
  rw [Finset.sum_congr rfl fun m _ => hterm m,
    sum_addChar_quad (zChar χ) hψ hA0]

end Model

end P4

end LeanDring
