Print("=== Route 1b: load tomlib, retry ===\n");
r := LoadPackage("tomlib");
Print("tomlib loaded: ", r, "\n");
tomO := TableOfMarks("O7(3)");
Print("O7(3) tom: ", tomO, "\n");
tomS := TableOfMarks("S6(3)");
Print("S6(3) tom: ", tomS, "\n");
Print("Trying alt names...\n");
Print("Omega(7,3): ", TableOfMarks("Omega(7,3)"), "\n");
Print("PSp(6,3): ", TableOfMarks("PSp(6,3)"), "\n");
Print("Sp(6,3): ", TableOfMarks("Sp(6,3)"), "\n");
Print("=== done route1b probe ===\n");
