/-
Copyright (c) 2026 Tilemachos Vassias. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tilemachos Vassias (formalization assisted by Claude)
-/
import LeanDring.P5.Certificate.ComputableModel.Twin1.ComputableGroup
import Mathlib.GroupTheory.Coset.Card
import Mathlib.Algebra.Group.Subgroup.Pointwise

/-!
# Canonical generating sequences for subgroups of the order-`5^5` group

Building on the computable group `Coordinate q` of
`LeanDring.P5.Certificate.ComputableModel.Twin1.ComputableGroup`, this file
provides a *canonical generating sequence* (induced pcgs) layer against the pc
chief series `depthGE d = ⟨g_d, …, g_4⟩` (the tail subgroups, each normal).

A subgroup is represented by an echelonized generator list: pivot depths
strictly increasing, leading coordinate `1`, and each generator's fifth power
and conjugates lying in the subgroup generated by the deeper ones (`wfB`, whose
positive answers imply the semantic predicate `WF`).  For such a list, `siftB`
decides membership (`sift_mem_iff`), the order is `5 ^ length` (`card_ofList`),
and `Cgs.cgsEquiv` decides equality of the generated subgroups
(`Cgs.cgsEquiv_iff`).  Everything stays at generator-list / `F₅`-linear-algebra
level: no subgroup is ever materialised as a `Finset` of the 3125 carrier
elements.
-/

namespace LeanDring.P5Presentation

open Function
open Fin.NatCast
open scoped Pointwise

/-! ## Coordinate extraction and additivity along the chief series -/

/-- The `i`-th pc coordinate, as an element of `Fin 5` (`= ZMod 5`). -/
def coordAt (x : Coordinates) : ℕ → Fin 5
  | 0 => x.1
  | 1 => x.2.1
  | 2 => x.2.2.1
  | 3 => x.2.2.2.1
  | 4 => x.2.2.2.2
  | _ + 5 => 0

@[simp] theorem coordAt_zero (x : Coordinates) : coordAt x 0 = x.1 := rfl
@[simp] theorem coordAt_one (x : Coordinates) : coordAt x 1 = x.2.1 := rfl
@[simp] theorem coordAt_two (x : Coordinates) : coordAt x 2 = x.2.2.1 := rfl
@[simp] theorem coordAt_three (x : Coordinates) : coordAt x 3 = x.2.2.2.1 := rfl
@[simp] theorem coordAt_four (x : Coordinates) : coordAt x 4 = x.2.2.2.2 := rfl

/-! ### Generic iterate projection lemmas -/

theorem iterate_proj_const {p : Coordinates → Fin 5} {f : Coordinates → Coordinates}
    (h : ∀ x, p (f x) = p x) (n : ℕ) (x : Coordinates) : p (f^[n] x) = p x := by
  induction n with
  | zero => simp
  | succ n ih => rw [Function.iterate_succ_apply', h, ih]

theorem iterate_proj_succ {p : Coordinates → Fin 5} {f : Coordinates → Coordinates}
    (h : ∀ x, p (f x) = p x + 1) (n : ℕ) (x : Coordinates) : p (f^[n] x) = p x + (n : Fin 5) := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [Function.iterate_succ_apply', h, ih]
      push_cast
      abel

/-! ### Per-step coordinate deltas -/

/-- `step q d` increments coordinate `d` by one. -/
theorem step_add (q : ℕ) (d : Fin 5) (x : Coordinates) :
    coordAt (step q d x) d = coordAt x d + 1 := by
  fin_cases d <;> rcases x with ⟨a, b, c, e, f⟩ <;> rfl

/-- `step q k` preserves coordinate `d` whenever `d < k`. -/
theorem step_preserve (q : ℕ) (d k : Fin 5) (h : (d : ℕ) < k) (x : Coordinates) :
    coordAt (step q k x) d = coordAt x d := by
  fin_cases d <;> fin_cases k <;> simp_all <;> rcases x with ⟨a, b, c, e, f⟩ <;> rfl

/-! ### The additivity theorem: right factor in `depthGE d` -/

/-- **Coordinate additivity along the chief series.** If the right factor `b`
lies in the tail subgroup `depthGE d` (its coordinates below `d` vanish), then
coordinate `d` of the product is the sum of the two `d`-coordinates. The left
factor `a` is arbitrary. This is the chief-quotient homomorphism made explicit. -/
theorem coordAt_mulC_right (q : ℕ) (d : ℕ) (hd : d < 5) (a b : Coordinates)
    (hb : ∀ i, i < d → coordAt b i = 0) :
    coordAt (mulC q a b) d = coordAt a d + coordAt b d := by
  -- abbreviations for the five iterate counts
  interval_cases d
  · -- d = 0 : only step 0 touches coord 0; it is applied `b.1` times
    simp only [mulC]
    rw [iterate_proj_const (p := (coordAt · 0)) (f := step q 4)
          (fun x => step_preserve q 0 4 (by decide) x),
        iterate_proj_const (p := (coordAt · 0)) (f := step q 3)
          (fun x => step_preserve q 0 3 (by decide) x),
        iterate_proj_const (p := (coordAt · 0)) (f := step q 2)
          (fun x => step_preserve q 0 2 (by decide) x),
        iterate_proj_const (p := (coordAt · 0)) (f := step q 1)
          (fun x => step_preserve q 0 1 (by decide) x),
        iterate_proj_succ (p := (coordAt · 0)) (f := step q 0)
          (fun x => step_add q 0 x)]
    simp [coordAt, Fin.cast_val_eq_self]
  · -- d = 1
    have hb0 : (b.1 : ℕ) = 0 := by
      have := hb 0 (by norm_num); simpa [coordAt] using congrArg Fin.val this
    simp only [mulC, hb0, Function.iterate_zero, id_eq]
    rw [iterate_proj_const (p := (coordAt · 1)) (f := step q 4)
          (fun x => step_preserve q 1 4 (by decide) x),
        iterate_proj_const (p := (coordAt · 1)) (f := step q 3)
          (fun x => step_preserve q 1 3 (by decide) x),
        iterate_proj_const (p := (coordAt · 1)) (f := step q 2)
          (fun x => step_preserve q 1 2 (by decide) x),
        iterate_proj_succ (p := (coordAt · 1)) (f := step q 1)
          (fun x => step_add q 1 x)]
    simp [coordAt, Fin.cast_val_eq_self]
  · -- d = 2
    have hb0 : (b.1 : ℕ) = 0 := by
      have := hb 0 (by norm_num); simpa [coordAt] using congrArg Fin.val this
    have hb1 : (b.2.1 : ℕ) = 0 := by
      have := hb 1 (by norm_num); simpa [coordAt] using congrArg Fin.val this
    simp only [mulC, hb0, hb1, Function.iterate_zero, id_eq]
    rw [iterate_proj_const (p := (coordAt · 2)) (f := step q 4)
          (fun x => step_preserve q 2 4 (by decide) x),
        iterate_proj_const (p := (coordAt · 2)) (f := step q 3)
          (fun x => step_preserve q 2 3 (by decide) x),
        iterate_proj_succ (p := (coordAt · 2)) (f := step q 2)
          (fun x => step_add q 2 x)]
    simp [coordAt, Fin.cast_val_eq_self]
  · -- d = 3
    have hb0 : (b.1 : ℕ) = 0 := by
      have := hb 0 (by norm_num); simpa [coordAt] using congrArg Fin.val this
    have hb1 : (b.2.1 : ℕ) = 0 := by
      have := hb 1 (by norm_num); simpa [coordAt] using congrArg Fin.val this
    have hb2 : (b.2.2.1 : ℕ) = 0 := by
      have := hb 2 (by norm_num); simpa [coordAt] using congrArg Fin.val this
    simp only [mulC, hb0, hb1, hb2, Function.iterate_zero, id_eq]
    rw [iterate_proj_const (p := (coordAt · 3)) (f := step q 4)
          (fun x => step_preserve q 3 4 (by decide) x),
        iterate_proj_succ (p := (coordAt · 3)) (f := step q 3)
          (fun x => step_add q 3 x)]
    simp [coordAt, Fin.cast_val_eq_self]
  · -- d = 4
    have hb0 : (b.1 : ℕ) = 0 := by
      have := hb 0 (by norm_num); simpa [coordAt] using congrArg Fin.val this
    have hb1 : (b.2.1 : ℕ) = 0 := by
      have := hb 1 (by norm_num); simpa [coordAt] using congrArg Fin.val this
    have hb2 : (b.2.2.1 : ℕ) = 0 := by
      have := hb 2 (by norm_num); simpa [coordAt] using congrArg Fin.val this
    have hb3 : (b.2.2.2.1 : ℕ) = 0 := by
      have := hb 3 (by norm_num); simpa [coordAt] using congrArg Fin.val this
    simp only [mulC, hb0, hb1, hb2, hb3, Function.iterate_zero, id_eq]
    rw [iterate_proj_succ (p := fun y => coordAt y 4) (f := step q 4)
          (fun x => step_add q 4 x)]
    simp [coordAt]

theorem coordAt_zero_all (i : ℕ) : coordAt ((0, 0, 0, 0, 0) : Coordinates) i = 0 := by
  rcases i with _ | _ | _ | _ | _ | i <;> rfl

/-! ## Additivity for the group multiplication of `Coordinate q` -/

/-- The group multiplication on `Coordinate q` is the computable `mulC` (global
`Mul` instance), so coordinate additivity transfers verbatim. -/
theorem coordAt_mul_right (q d : ℕ) (hd : d < 5) (a b : Coordinate q)
    (hb : ∀ i, i < d → coordAt b i = 0) :
    coordAt (a * b) d = coordAt a d + coordAt b d :=
  coordAt_mulC_right q d hd a b hb

/-! ## Pivot depth -/

/-- The pivot depth of a coordinate vector: the index of its first nonzero
coordinate (`5` for the identity). -/
def pivotDepth (x : Coordinates) : ℕ :=
  if x.1 ≠ 0 then 0
  else if x.2.1 ≠ 0 then 1
  else if x.2.2.1 ≠ 0 then 2
  else if x.2.2.2.1 ≠ 0 then 3
  else if x.2.2.2.2 ≠ 0 then 4
  else 5

theorem pivotDepth_le_five (x : Coordinates) : pivotDepth x ≤ 5 := by
  unfold pivotDepth; split_ifs <;> omega

theorem coordAt_of_lt_pivotDepth (x : Coordinates) (i : ℕ) (h : i < pivotDepth x) :
    coordAt x i = 0 := by
  unfold pivotDepth at h
  split_ifs at h with h0 h1 h2 h3 h4 <;>
    interval_cases i <;> simp_all [coordAt]

theorem coordAt_pivotDepth_ne (x : Coordinates) (h : pivotDepth x < 5) :
    coordAt x (pivotDepth x) ≠ 0 := by
  unfold pivotDepth at h ⊢
  split_ifs at h ⊢ with h0 h1 h2 h3 h4 <;> simp_all [coordAt]

/-! ## The chief-series tail subgroups `depthGE d = ⟨g_d, …, g_4⟩` -/

/-- The tail subgroup: coordinate vectors whose coordinates below `d` vanish.
This is the normal chief-series member `C_{5-d}`. -/
def depthGE (q : ℕ) (hq : q = 1 ∨ q = 2) (d : ℕ) :
    letI := coordinateGroup q hq; Subgroup (Coordinate q) :=
  letI := coordinateGroup q hq
  { carrier := {x : Coordinate q | ∀ i, i < d → coordAt x i = 0}
    one_mem' := by intro i _; exact coordAt_zero_all i
    mul_mem' := by
      intro x y hx hy i hi
      by_cases h5 : i < 5
      · rw [coordAt_mul_right q i h5 x y (fun j hj => hy j (lt_trans hj hi)),
          hx i hi, hy i hi, add_zero]
      · rcases i with _ | _ | _ | _ | _ | i
        all_goals first | omega | rfl
    inv_mem' := by
      intro x hx i hi
      by_cases h5 : i < 5
      · have hxx : x⁻¹ * x = 1 := inv_mul_cancel x
        have := coordAt_mul_right q i h5 x⁻¹ x (fun j hj => hx j (lt_trans hj hi))
        rw [hxx] at this
        have h1 : coordAt (1 : Coordinate q) i = 0 := coordAt_zero_all i
        rw [h1, hx i hi, add_zero] at this
        exact this.symm
      · rcases i with _ | _ | _ | _ | _ | i
        all_goals first | omega | rfl }

theorem mem_depthGE {q : ℕ} (hq : q = 1 ∨ q = 2) (d : ℕ) (x : Coordinate q) :
    letI := coordinateGroup q hq
    x ∈ depthGE q hq d ↔ ∀ i, i < d → coordAt x i = 0 :=
  Iff.rfl

/-- Every vector lies in the tail subgroup indexed by its own pivot depth. -/
theorem self_mem_depthGE_pivotDepth {q : ℕ} (hq : q = 1 ∨ q = 2) (x : Coordinate q) :
    letI := coordinateGroup q hq
    x ∈ depthGE q hq (pivotDepth x) :=
  fun i hi => coordAt_of_lt_pivotDepth x i hi

/-- Coordinate `d` restricts to a group homomorphism on the tail subgroup
`depthGE d` — the chief-quotient map made explicit. -/
def coordHom (q : ℕ) (hq : q = 1 ∨ q = 2) (d : ℕ) (hd : d < 5) :
    letI := coordinateGroup q hq
    depthGE q hq d →* Multiplicative (Fin 5) :=
  letI := coordinateGroup q hq
  { toFun := fun x => Multiplicative.ofAdd (coordAt (x : Coordinate q) d)
    map_one' := by
      change Multiplicative.ofAdd (coordAt ((1 : depthGE q hq d) : Coordinate q) d) = 1
      rw [Subgroup.coe_one]
      change Multiplicative.ofAdd (coordAt ((0, 0, 0, 0, 0) : Coordinates) d) = 1
      rw [coordAt_zero_all d]; rfl
    map_mul' := fun x y => by
      change Multiplicative.ofAdd (coordAt (((x * y : depthGE q hq d) : Coordinate q)) d)
          = Multiplicative.ofAdd (coordAt (x : Coordinate q) d)
            * Multiplicative.ofAdd (coordAt (y : Coordinate q) d)
      rw [Subgroup.coe_mul,
        coordAt_mul_right q d hd (x : Coordinate q) (y : Coordinate q)
          (fun j hj => y.property j hj)]
      rfl }

/-- The lead coordinate is additive along powers of an element of the tail
subgroup: `coordAt (a ^ i) d = i • coordAt a d`. -/
theorem coordAt_zpow {q : ℕ} (hq : q = 1 ∨ q = 2) (d : ℕ) (hd : d < 5)
    (a : Coordinate q) (ha : letI := coordinateGroup q hq; a ∈ depthGE q hq d) (i : ℤ) :
    letI := coordinateGroup q hq
    coordAt (a ^ i) d = i • coordAt a d := by
  letI := coordinateGroup q hq
  have hmap := (coordHom q hq d hd).map_zpow ⟨a, ha⟩ i
  have hcoe : (((⟨a, ha⟩ : depthGE q hq d) ^ i : depthGE q hq d) : Coordinate q) = a ^ i :=
    Subgroup.coe_zpow _ _ i
  have hL : coordHom q hq d hd (⟨a, ha⟩ ^ i)
      = Multiplicative.ofAdd (coordAt (a ^ i) d) := by
    change Multiplicative.ofAdd (coordAt (((⟨a, ha⟩ : depthGE q hq d) ^ i : depthGE q hq d)
        : Coordinate q) d) = _
    rw [hcoe]
  have hR : (coordHom q hq d hd ⟨a, ha⟩) ^ i
      = Multiplicative.ofAdd (i • coordAt a d) := by
    change (Multiplicative.ofAdd (coordAt a d)) ^ i = _
    rw [← ofAdd_zsmul]
  rw [hL, hR] at hmap
  exact Multiplicative.ofAdd.injective hmap

/-- `n • 1 = n` reflection in `Fin 5`, needed to identify a pivot exponent. -/
theorem zsmul_one_fin5 (t : Fin 5) : ((t.val : ℤ)) • (1 : Fin 5) = t := by
  have h1 : ((t.val : ℤ)) • (1 : ZMod 5) = t := by
    rw [zsmul_eq_mul, mul_one]; push_cast; exact ZMod.natCast_zmod_val (n := 5) t
  convert h1 using 2 <;> rfl

/-- The lead-coordinate identity `j • 1 = t` forces `5 ∣ (j - t.val)`. -/
theorem dvd_of_zsmul_one (j : ℤ) (t : Fin 5) (h : j • (1 : Fin 5) = t) :
    (5 : ℤ) ∣ (j - (t.val : ℤ)) := by
  have hzero : (((j - (t.val : ℤ)) : ℤ) : ZMod 5) = 0 := by
    have h2 : (j • (1 : ZMod 5)) = t := by convert h using 2 <;> rfl
    rw [zsmul_eq_mul, mul_one] at h2
    push_cast
    rw [sub_eq_zero, h2]
    exact (ZMod.natCast_zmod_val (n := 5) t).symm
  exact (ZMod.intCast_zmod_eq_zero_iff_dvd _ 5).mp hzero

/-! ## Computable powers, the clearing step, and the sift -/

/-- Computable right-fold power `p ^ n` on the raw coordinate space. -/
def mpow (q : ℕ) (p : Coordinates) : ℕ → Coordinates
  | 0 => (0, 0, 0, 0, 0)
  | n + 1 => mulC q (mpow q p n) p

theorem mpow_eq_pow {q : ℕ} (hq : q = 1 ∨ q = 2) (p : Coordinate q) (n : ℕ) :
    letI := coordinateGroup q hq
    mpow q p n = p ^ n := by
  letI := coordinateGroup q hq
  induction n with
  | zero => simp only [mpow, pow_zero]; rfl
  | succ n ih =>
      change mulC q (mpow q p n) p = p ^ (n + 1)
      rw [pow_succ, ← ih]; rfl

/-- The clearing step: right-multiply `x` by the inverse power of `p` that kills
`x`'s coordinate at `p`'s pivot depth. Fully computable (no group typeclass). -/
def clearStep (q : ℕ) (p x : Coordinates) : Coordinates :=
  mulC q x (mpow q (invC q p) (coordAt x (pivotDepth p)).val)

theorem clearStep_eq {q : ℕ} (hq : q = 1 ∨ q = 2) (p x : Coordinate q) :
    letI := coordinateGroup q hq
    clearStep q p x = x * p ^ (-(coordAt x (pivotDepth p)).val : ℤ) := by
  letI := coordinateGroup q hq
  change mulC q x (mpow q (invC q p) (coordAt x (pivotDepth p)).val) = _
  rw [mpow_eq_pow hq]
  change x * (p⁻¹) ^ (coordAt x (pivotDepth p)).val = _
  rw [inv_pow, ← zpow_natCast, ← zpow_neg]

/-- The reduction: successively strip the pivots of the generator list. -/
def reduceAux (q : ℕ) : List Coordinates → Coordinates → Coordinates
  | [], x => x
  | p :: rest, x => reduceAux q rest (clearStep q p x)

/-- The membership sift as a `Bool`: `x` reduces to the identity. -/
def siftB (q : ℕ) (gs : List Coordinates) (x : Coordinates) : Bool :=
  decide (reduceAux q gs x = (0, 0, 0, 0, 0))

/-- The subgroup generated by a generator list. -/
def ofList (q : ℕ) (hq : q = 1 ∨ q = 2) (gs : List (Coordinate q)) :
    letI := coordinateGroup q hq; Subgroup (Coordinate q) :=
  letI := coordinateGroup q hq
  Subgroup.closure {x : Coordinate q | x ∈ gs}

/-! ### Well-formedness of an echelon generator list (shallowest first) -/

/-- A generator list is *well formed* if it is an echelonized induced pcgs:
strictly increasing pivots, unit leads, and each generator's `p`-th power and
conjugation stay in the tail it dominates. -/
def WF (q : ℕ) (hq : q = 1 ∨ q = 2) : List (Coordinate q) → Prop
  | [] => True
  | p :: rest =>
      letI := coordinateGroup q hq
      pivotDepth p < 5 ∧
      coordAt p (pivotDepth p) = 1 ∧
      (∀ g ∈ rest, pivotDepth p < pivotDepth g) ∧
      p ^ (5 : ℕ) ∈ ofList q hq rest ∧
      p ∈ Subgroup.normalizer (ofList q hq rest) ∧
      WF q hq rest

/-! ### The head-decomposition lemma -/

section Head
variable {q : ℕ} (hq : q = 1 ∨ q = 2)

/-- Tail generators dominated by `p` lie in the deeper chief-series member. -/
theorem ofList_le_depthGE (p : Coordinate q) (rest : List (Coordinate q))
    (hrest : ∀ g ∈ rest, pivotDepth p < pivotDepth g) :
    letI := coordinateGroup q hq
    ofList q hq rest ≤ depthGE q hq (pivotDepth p + 1) := by
  letI := coordinateGroup q hq
  apply Subgroup.closure_le _ |>.mpr
  intro g hg i hi
  exact coordAt_of_lt_pivotDepth g i (lt_of_lt_of_le hi (hrest g hg))

/-- **The head-decomposition lemma.** Membership in the subgroup generated by
`p :: rest` reduces to membership in the tail subgroup after one clearing step.
This is the inductive heart of the sift's correctness. -/
theorem mem_head_iff (p : Coordinate q) (rest : List (Coordinate q))
    (hp5 : pivotDepth p < 5)
    (hlead : coordAt p (pivotDepth p) = 1)
    (hrest : ∀ g ∈ rest, pivotDepth p < pivotDepth g)
    (hpow : letI := coordinateGroup q hq; p ^ (5 : ℕ) ∈ ofList q hq rest)
    (hnorm : letI := coordinateGroup q hq;
      p ∈ Subgroup.normalizer (ofList q hq rest))
    (x : Coordinate q) :
    letI := coordinateGroup q hq
    (x ∈ ofList q hq (p :: rest) ↔ clearStep q p x ∈ ofList q hq rest) := by
  letI := coordinateGroup q hq
  set d := pivotDepth p with hd_def
  set N := ofList q hq rest with hN_def
  have hpmem : p ∈ depthGE q hq d := self_mem_depthGE_pivotDepth hq p
  have hNle : N ≤ depthGE q hq (d + 1) := ofList_le_depthGE hq p rest hrest
  set K := Subgroup.closure ({p} : Set (Coordinate q)) with hK_def
  have hKnorm : K ≤ Subgroup.normalizer N := by
    rw [hK_def]; exact (Subgroup.closure_le _).mpr (by
      intro y hy; rw [Set.mem_singleton_iff] at hy; subst hy; exact hnorm)
  have hH : ofList q hq (p :: rest) = K ⊔ N := by
    rw [ofList, hK_def, hN_def, ofList,
      show {x : Coordinate q | x ∈ p :: rest} = insert p {x | x ∈ rest} by
        ext y; simp [List.mem_cons],
      Set.insert_eq, Subgroup.closure_union]
  have hcarrier : (↑(ofList q hq (p :: rest)) : Set (Coordinate q))
      = (K : Set (Coordinate q)) * (N : Set (Coordinate q)) := by
    rw [hH]; exact Subgroup.coe_mul_of_left_le_normalizer_right K N hKnorm
  have hpow_dvd : ∀ j : ℤ, (5 : ℤ) ∣ j → p ^ j ∈ N := by
    intro j hj; obtain ⟨k, rfl⟩ := hj
    rw [zpow_mul, show (5 : ℤ) = ((5 : ℕ) : ℤ) from rfl, zpow_natCast]
    exact Subgroup.zpow_mem N hpow k
  have hcoordPow : ∀ i : ℤ, coordAt (p ^ i) d = i • (1 : Fin 5) := by
    intro i; rw [coordAt_zpow hq d hp5 p hpmem i, hlead]
  -- (c) an element of `H` with vanishing pivot coordinate lies in `N`.
  have hc : ∀ y ∈ ofList q hq (p :: rest), coordAt y d = 0 → y ∈ N := by
    intro y hy hy0
    rw [← SetLike.mem_coe, hcarrier] at hy
    obtain ⟨a, ha, n, hn, rfl⟩ := hy
    obtain ⟨j, rfl⟩ := Subgroup.mem_closure_singleton.mp ha
    have hnmem : coordAt n d = 0 := (hNle hn) d (Nat.lt_succ_self d)
    have hco : coordAt (p ^ j * n) d = j • (1 : Fin 5) := by
      rw [coordAt_mul_right q d hp5 (p ^ j) n
            (fun m hm => (hNle hn) m (Nat.lt_succ_of_lt hm)),
        hcoordPow j, hnmem, add_zero]
    have hj0 : j • (1 : Fin 5) = 0 := hco.symm.trans hy0
    have hdvd : (5 : ℤ) ∣ j := by
      have := dvd_of_zsmul_one j 0 hj0
      simpa using this
    exact Subgroup.mul_mem N (hpow_dvd j hdvd) hn
  have hpH : p ∈ ofList q hq (p :: rest) :=
    Subgroup.subset_closure (by simp [List.mem_cons])
  constructor
  · intro hx
    rw [clearStep_eq hq p x]
    apply hc
    · exact Subgroup.mul_mem _ hx (Subgroup.zpow_mem _ hpH (-(coordAt x d).val : ℤ))
    · rw [coordAt_mul_right q d hp5 x (p ^ (-(coordAt x d).val : ℤ))
            (fun m hm => Subgroup.zpow_mem _ hpmem (-(coordAt x d).val : ℤ) m hm),
        hcoordPow (-(coordAt x d).val : ℤ), neg_zsmul, zsmul_one_fin5, add_neg_cancel]
  · intro hcl
    rw [clearStep_eq hq p x] at hcl
    have hxrw : x = (x * p ^ (-(coordAt x d).val : ℤ)) * p ^ ((coordAt x d).val : ℤ) := by
      rw [mul_assoc, ← zpow_add]; simp
    rw [hxrw, hH]
    exact Subgroup.mul_mem _ (Subgroup.mem_sup_right hcl)
      (Subgroup.mem_sup_left (Subgroup.zpow_mem _
        (Subgroup.subset_closure (Set.mem_singleton p)) ((coordAt x d).val : ℤ)))

end Head

/-! ## The sift is correct -/

/-- **Sift correctness.** For a well-formed echelon generator list, the sift
decides membership in the generated subgroup. -/
theorem sift_mem_iff {q : ℕ} (hq : q = 1 ∨ q = 2) :
    ∀ (gs : List (Coordinate q)), WF q hq gs → ∀ (x : Coordinate q),
      letI := coordinateGroup q hq
      (siftB q gs x = true ↔ x ∈ ofList q hq gs) := by
  letI := coordinateGroup q hq
  intro gs
  induction gs with
  | nil =>
      intro _ x
      simp only [siftB, reduceAux, decide_eq_true_eq]
      rw [ofList, show {y : Coordinate q | y ∈ ([] : List (Coordinate q))} = ∅ by ext y; simp,
        Subgroup.closure_empty, Subgroup.mem_bot]
      exact ⟨fun h => h, fun h => h⟩
  | cons p rest ih =>
      intro hwf x
      obtain ⟨hp5, hlead, hrest, hpow, hnorm, hwfrest⟩ := hwf
      change (siftB q rest (clearStep q p x) = true ↔ x ∈ ofList q hq (p :: rest))
      rw [ih hwfrest (clearStep q p x)]
      exact (mem_head_iff hq p rest hp5 hlead hrest hpow hnorm x).symm

/-! ## Cardinality of the generated subgroup -/

section Card
variable {q : ℕ} (hq : q = 1 ∨ q = 2)

/-- One step of the order recursion: adding a dominating generator multiplies
the order by `5`. -/
theorem card_ofList_cons (p : Coordinate q) (rest : List (Coordinate q))
    (hp5 : pivotDepth p < 5)
    (hlead : coordAt p (pivotDepth p) = 1)
    (hrest : ∀ g ∈ rest, pivotDepth p < pivotDepth g)
    (hpow : letI := coordinateGroup q hq; p ^ (5 : ℕ) ∈ ofList q hq rest)
    (hnorm : letI := coordinateGroup q hq;
      p ∈ Subgroup.normalizer (ofList q hq rest)) :
    letI := coordinateGroup q hq
    Nat.card (ofList q hq (p :: rest)) = 5 * Nat.card (ofList q hq rest) := by
  letI := coordinateGroup q hq
  set d := pivotDepth p with hd_def
  set N := ofList q hq rest with hN_def
  have hpmem : p ∈ depthGE q hq d := self_mem_depthGE_pivotDepth hq p
  have hNle : N ≤ depthGE q hq (d + 1) := ofList_le_depthGE hq p rest hrest
  set K := Subgroup.closure ({p} : Set (Coordinate q)) with hK_def
  have hKnorm : K ≤ Subgroup.normalizer N := by
    rw [hK_def]; exact (Subgroup.closure_le _).mpr (by
      intro y hy; rw [Set.mem_singleton_iff] at hy; subst hy; exact hnorm)
  have hH : ofList q hq (p :: rest) = K ⊔ N := by
    rw [ofList, hK_def, hN_def, ofList,
      show {x : Coordinate q | x ∈ p :: rest} = insert p {x | x ∈ rest} by
        ext y; simp [List.mem_cons],
      Set.insert_eq, Subgroup.closure_union]
  have hcarrier : (↑(ofList q hq (p :: rest)) : Set (Coordinate q))
      = (K : Set (Coordinate q)) * (N : Set (Coordinate q)) := by
    rw [hH]; exact Subgroup.coe_mul_of_left_le_normalizer_right K N hKnorm
  have hpH : p ∈ ofList q hq (p :: rest) :=
    Subgroup.subset_closure (by simp [List.mem_cons])
  have hNH : N ≤ ofList q hq (p :: rest) := by rw [hH]; exact le_sup_right
  have hpow_dvd : ∀ j : ℤ, (5 : ℤ) ∣ j → p ^ j ∈ N := by
    intro j hj; obtain ⟨k, rfl⟩ := hj
    rw [zpow_mul, show (5 : ℤ) = ((5 : ℕ) : ℤ) from rfl, zpow_natCast]
    exact Subgroup.zpow_mem N hpow k
  have hcoordPow : ∀ i : ℤ, coordAt (p ^ i) d = i • (1 : Fin 5) := by
    intro i; rw [coordAt_zpow hq d hp5 p hpmem i, hlead]
  -- lead coordinate of a natural power
  have hcoordNat : ∀ (e : Fin 5) (n : Coordinate q), n ∈ N →
      coordAt (p ^ (e.val) * n) d = e := by
    intro e n hn
    rw [coordAt_mul_right q d hp5 (p ^ e.val) n
          (fun m hm => (hNle hn) m (Nat.lt_succ_of_lt hm)),
      ← zpow_natCast, hcoordPow (e.val : ℤ), (hNle hn) d (Nat.lt_succ_self d),
      add_zero, zsmul_one_fin5]
  -- the exponent-vector bijection
  let f : Fin 5 × N → ofList q hq (p :: rest) :=
    fun en => ⟨p ^ (en.1.val) * (en.2 : Coordinate q),
      Subgroup.mul_mem _ (pow_mem hpH _) (hNH en.2.2)⟩
  have hf : Function.Bijective f := by
    constructor
    · rintro ⟨e, n⟩ ⟨e', n'⟩ hEq
      have hEqv : p ^ (e.val) * (n : Coordinate q) = p ^ (e'.val) * (n' : Coordinate q) :=
        congrArg Subtype.val hEq
      have he : e = e' := by
        have h1 := hcoordNat e n n.2
        have h2 := hcoordNat e' n' n'.2
        rw [hEqv] at h1; rw [h1] at h2; exact h2
      subst he
      have hn : (n : Coordinate q) = (n' : Coordinate q) := by
        have := hEqv; rwa [mul_right_inj] at this
      exact Prod.ext rfl (Subtype.ext hn)
    · rintro ⟨y, hy⟩
      rw [← SetLike.mem_coe, hcarrier] at hy
      obtain ⟨a, ha, m, hm, rfl⟩ := hy
      obtain ⟨j, rfl⟩ := Subgroup.mem_closure_singleton.mp ha
      refine ⟨(⟨(j % 5).toNat, ?_⟩, ⟨p ^ (5 * (j / 5)) * m, ?_⟩), ?_⟩
      · have : j % 5 < 5 := Int.emod_lt_of_pos j (by norm_num)
        omega
      · exact Subgroup.mul_mem _ (hpow_dvd _ ⟨j / 5, rfl⟩) hm
      · apply Subtype.ext
        change p ^ ((j % 5).toNat) * (p ^ (5 * (j / 5)) * m) = p ^ j * m
        rw [← mul_assoc, ← zpow_natCast p ((j % 5).toNat),
          Int.toNat_of_nonneg (Int.emod_nonneg j (by norm_num)), ← zpow_add,
          show (j % 5) + 5 * (j / 5) = j from by omega]
  calc Nat.card (ofList q hq (p :: rest))
      = Nat.card (Fin 5 × N) := (Nat.card_congr (Equiv.ofBijective f hf)).symm
    _ = 5 * Nat.card N := by rw [Nat.card_prod, Nat.card_eq_fintype_card, Fintype.card_fin]

end Card

/-- **Order of the generated subgroup.** A well-formed echelon list of length `m`
generates a subgroup of order `5 ^ m`. -/
theorem card_ofList {q : ℕ} (hq : q = 1 ∨ q = 2) :
    ∀ (gs : List (Coordinate q)), WF q hq gs →
      letI := coordinateGroup q hq
      Nat.card (ofList q hq gs) = 5 ^ gs.length := by
  letI := coordinateGroup q hq
  intro gs
  induction gs with
  | nil =>
      intro _
      rw [ofList, show {y : Coordinate q | y ∈ ([] : List (Coordinate q))} = ∅ by ext y; simp,
        Subgroup.closure_empty]
      simp
  | cons p rest ih =>
      intro hwf
      obtain ⟨hp5, hlead, hrest, hpow, hnorm, hwfrest⟩ := hwf
      rw [card_ofList_cons hq p rest hp5 hlead hrest hpow hnorm, ih hwfrest]
      rw [List.length_cons, pow_succ]
      ring

/-! ## `reduceAux` is a canonical left-coset transversal -/

/-- **`reduceAux` is constant on left cosets of the generated subgroup.** For a
well-formed echelon list `gs`, right-multiplying `x` by any `m ∈ ⟨gs⟩` leaves the
reduced normal form unchanged: `reduceAux gs (x * m) = reduceAux gs x`. Since
`reduceAux gs x ∈ x · ⟨gs⟩`, this makes `reduceAux gs` a canonical transversal of
the left cosets `x · ⟨gs⟩`, hence a decider of coset equality. -/
theorem reduceAux_mul_mem {q : ℕ} (hq : q = 1 ∨ q = 2) :
    ∀ (gs : List (Coordinate q)), WF q hq gs →
      letI := coordinateGroup q hq
      ∀ (x m : Coordinate q), m ∈ ofList q hq gs →
        reduceAux q gs (x * m) = reduceAux q gs x := by
  letI := coordinateGroup q hq
  intro gs
  induction gs with
  | nil =>
      intro _ x m hm
      rw [ofList, show {y : Coordinate q | y ∈ ([] : List (Coordinate q))} = ∅ by ext y; simp,
        Subgroup.closure_empty, Subgroup.mem_bot] at hm
      subst hm
      rw [mul_one]
  | cons p rest ih =>
      intro hwf x m hm
      obtain ⟨hp5, hlead, hrest, hpow, hnorm, hwfrest⟩ := hwf
      -- decompose `m = p ^ j * n` with `n ∈ N := ⟨rest⟩`
      set N := ofList q hq rest with hN_def
      have hpmemp : p ∈ depthGE q hq (pivotDepth p) := self_mem_depthGE_pivotDepth hq p
      have hNle : N ≤ depthGE q hq (pivotDepth p + 1) := ofList_le_depthGE hq p rest hrest
      set K := Subgroup.closure ({p} : Set (Coordinate q)) with hK_def
      have hKnorm : K ≤ Subgroup.normalizer N := by
        rw [hK_def]; exact (Subgroup.closure_le _).mpr (by
          intro y hy; rw [Set.mem_singleton_iff] at hy; subst hy; exact hnorm)
      have hH : ofList q hq (p :: rest) = K ⊔ N := by
        rw [ofList, hK_def, hN_def, ofList,
          show {y : Coordinate q | y ∈ p :: rest} = insert p {y | y ∈ rest} by
            ext y; simp [List.mem_cons],
          Set.insert_eq, Subgroup.closure_union]
      have hcarrier : (↑(ofList q hq (p :: rest)) : Set (Coordinate q))
          = (K : Set (Coordinate q)) * (N : Set (Coordinate q)) := by
        rw [hH]; exact Subgroup.coe_mul_of_left_le_normalizer_right K N hKnorm
      have hpow_dvd : ∀ i : ℤ, (5 : ℤ) ∣ i → p ^ i ∈ N := by
        intro i hi; obtain ⟨k, rfl⟩ := hi
        rw [zpow_mul, show (5 : ℤ) = ((5 : ℕ) : ℤ) from rfl, zpow_natCast]
        exact Subgroup.zpow_mem N hpow k
      rw [← SetLike.mem_coe, hcarrier] at hm
      obtain ⟨a, ha, n, hn, rfl⟩ := hm
      obtain ⟨j, rfl⟩ := Subgroup.mem_closure_singleton.mp ha
      have hn_below : ∀ i, i < pivotDepth p + 1 → coordAt n i = 0 :=
        (mem_depthGE hq _ n).mp (hNle hn)
      have hpjn_below : ∀ i, i < pivotDepth p → coordAt (p ^ j * n) i = 0 := by
        have : (p ^ j * n) ∈ depthGE q hq (pivotDepth p) :=
          Subgroup.mul_mem _ (Subgroup.zpow_mem _ hpmemp j)
            (fun i hi => hn_below i (Nat.lt_succ_of_lt hi))
        exact (mem_depthGE hq _ (p ^ j * n)).mp this
      -- one clear-step on each side
      change reduceAux q rest (clearStep q p (x * (p ^ j * n)))
         = reduceAux q rest (clearStep q p x)
      rw [clearStep_eq hq p (x * (p ^ j * n)), clearStep_eq hq p x]
      set d := pivotDepth p with hd_def
      set A : ℤ := ((coordAt x d).val : ℤ) with hA_def
      set B : ℤ := ((coordAt (x * (p ^ j * n)) d).val : ℤ) with hB_def
      -- the lead coordinate of the shifted element
      have hcoordB : coordAt (x * (p ^ j * n)) d = coordAt x d + j • (1 : Fin 5) := by
        rw [coordAt_mul_right q d hp5 x (p ^ j * n) hpjn_below,
          coordAt_mul_right q d hp5 (p ^ j) n (fun i hi => hn_below i (Nat.lt_succ_of_lt hi)),
          coordAt_zpow hq d hp5 p hpmemp j, hlead, hn_below d (Nat.lt_succ_self d), add_zero]
      -- the residual `p^(A+j) n p^(-B)` lies in `N`
      have hdvd : (5 : ℤ) ∣ (A + j - B) := by
        have h0 : (A + j - B) • (1 : Fin 5) = ((0 : Fin 5).val : ℤ) • (1 : Fin 5) := by
          have e1 : A • (1 : Fin 5) = coordAt x d := by rw [hA_def, zsmul_one_fin5]
          have e2 : B • (1 : Fin 5) = coordAt (x * (p ^ j * n)) d := by rw [hB_def, zsmul_one_fin5]
          rw [sub_zsmul, add_zsmul, e1, e2, hcoordB]; simp
        have := dvd_of_zsmul_one (A + j - B) 0 (by simpa using h0)
        simpa using this
      have hmem' : p ^ (A + j) * n * p ^ (-B) ∈ N := by
        have h1 : p ^ (A + j) * n * (p ^ (A + j))⁻¹ ∈ N :=
          (Subgroup.mem_normalizer_iff.mp (Subgroup.zpow_mem _ hnorm (A + j)) n).mp hn
        have hrw : p ^ (A + j) * n * p ^ (-B)
            = (p ^ (A + j) * n * (p ^ (A + j))⁻¹) * p ^ (A + j - B) := by group
        rw [hrw]; exact Subgroup.mul_mem _ h1 (hpow_dvd _ hdvd)
      -- rewrite the left argument and finish by the tail IH
      have harg : x * (p ^ j * n) * p ^ (-B) = (x * p ^ (-A)) * (p ^ (A + j) * n * p ^ (-B)) := by
        group
      rw [harg]
      exact ih hwfrest (x * p ^ (-A)) _ hmem'

/-! ## Decidable well-formedness -/

/-- An element normalizes the closure of `S` as soon as it conjugates every
member of `S` back into the closure. -/
theorem normalizes_closure {q : ℕ} (hq : q = 1 ∨ q = 2) (p : Coordinate q)
    (S : Set (Coordinate q))
    (h1 : letI := coordinateGroup q hq; ∀ g ∈ S, p * g * p⁻¹ ∈ Subgroup.closure S)
    (h2 : letI := coordinateGroup q hq; ∀ g ∈ S, p⁻¹ * g * p ∈ Subgroup.closure S) :
    letI := coordinateGroup q hq
    p ∈ Subgroup.normalizer (Subgroup.closure S) := by
  letI := coordinateGroup q hq
  have A : ∀ x ∈ Subgroup.closure S, p * x * p⁻¹ ∈ Subgroup.closure S := by
    intro x hx
    induction hx using Subgroup.closure_induction with
    | mem y hy => exact h1 y hy
    | one => simp only [mul_one, mul_inv_cancel]; exact Subgroup.one_mem _
    | mul a b _ _ ha hb =>
        rw [show p * (a * b) * p⁻¹ = (p * a * p⁻¹) * (p * b * p⁻¹) by group]
        exact Subgroup.mul_mem _ ha hb
    | inv a _ ha =>
        rw [show p * a⁻¹ * p⁻¹ = (p * a * p⁻¹)⁻¹ by group]
        exact Subgroup.inv_mem _ ha
  have B : ∀ x ∈ Subgroup.closure S, p⁻¹ * x * p ∈ Subgroup.closure S := by
    intro x hx
    induction hx using Subgroup.closure_induction with
    | mem y hy => exact h2 y hy
    | one => simp only [mul_one, inv_mul_cancel]; exact Subgroup.one_mem _
    | mul a b _ _ ha hb =>
        rw [show p⁻¹ * (a * b) * p = (p⁻¹ * a * p) * (p⁻¹ * b * p) by group]
        exact Subgroup.mul_mem _ ha hb
    | inv a _ ha =>
        rw [show p⁻¹ * a⁻¹ * p = (p⁻¹ * a * p)⁻¹ by group]
        exact Subgroup.inv_mem _ ha
  rw [Subgroup.mem_normalizer_iff]
  intro y
  refine ⟨fun hy => A y hy, fun hy => ?_⟩
  have hB := B _ hy
  rwa [show p⁻¹ * (p * y * p⁻¹) * p = y by group] at hB

/-- Computable conjugation `a * g * a⁻¹`. -/
def conjC (q : ℕ) (a g : Coordinates) : Coordinates := mulC q (mulC q a g) (invC q a)

theorem conjC_eq {q : ℕ} (hq : q = 1 ∨ q = 2) (a g : Coordinate q) :
    letI := coordinateGroup q hq
    (conjC q a g : Coordinate q) = a * g * a⁻¹ := rfl

/-- Decidable well-formedness test (the kernel-checkable `Cgs` invariant). -/
def wfB (q : ℕ) : List Coordinates → Bool
  | [] => true
  | p :: rest =>
      decide (pivotDepth p < 5) &&
      decide (coordAt p (pivotDepth p) = 1) &&
      decide (∀ g ∈ rest, pivotDepth p < pivotDepth g) &&
      siftB q rest (mpow q p 5) &&
      rest.all (fun g => siftB q rest (conjC q p g) && siftB q rest (conjC q (invC q p) g)) &&
      wfB q rest

/-- The decidable test entails the semantic well-formedness predicate. -/
theorem wf_of_wfB {q : ℕ} (hq : q = 1 ∨ q = 2) :
    ∀ gs : List (Coordinate q), wfB q gs = true → WF q hq gs := by
  letI := coordinateGroup q hq
  intro gs
  induction gs with
  | nil => intro _; trivial
  | cons p rest ih =>
      intro h
      simp only [wfB, Bool.and_eq_true, decide_eq_true_eq, List.all_eq_true] at h
      obtain ⟨⟨⟨⟨⟨hp5, hlead⟩, hrest⟩, hpow⟩, hconj⟩, hrestB⟩ := h
      have hwfrest : WF q hq rest := ih hrestB
      refine ⟨hp5, hlead, hrest, ?_, ?_, hwfrest⟩
      · have hm := (sift_mem_iff hq rest hwfrest (mpow q p 5)).mp hpow
        rwa [mpow_eq_pow hq p 5] at hm
      · apply normalizes_closure hq p {x : Coordinate q | x ∈ rest}
        · intro g hg
          have hgr : g ∈ rest := hg
          have := (sift_mem_iff hq rest hwfrest (conjC q p g)).mp (hconj g hgr).1
          rwa [conjC_eq hq p g] at this
        · intro g hg
          have hgr : g ∈ rest := hg
          have := (sift_mem_iff hq rest hwfrest (conjC q (invC q p) g)).mp (hconj g hgr).2
          rw [conjC_eq hq (invC q p) g] at this
          simpa only [ofList, show invC q p = p⁻¹ from rfl, inv_inv] using this

/-! ### Pure-`Bool` well-formedness `wfB'` and its soundness bridge

`wfB` is correct but its pivot/lead/increasing conjuncts are `decide`-of-`Prop`,
which the kernel reduces through the `Decidable`-instance tower (`Nat.decLt`,
`Fin.decEq`, `List.decidableBAll`) *off* the accelerated `Nat`-literal path, and
so far more slowly than the pure-`Bool` primitives `Nat.blt`/`Nat.beq`/`Nat.ble`.
`wfB'` swaps exactly those three conjuncts for their `Bool` equivalents, keeping
the (already cheap) sift conjuncts verbatim, and `wfB'_eq_wfB` proves the two
agree pointwise — so every well-formedness obligation can be discharged with the
fast `wfB'`. -/

/-- Generic `Bool = decide` bridge from a `= true` characterization. -/
theorem bool_eq_decide {b : Bool} {P : Prop} [Decidable P] (h : b = true ↔ P) :
    b = decide P := by
  have h' : (b = true) ↔ (decide P = true) := by rw [decide_eq_true_eq]; exact h
  cases hb : b <;> cases hd : decide P <;> simp only [hb, hd] at h' ⊢ <;> simp_all

/-- Pure-`Bool` strictly-increasing-pivot check. -/
def incrB (p : Coordinates) (rest : List Coordinates) : Bool :=
  rest.all (fun g => Nat.ble (pivotDepth p + 1) (pivotDepth g))

theorem incrB_iff (p : Coordinates) (rest : List Coordinates) :
    incrB p rest = true ↔ ∀ g ∈ rest, pivotDepth p < pivotDepth g := by
  simp only [incrB, List.all_eq_true, Nat.ble_eq, Nat.add_one_le_iff]

/-- `wfB` with the pivot/lead/increasing conjuncts reformulated as pure `Bool`. -/
def wfB' (q : ℕ) : List Coordinates → Bool
  | [] => true
  | p :: rest =>
      Nat.blt (pivotDepth p) 5 &&
      Nat.beq (coordAt p (pivotDepth p)).val 1 &&
      incrB p rest &&
      siftB q rest (mpow q p 5) &&
      rest.all (fun g => siftB q rest (conjC q p g) && siftB q rest (conjC q (invC q p) g)) &&
      wfB' q rest

/-- The pure-`Bool` `wfB'` agrees with `wfB` on every list, so a `wfB'` check
suffices to build a `Cgs`. -/
theorem wfB'_eq_wfB (q : ℕ) : ∀ gs : List Coordinates, wfB' q gs = wfB q gs
  | [] => rfl
  | p :: rest => by
      have hA : Nat.blt (pivotDepth p) 5 = decide (pivotDepth p < 5) :=
        bool_eq_decide (by rw [Nat.blt_eq])
      have hB : Nat.beq (coordAt p (pivotDepth p)).val 1
          = decide (coordAt p (pivotDepth p) = 1) :=
        bool_eq_decide (by
          constructor
          · intro h; apply Fin.ext; simpa using Nat.eq_of_beq_eq_true h
          · intro h; rw [h]; rfl)
      have hC : incrB p rest
          = decide (∀ g ∈ rest, pivotDepth p < pivotDepth g) :=
        bool_eq_decide (incrB_iff p rest)
      simp only [wfB', wfB, hA, hB, hC, wfB'_eq_wfB q rest]

/-- One-directional bridge: a positive `wfB'` yields the semantic predicate `WF`
(hence lets us build `Cgs` values through the kernel-checked `wfB`). -/
theorem wf_of_wfB' {q : ℕ} (hq : q = 1 ∨ q = 2) (gs : List (Coordinate q)) :
    wfB' q gs = true → WF q hq gs :=
  fun h => wf_of_wfB hq gs (by rw [← wfB'_eq_wfB]; exact h)

/-! ## The `Cgs` type and its headline API -/

/-- A canonical(-shape) generating sequence: an echelonized, well-formed
generator list against the pc chief series. Well-formedness is a kernel-checkable
`Bool`, so `Cgs` values can be produced by `decide`. -/
structure Cgs (q : ℕ) (hq : q = 1 ∨ q = 2) where
  gens : List (Coordinate q)
  wf : wfB q gens = true

namespace Cgs

variable {q : ℕ} {hq : q = 1 ∨ q = 2}

theorem isWF (c : Cgs q hq) : WF q hq c.gens := wf_of_wfB hq c.gens c.wf

/-- The subgroup presented by a `Cgs`. -/
def toSubgroup (c : Cgs q hq) : letI := coordinateGroup q hq; Subgroup (Coordinate q) :=
  ofList q hq c.gens

/-- The membership sift. -/
def sift (c : Cgs q hq) (x : Coordinate q) : Bool := siftB q c.gens x

/-- **Sift correctness for `Cgs`.** -/
theorem sift_mem_iff (c : Cgs q hq) (x : Coordinate q) :
    letI := coordinateGroup q hq
    (c.sift x = true ↔ x ∈ c.toSubgroup) :=
  LeanDring.P5Presentation.sift_mem_iff hq c.gens c.isWF x

/-- **Order of a `Cgs` subgroup.** -/
theorem card_toSubgroup (c : Cgs q hq) :
    letI := coordinateGroup q hq
    Nat.card c.toSubgroup = 5 ^ c.gens.length :=
  card_ofList hq c.gens c.isWF

/-- Decidable subgroup-equality via mutual sifting. -/
def cgsEquiv (c c' : Cgs q hq) : Bool :=
  c'.gens.all (fun g => c.sift g) && c.gens.all (fun g => c'.sift g)

/-- **Mutual-sift decides subgroup equality.** -/
theorem cgsEquiv_iff (c c' : Cgs q hq) :
    letI := coordinateGroup q hq
    (c.cgsEquiv c' = true ↔ c.toSubgroup = c'.toSubgroup) := by
  letI := coordinateGroup q hq
  rw [cgsEquiv, Bool.and_eq_true, List.all_eq_true, List.all_eq_true]
  constructor
  · rintro ⟨h1, h2⟩
    apply le_antisymm
    · refine (Subgroup.closure_le _).mpr ?_
      intro g hg
      exact (c'.sift_mem_iff g).mp (h2 g hg)
    · refine (Subgroup.closure_le _).mpr ?_
      intro g hg
      exact (c.sift_mem_iff g).mp (h1 g hg)
  · intro hEq
    refine ⟨fun g hg => ?_, fun g hg => ?_⟩
    · rw [c.sift_mem_iff g, hEq]
      exact Subgroup.subset_closure hg
    · rw [c'.sift_mem_iff g, ← hEq]
      exact Subgroup.subset_closure hg

end Cgs

/-! ## Kernel smoke tests (small `decide`, no `native_decide`) -/

section Smoke

set_option maxRecDepth 400000

/-- The full group `⊤`: all five standard pc generators (shallowest first). -/
def topCgs : Cgs 1 (Or.inl rfl) :=
  ⟨[(1, 0, 0, 0, 0), (0, 1, 0, 0, 0), (0, 0, 1, 0, 0), (0, 0, 0, 1, 0), (0, 0, 0, 0, 1)],
    by decide⟩

/-- The trivial subgroup `⊥`: the empty generating sequence. -/
def botCgs : Cgs 1 (Or.inl rfl) := ⟨[], by decide⟩

/-- The center `⟨g₄⟩`: the depth-4 generator alone (order 5). -/
def centerCgs : Cgs 1 (Or.inl rfl) := ⟨[(0, 0, 0, 0, 1)], by decide⟩

/-- `⟨g₃, g₄⟩` given by its standard echelon sequence. -/
def c34a : Cgs 1 (Or.inl rfl) := ⟨[(0, 0, 0, 1, 0), (0, 0, 0, 0, 1)], by decide⟩

/-- `⟨g₃, g₄⟩` given by a *different* echelon sequence (`g₃g₄` in place of `g₃`). -/
def c34b : Cgs 1 (Or.inl rfl) := ⟨[(0, 0, 0, 1, 1), (0, 0, 0, 0, 1)], by decide⟩

-- Orders, via `card_toSubgroup` (never materialising the carrier as a `Finset`).
example : Nat.card topCgs.toSubgroup = 3125 := by rw [Cgs.card_toSubgroup]; rfl
example : Nat.card botCgs.toSubgroup = 1 := by rw [Cgs.card_toSubgroup]; rfl
example : Nat.card centerCgs.toSubgroup = 5 := by rw [Cgs.card_toSubgroup]; rfl

-- A membership sift: `g₀` sifts to `1` in `⊤`, but not in the center.
example : topCgs.sift (1, 2, 3, 4, 0) = true := by decide
example : centerCgs.sift (1, 0, 0, 0, 0) = false := by decide
example : centerCgs.sift (0, 0, 0, 0, 3) = true := by decide

-- Two different generating sequences for `⟨g₃, g₄⟩` are recognised as equal…
example : c34a.cgsEquiv c34b = true := by decide

-- … and the equality decision really certifies subgroup equality.
example : c34a.toSubgroup = c34b.toSubgroup :=
  (Cgs.cgsEquiv_iff c34a c34b).mp (by decide)

end Smoke

end LeanDring.P5Presentation
