/-
Copyright (c) 2026 Tilemachos Vassias. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tilemachos Vassias (formalization assisted by Claude)
-/
import LeanDring.P5.Certificate.SubgroupInventory.Twin2.FrattiniCert
import Mathlib.GroupTheory.Commutator.Basic
import Mathlib.GroupTheory.QuotientGroup.Finite

/-!
# Frattini step — discharging `FratDischarge` (subgroup inventory, final step)

This file proves the single remaining group-theoretic obligation
`FratDischarge` isolated in `LeanDring/P5/Certificate/SubgroupInventory/Twin2/FrattiniCert.lean`,
and wires the now-unconditional
consequences.
-/

namespace LeanDring.P5Presentation

namespace Q2

open Cgs Subgroup
open scoped commutatorElement

set_option maxRecDepth 100000

/-! ## Certificate fact extraction -/

/-- Well-formedness of the echelon base at an in-range index. -/
theorem wf_getB {i : Nat} (hi : i < 676) : WF 2 hq2 (getB i) := by
  have hmem : getB i ∈ allBases := getD_mem_allBases i hi
  exact wf_of_wfB hq2 _ (allBases_wfB _ hmem)

/-- `subAt i` is the subgroup generated by the base `getB i`. -/
theorem subAt_eq_ofList (i : Nat) : subAt i = ofList 2 hq2 (getB i) := rfl

/-- Sift ↔ membership at an in-range index. -/
theorem siftB_getB_iff {i : Nat} (hi : i < 676) (x : Coordinate 2) :
    siftB 2 (getB i) x = true ↔ x ∈ subAt i :=
  sift_mem_iff hq2 (getB i) (wf_getB hi) x

/-- The certificate facts, at subgroup-membership level. `Φ := subAt fc.phiIdx`. -/
structure CertFacts (h : Nat) (fc : FratCert) : Prop where
  hh : h < 676
  hphi : fc.phiIdx < 676
  hmaxlt : ∀ j ∈ fc.maxIdxs, j < 676
  hwitsfst : List.map Prod.fst fc.wits = getB fc.phiIdx
  hwits : ∀ w ∈ fc.wits, wordValC w.2 = w.1 ∧
    ∀ a ∈ w.2, a.2.2.1 ∈ subAt h ∧ (a.2.1 = true ∨ a.2.2.2 ∈ subAt h)
  hcomm : ∀ a ∈ getB h, ∀ b ∈ getB h, commutatorC a b ∈ subAt fc.phiIdx
  hpow : ∀ a ∈ getB h, mpow 2 a 5 ∈ subAt fc.phiIdx
  hnorm : ∀ g ∈ getB fc.phiIdx, ∀ a ∈ getB h,
    conjC 2 a g ∈ subAt fc.phiIdx ∧ conjC 2 (invC 2 a) g ∈ subAt fc.phiIdx
  hmax : ∀ j ∈ fc.maxIdxs, (∀ g ∈ getB fc.phiIdx, g ∈ subAt j) ∧
    (∀ g ∈ getB j, g ∈ subAt h) ∧ (getB j).length + 1 = (getB h).length
  hnodup : fc.maxIdxs.Nodup
  hcount : fc.maxIdxs.length = (5 ^ ((getB h).length - (getB fc.phiIdx).length) - 1) / 4

/-- Extract the certificate facts from the Boolean checker. -/
theorem certFacts_of_check {h : Nat} {fc : FratCert} (hc : fratCertB h fc = true) :
    CertFacts h fc := by
  simp only [fratCertB, Bool.and_eq_true, List.all_eq_true, decide_eq_true_eq,
    Bool.or_eq_true, Nat.blt_eq, Nat.beq_eq] at hc
  obtain ⟨⟨⟨⟨⟨⟨⟨⟨⟨⟨hh, hphi⟩, hmaxlt⟩, hwitsfst⟩, hwits⟩, hcomm⟩, hpow⟩, hnorm⟩, hmax⟩,
    hnodup⟩, hcount⟩ := hc
  refine ⟨hh, hphi, hmaxlt, hwitsfst, ?_, ?_, ?_, ?_, ?_, hnodup, hcount⟩
  · intro w hw
    obtain ⟨hval, hatoms⟩ := hwits w hw
    refine ⟨hval, fun a ha => ?_⟩
    obtain ⟨h1, h2⟩ := hatoms a ha
    exact ⟨(siftB_getB_iff hh _).mp h1, h2.imp id (siftB_getB_iff hh _).mp⟩
  · intro a ha b hb
    exact (siftB_getB_iff hphi _).mp (hcomm a ha b hb)
  · intro a ha
    exact (siftB_getB_iff hphi _).mp (hpow a ha)
  · intro g hg a ha
    obtain ⟨h1, h2⟩ := hnorm g hg a ha
    exact ⟨(siftB_getB_iff hphi _).mp h1, (siftB_getB_iff hphi _).mp h2⟩
  · intro j hj
    obtain ⟨⟨hg1, hg2⟩, hlen⟩ := hmax j hj
    refine ⟨fun g hg => (siftB_getB_iff (hmaxlt j hj) _).mp (hg1 g hg),
      fun g hg => (siftB_getB_iff hh _).mp (hg2 g hg), hlen⟩

/-! ## Computable-operation bridges to the group operations -/

theorem commutatorC_eq (a b : Coordinate 2) : commutatorC a b = ⁅a, b⁆ := by
  rw [commutatorElement_def]; rfl

theorem mpow5_eq (a : Coordinate 2) : mpow 2 a 5 = a ^ 5 := mpow_eq_pow hq2 a 5

/-- `subAt i` is `Subgroup.closure` of its generator set. -/
theorem subAt_eq_closure (i : Nat) :
    subAt i = Subgroup.closure {x : Coordinate 2 | x ∈ getB i} := rfl

/-! ## The witness lemma: `Φ ≤ M` whenever `[H,H] ≤ M` and `H⁵ ≤ M` -/

/-- The value of a single signed atom, expressed with group operations. -/
theorem atomValC_mem {L : Subgroup (Coordinate 2)} (b p : Bool) (x y : Coordinate 2)
    (hx : x ∈ subAt h) (hxy : p = true ∨ y ∈ subAt h)
    (hcomm : ∀ a ∈ subAt h, ∀ b ∈ subAt h, ⁅a, b⁆ ∈ L)
    (hpow : ∀ a ∈ subAt h, a ^ 5 ∈ L) :
    (atomValC (b, p, x, y) : Coordinate 2) ∈ L := by
  have hv : ((if p then mpow 2 x 5 else commutatorC x y : Coordinates) : Coordinate 2) ∈ L := by
    cases p with
    | true => change (mpow 2 x 5 : Coordinate 2) ∈ L; rw [mpow5_eq]; exact hpow x hx
    | false =>
        change (commutatorC x y : Coordinate 2) ∈ L
        rw [commutatorC_eq]
        exact hcomm x hx y (hxy.resolve_left (by simp))
  cases b with
  | true => exact L.inv_mem hv
  | false => exact hv

/-- Membership of a left-fold product in a subgroup. -/
theorem foldl_atomValC_mem {L : Subgroup (Coordinate 2)} (l : FratWord) (acc : Coordinate 2)
    (hacc : acc ∈ L) (hall : ∀ a ∈ l, (atomValC a : Coordinate 2) ∈ L) :
    (List.foldl (fun acc a => mulC 2 acc (atomValC a)) acc l : Coordinate 2) ∈ L := by
  induction l generalizing acc with
  | nil => exact hacc
  | cons b t ih =>
      apply ih
      · exact L.mul_mem hacc (hall b (List.mem_cons.mpr (Or.inl rfl)))
      · exact fun a ha => hall a (List.mem_cons.mpr (Or.inr ha))

/-- If a subgroup `L` contains every commutator and every `5`th power of elements
of `H = subAt h`, then it contains `Φ = subAt fc.phiIdx`. Uses only the witness
data (i): the `Φ`-generators are products of such atoms with `a,b ∈ H`. -/
theorem phi_le_of_comm_pow {h : Nat} {fc : FratCert} (cf : CertFacts h fc)
    (L : Subgroup (Coordinate 2))
    (hcomm : ∀ a ∈ subAt h, ∀ b ∈ subAt h, ⁅a, b⁆ ∈ L)
    (hpow : ∀ a ∈ subAt h, a ^ 5 ∈ L) :
    subAt fc.phiIdx ≤ L := by
  -- each atom value lands in `L`
  have hatom : ∀ w ∈ fc.wits, ∀ a ∈ w.2, (atomValC a : Coordinate 2) ∈ L := by
    intro w hw a ha
    obtain ⟨_, hmem⟩ := cf.hwits w hw
    obtain ⟨ha1, ha2⟩ := hmem a ha
    obtain ⟨b, p, x, y⟩ := a
    exact atomValC_mem (h := h) b p x y ha1 ha2 hcomm hpow
  -- each witness word folds into `L`
  have hword : ∀ w ∈ fc.wits, (wordValC w.2 : Coordinate 2) ∈ L :=
    fun w hw => foldl_atomValC_mem w.2 (0, 0, 0, 0, 0) L.one_mem (hatom w hw)
  -- generators of `Φ` are the witness words' values
  rw [subAt_eq_closure, Subgroup.closure_le]
  intro g hg
  rw [Set.mem_setOf_eq, ← cf.hwitsfst] at hg
  obtain ⟨w, hw, hwg⟩ := List.exists_of_mem_map hg
  obtain ⟨hval, _⟩ := cf.hwits w hw
  rw [SetLike.mem_coe, ← hwg, ← hval]
  exact hword w hw

/-! ## Commutators of generators + normal target ⟹ derived subgroup inside -/

/-- **The generator-to-derived-subgroup lemma.** If `Φ` is normalized by
`closure S` and the commutators of elements of the generating set `S` lie in `Φ`,
then *all* commutators of elements of `closure S` lie in `Φ`. -/
theorem commutator_gens_mem {G : Type*} [_root_.Group G] {S : Set G} {Φ : Subgroup G}
    (hnormlz : ∀ z ∈ Subgroup.closure S, ∀ g ∈ Φ, z * g * z⁻¹ ∈ Φ)
    (hcomm : ∀ a ∈ S, ∀ b ∈ S, ⁅a, b⁆ ∈ Φ) :
    ∀ x ∈ Subgroup.closure S, ∀ y ∈ Subgroup.closure S, ⁅x, y⁆ ∈ Φ := by
  -- Lemma A: fix a generator `a`, induct on `y`.
  have hA : ∀ a ∈ S, ∀ y ∈ Subgroup.closure S, ⁅a, y⁆ ∈ Φ := by
    intro a ha y hy
    induction hy using Subgroup.closure_induction with
    | mem b hb => exact hcomm a ha b hb
    | one => rw [commutatorElement_one_right]; exact Φ.one_mem
    | mul y1 y2 hy1 _ ih1 ih2 =>
        have hid : ⁅a, y1 * y2⁆ = ⁅a, y1⁆ * (y1 * ⁅a, y2⁆ * y1⁻¹) := by
          simp only [commutatorElement_def]; group
        rw [hid]
        exact Φ.mul_mem ih1 (hnormlz y1 hy1 _ ih2)
    | inv y1 hy1 ih1 =>
        have hid : ⁅a, y1⁻¹⁆ = y1⁻¹ * ⁅a, y1⁆⁻¹ * (y1⁻¹)⁻¹ := by
          simp only [commutatorElement_def]; group
        rw [hid]
        exact hnormlz _ (Subgroup.inv_mem _ hy1) _ (Φ.inv_mem ih1)
  -- Lemma B: induct on `x`.
  intro x hx
  induction hx using Subgroup.closure_induction with
  | mem a ha => exact hA a ha
  | one => intro y _; rw [commutatorElement_one_left]; exact Φ.one_mem
  | mul x1 x2 hx1 _ ih1 ih2 =>
      intro y hy
      have hid : ⁅x1 * x2, y⁆ = x1 * ⁅x2, y⁆ * x1⁻¹ * ⁅x1, y⁆ := by
        simp only [commutatorElement_def]; group
      rw [hid]
      exact Φ.mul_mem (hnormlz x1 hx1 _ (ih2 y hy)) (ih1 y hy)
  | inv x1 hx1 ih1 =>
      intro y hy
      have hid : ⁅x1⁻¹, y⁆ = x1⁻¹ * ⁅x1, y⁆⁻¹ * (x1⁻¹)⁻¹ := by
        simp only [commutatorElement_def]; group
      rw [hid]
      exact hnormlz _ (Subgroup.inv_mem _ hx1) _ (Φ.inv_mem (ih1 y hy))

/-! ## `H` normalizes `Φ`, and `[H,H] ≤ Φ` -/

/-- Each generator of `H` normalizes `Φ`, hence `H ≤ normalizer Φ`. -/
theorem H_le_normalizer {h : Nat} {fc : FratCert} (cf : CertFacts h fc) :
    subAt h ≤ Subgroup.normalizer (subAt fc.phiIdx) := by
  rw [subAt_eq_closure]
  refine (Subgroup.closure_le _).mpr ?_
  intro p hp
  apply normalizes_closure hq2 p {x : Coordinate 2 | x ∈ getB fc.phiIdx}
  · intro g hg
    have := (cf.hnorm g hg p hp).1
    rwa [conjC_eq hq2 p g] at this
  · intro g hg
    have h2 := (cf.hnorm g hg p hp).2
    rw [conjC_eq hq2 (invC 2 p) g, show invC 2 p = p⁻¹ from rfl, inv_inv] at h2
    exact h2

/-- Conjugation-stability of `Φ` by elements of `H`. -/
theorem conj_mem {h : Nat} {fc : FratCert} (cf : CertFacts h fc) :
    ∀ z ∈ subAt h, ∀ g ∈ subAt fc.phiIdx, z * g * z⁻¹ ∈ subAt fc.phiIdx := by
  intro z hz g hg
  exact (Subgroup.mem_normalizer_iff.mp (H_le_normalizer cf hz) g).mp hg

/-- **`[H,H] ≤ Φ`.** All commutators of `H`-elements lie in `Φ`. -/
theorem HH_comm_mem {h : Nat} {fc : FratCert} (cf : CertFacts h fc) :
    ∀ x ∈ subAt h, ∀ y ∈ subAt h, ⁅x, y⁆ ∈ subAt fc.phiIdx :=
  commutator_gens_mem (S := {x : Coordinate 2 | x ∈ getB h}) (conj_mem cf)
    (fun a ha b hb => by rw [← commutatorC_eq]; exact cf.hcomm a ha b hb)

/-! ## Cardinalities and translation between `↥H`-level and ambient facts -/

/-- Order of `subAt i` for an in-range index. -/
theorem card_subAt {i : Nat} (hi : i < 676) :
    Nat.card (subAt i) = 5 ^ (getB i).length :=
  card_ofList hq2 (getB i) (wf_getB hi)

/-- Coercion of a subtype commutator to the ambient commutator. -/
theorem coe_commutatorElement_subAt {h : Nat} (a b : ↥(subAt h)) :
    (↑(⁅a, b⁆) : Coordinate 2) = ⁅(↑a : Coordinate 2), ↑b⁆ := by
  rw [← Subgroup.coe_subtype, map_commutatorElement]

/-- Ambient commutators from `commutator ↥H ≤ K.subgroupOf H`. -/
theorem comm_mem_of_commutator_le {h : Nat} {K : Subgroup (Coordinate 2)}
    (hle : _root_.commutator (subAt h) ≤ K.subgroupOf (subAt h)) :
    ∀ x ∈ subAt h, ∀ y ∈ subAt h, ⁅x, y⁆ ∈ K := by
  intro x hx y hy
  have hmem : ⁅(⟨x, hx⟩ : ↥(subAt h)), (⟨y, hy⟩ : ↥(subAt h))⁆
      ∈ _root_.commutator (subAt h) := by
    rw [commutator_def]; exact commutator_mem_commutator (mem_top _) (mem_top _)
  have hK := hle hmem
  rw [Subgroup.mem_subgroupOf, coe_commutatorElement_subAt] at hK
  exact hK

/-- `commutator ↥H ≤ K.subgroupOf H` from ambient commutators. -/
theorem commutator_le_of_comm_mem {h : Nat} {K : Subgroup (Coordinate 2)}
    (hc : ∀ x ∈ subAt h, ∀ y ∈ subAt h, ⁅x, y⁆ ∈ K) :
    _root_.commutator (subAt h) ≤ K.subgroupOf (subAt h) := by
  rw [commutator_def, Subgroup.commutator_le]
  intro a _ b _
  rw [Subgroup.mem_subgroupOf, coe_commutatorElement_subAt]
  exact hc a a.property b b.property

/-- Ambient `5`th powers from `↥H`-level `5`th powers in `K.subgroupOf H`. -/
theorem pow_mem_ambient {h : Nat} {K : Subgroup (Coordinate 2)}
    (hp : ∀ q : subAt h, q ^ 5 ∈ K.subgroupOf (subAt h)) :
    ∀ x ∈ subAt h, x ^ 5 ∈ K := by
  intro x hx
  have hK := hp ⟨x, hx⟩
  rw [Subgroup.mem_subgroupOf] at hK
  rwa [show (↑((⟨x, hx⟩ : subAt h) ^ 5) : Coordinate 2) = x ^ 5 from by
    rw [Subgroup.coe_pow]] at hK

/-! ## The Frattini quotient `Q = ↥H ⧸ N` is abelian of exponent dividing `5` -/

/-- `commutator ↥H ≤ N := Φ.subgroupOf H`. -/
theorem commutator_le_N {h : Nat} {fc : FratCert} (cf : CertFacts h fc) :
    _root_.commutator (subAt h) ≤ (subAt fc.phiIdx).subgroupOf (subAt h) :=
  commutator_le_of_comm_mem (HH_comm_mem cf)

/-- **`Φ ≤ H`.** The Frattini subgroup sits inside `H` (`H` contains all its own
commutators and `5`th powers, and the witnesses build `Φ` from those). -/
theorem Phi_le_H {h : Nat} {fc : FratCert} (cf : CertFacts h fc) :
    subAt fc.phiIdx ≤ subAt h :=
  phi_le_of_comm_pow cf (subAt h)
    (fun a ha b hb => by
      rw [commutatorElement_def]
      exact mul_mem (mul_mem (mul_mem ha hb) (inv_mem ha)) (inv_mem hb))
    (fun a ha => (subAt h).pow_mem ha 5)

/-- `N := Φ.subgroupOf H` is normal in `↥H`. -/
theorem N_normal {h : Nat} {fc : FratCert} (cf : CertFacts h fc) :
    ((subAt fc.phiIdx).subgroupOf (subAt h)).Normal :=
  (normal_subgroupOf_iff_le_normalizer (Phi_le_H cf)).mpr (H_le_normalizer cf)

/-- `Q = ↥H ⧸ N` is commutative. -/
theorem Q_mul_comm {h : Nat} {fc : FratCert} (cf : CertFacts h fc) :
    letI := N_normal cf
    ∀ a b : ↥(subAt h) ⧸ (subAt fc.phiIdx).subgroupOf (subAt h), a * b = b * a := by
  haveI := N_normal cf
  exact isMulCommutative_iff.mp
    (Subgroup.Normal.quotient_commutative_iff_commutator_le.mpr (commutator_le_N cf))

/-- `Q = ↥H ⧸ N` has exponent dividing `5`. -/
theorem Q_exponent {h : Nat} {fc : FratCert} (cf : CertFacts h fc) :
    letI := N_normal cf
    Monoid.exponent (↥(subAt h) ⧸ (subAt fc.phiIdx).subgroupOf (subAt h)) ∣ 5 := by
  haveI := N_normal cf
  letI : CommGroup (↥(subAt h) ⧸ (subAt fc.phiIdx).subgroupOf (subAt h)) :=
    { (inferInstance : _root_.Group (↥(subAt h) ⧸ (subAt fc.phiIdx).subgroupOf (subAt h))) with
      mul_comm := Q_mul_comm cf }
  rw [Monoid.exponent_dvd_iff_forall_pow_eq_one]
  have key : ∀ z : ↥(subAt h),
      (QuotientGroup.mk' ((subAt fc.phiIdx).subgroupOf (subAt h)) z) ^ 5 = 1 := by
    intro z
    have htop : Subgroup.closure ((subAt h).subtype ⁻¹' {x : Coordinate 2 | x ∈ getB h}) = ⊤ := by
      rw [subAt_eq_closure]; exact closure_preimage_eq_top {x : Coordinate 2 | x ∈ getB h}
    have hz : z ∈ Subgroup.closure ((subAt h).subtype ⁻¹' {x : Coordinate 2 | x ∈ getB h}) :=
      htop ▸ Subgroup.mem_top z
    induction hz using Subgroup.closure_induction with
    | mem z' hz' =>
        simp only [Set.mem_preimage, Set.mem_setOf_eq, Subgroup.coe_subtype] at hz'
        rw [← map_pow, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff,
          Subgroup.mem_subgroupOf, Subgroup.coe_pow]
        have hp := cf.hpow _ hz'
        rwa [mpow5_eq] at hp
    | one => rw [map_one, one_pow]
    | mul a b _ _ iha ihb => rw [map_mul, mul_pow, iha, ihb, mul_one]
    | inv a _ iha => rw [map_inv, inv_pow, iha, inv_one]
  intro q
  obtain ⟨z, rfl⟩ := QuotientGroup.mk'_surjective _ q
  exact key z

/-! ## The hyperplane count for `Q`, transported to `maxIdxs.length` -/

/-- **Order of the Frattini quotient.** `|Q| = 5^(|H|_gens − |Φ|_gens)`. -/
theorem card_Q {h : Nat} {fc : FratCert} (cf : CertFacts h fc) :
    letI := N_normal cf
    Nat.card (↥(subAt h) ⧸ (subAt fc.phiIdx).subgroupOf (subAt h))
      = 5 ^ ((getB h).length - (getB fc.phiIdx).length) := by
  haveI := N_normal cf
  have hcardH : Nat.card (subAt h) = 5 ^ (getB h).length := card_subAt cf.hh
  have hcardN : Nat.card ((subAt fc.phiIdx).subgroupOf (subAt h))
      = 5 ^ (getB fc.phiIdx).length := by
    rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe (Phi_le_H cf)).toEquiv, card_subAt cf.hphi]
  have hlag := Subgroup.card_eq_card_quotient_mul_card_subgroup
    ((subAt fc.phiIdx).subgroupOf (subAt h))
  rw [hcardH, hcardN] at hlag
  have hle : (getB fc.phiIdx).length ≤ (getB h).length := by
    have hdvd : (5 : ℕ) ^ (getB fc.phiIdx).length ∣ 5 ^ (getB h).length :=
      ⟨_, by rw [hlag]; ring⟩
    exact (pow_dvd_pow_iff (by norm_num) (by rw [Nat.isUnit_iff]; decide)).mp hdvd
  have hsplit : (5 : ℕ) ^ (getB h).length
      = 5 ^ ((getB h).length - (getB fc.phiIdx).length) * 5 ^ (getB fc.phiIdx).length := by
    rw [← pow_add, Nat.sub_add_cancel hle]
  rw [hsplit] at hlag
  exact Nat.eq_of_mul_eq_mul_right (by positivity) hlag.symm

/-- **The count.** `Q` has exactly `maxIdxs.length` index-`5` subgroups. -/
theorem count_B {h : Nat} {fc : FratCert} (cf : CertFacts h fc) :
    letI := N_normal cf
    Nat.card {H' : Subgroup (↥(subAt h) ⧸ (subAt fc.phiIdx).subgroupOf (subAt h)) //
      Nat.card ((↥(subAt h) ⧸ (subAt fc.phiIdx).subgroupOf (subAt h)) ⧸ H') = 5}
      = fc.maxIdxs.length := by
  haveI := N_normal cf
  letI : CommGroup (↥(subAt h) ⧸ (subAt fc.phiIdx).subgroupOf (subAt h)) :=
    { (inferInstance : _root_.Group (↥(subAt h) ⧸ (subAt fc.phiIdx).subgroupOf (subAt h))) with
      mul_comm := Q_mul_comm cf }
  have hcount := LeanDring.P5Presentation.card_index_five_subgroups
    (↥(subAt h) ⧸ (subAt fc.phiIdx).subgroupOf (subAt h)) (Q_exponent cf)
  rw [card_Q cf] at hcount
  rw [cf.hcount, ← hcount, Nat.mul_div_cancel_left _ (by norm_num : 0 < 4)]

/-! ## Pigeonhole ingredients -/

/-- Distinct in-range indices present distinct subgroups. -/
theorem subAt_ne {i j : Nat} (hi : i < 676) (hj : j < 676) (hij : i ≠ j) :
    subAt i ≠ subAt j := by
  have hil : i < allBases.length := by rw [allBases_card]; exact hi
  have hjl : j < allBases.length := by rw [allBases_card]; exact hj
  have hei : subAt i = ofList 2 hq2 allBases[i] := by
    unfold subAt; rw [List.getD_eq_getElem allBases [] hil]
  have hej : subAt j = ofList 2 hq2 allBases[j] := by
    unfold subAt; rw [List.getD_eq_getElem allBases [] hjl]
  rw [hei, hej]
  rcases Nat.lt_or_ge i j with hlt | hge
  · exact (List.pairwise_iff_getElem.mp Hbases) i j hil hjl hlt
  · exact fun heq =>
      (List.pairwise_iff_getElem.mp Hbases) j i hjl hil
        (lt_of_le_of_ne hge hij.symm) heq.symm

/-- `Φ ≤ subAt j` for each listed maximal `j`. -/
theorem Phi_le_subAt {h : Nat} {fc : FratCert} (cf : CertFacts h fc) {j : Nat}
    (hj : j ∈ fc.maxIdxs) : subAt fc.phiIdx ≤ subAt j := by
  obtain ⟨hg1, _, _⟩ := cf.hmax j hj
  rw [subAt_eq_closure]; exact (Subgroup.closure_le _).mpr hg1

/-- `subAt j ≤ H` for each listed maximal `j`. -/
theorem subAt_le_H {h : Nat} {fc : FratCert} (cf : CertFacts h fc) {j : Nat}
    (hj : j ∈ fc.maxIdxs) : subAt j ≤ subAt h := by
  obtain ⟨_, hg2, _⟩ := cf.hmax j hj
  rw [subAt_eq_closure]; exact (Subgroup.closure_le _).mpr hg2

/-- Each listed maximal `subAt j` has relative index `5` in `H`. -/
theorem card_quot_five_of_mem {h : Nat} {fc : FratCert} (cf : CertFacts h fc) {j : Nat}
    (hj : j ∈ fc.maxIdxs) :
    Nat.card (↥(subAt h) ⧸ (subAt j).subgroupOf (subAt h)) = 5 := by
  obtain ⟨_, _, hlen⟩ := cf.hmax j hj
  have hcardsub : Nat.card ((subAt j).subgroupOf (subAt h)) = 5 ^ (getB j).length := by
    rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe (subAt_le_H cf hj)).toEquiv,
      card_subAt (cf.hmaxlt j hj)]
  have hlag := Subgroup.card_eq_card_quotient_mul_card_subgroup ((subAt j).subgroupOf (subAt h))
  rw [card_subAt cf.hh, hcardsub, ← hlen, pow_succ, mul_comm] at hlag
  exact (Nat.eq_of_mul_eq_mul_right (by positivity) hlag).symm

/-- Pushing an index-`5` subgroup of `↥H` containing `N` into `Q` keeps index `5`. -/
theorem card_quot_map {h : Nat} {fc : FratCert} (cf : CertFacts h fc)
    (S' : Subgroup ↥(subAt h)) (hNS : (subAt fc.phiIdx).subgroupOf (subAt h) ≤ S')
    (hidx : Nat.card (↥(subAt h) ⧸ S') = 5) :
    letI := N_normal cf
    Nat.card ((↥(subAt h) ⧸ (subAt fc.phiIdx).subgroupOf (subAt h)) ⧸
      Subgroup.map (QuotientGroup.mk' ((subAt fc.phiIdx).subgroupOf (subAt h))) S') = 5 := by
  haveI := N_normal cf
  set N := (subAt fc.phiIdx).subgroupOf (subAt h) with hNdef
  have hcomap : Subgroup.comap (QuotientGroup.mk' N)
      (Subgroup.map (QuotientGroup.mk' N) S') = S' :=
    Subgroup.comap_map_eq_self (by rw [QuotientGroup.ker_mk']; exact hNS)
  have hidxeq : (Subgroup.map (QuotientGroup.mk' N) S').index = S'.index := by
    conv_rhs => rw [← hcomap]
    exact (index_comap_of_surjective (Subgroup.map (QuotientGroup.mk' N) S')
      (QuotientGroup.mk'_surjective N)).symm
  rw [← Subgroup.index_eq_card, hidxeq, Subgroup.index_eq_card]; exact hidx

/-! ## The discharge -/

/-- **The isolated Frattini step obligation `FratDischarge`, discharged.** A valid
certificate at index `h` closes `subAt h` under its normal index-`5` subgroups. -/
theorem fratDischarge : FratDischarge := by
  intro h fc hchk M hMlt hMnorm hMidx
  have cf := certFacts_of_check hchk
  haveI hNnorm := N_normal cf
  set N := (subAt fc.phiIdx).subgroupOf (subAt h) with hNdef
  -- Step A: `Φ ≤ M`, since `H/M` is cyclic of order `5`.
  have hcard5M : Nat.card (↥(subAt h) ⧸ M.subgroupOf (subAt h)) = 5 := by
    rw [← Subgroup.index_eq_card]; exact hMidx
  haveI hMsub : (M.subgroupOf (subAt h)).Normal := hMnorm
  haveI hcyc : IsCyclic (↥(subAt h) ⧸ M.subgroupOf (subAt h)) := isCyclic_of_prime_card hcard5M
  have hcommM : _root_.commutator ↥(subAt h) ≤ M.subgroupOf (subAt h) :=
    Subgroup.Normal.quotient_commutative_iff_commutator_le.mp inferInstance
  have hpowM : ∀ q : ↥(subAt h), q ^ 5 ∈ M.subgroupOf (subAt h) := by
    intro q
    have hp := pow_card_eq_one' (G := ↥(subAt h) ⧸ M.subgroupOf (subAt h))
      (x := QuotientGroup.mk' _ q)
    rw [hcard5M, ← map_pow, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff] at hp
    exact hp
  have hPhiM : subAt fc.phiIdx ≤ M :=
    phi_le_of_comm_pow cf M (comm_mem_of_commutator_le hcommM) (pow_mem_ambient hpowM)
  -- Step C: pigeonhole over the index-`5` subgroups of `Q = ↥H ⧸ N`.
  set Q := ↥(subAt h) ⧸ N with hQdef
  set mkN := QuotientGroup.mk' N with hmkN
  haveI : Finite (Subgroup Q) := Finite.of_injective _ (SetLike.coe_injective (A := Subgroup Q))
  have hkerN : mkN.ker = N := by rw [hmkN, QuotientGroup.ker_mk']
  have hNleMax : ∀ {j : Nat}, j ∈ fc.maxIdxs → N ≤ (subAt j).subgroupOf (subAt h) :=
    fun hj => Subgroup.comap_mono (Phi_le_subAt cf hj)
  have hNleM : N ≤ M.subgroupOf (subAt h) := Subgroup.comap_mono hPhiM
  -- the `B`-element attached to a listed maximal / to `M`
  let B := {H' : Subgroup Q // Nat.card (Q ⧸ H') = 5}
  let bB : {j // j ∈ fc.maxIdxs} → B := fun jm =>
    ⟨Subgroup.map mkN ((subAt jm.1).subgroupOf (subAt h)),
      card_quot_map cf _ (hNleMax jm.2) (card_quot_five_of_mem cf jm.2)⟩
  let bM : B := ⟨Subgroup.map mkN (M.subgroupOf (subAt h)),
    card_quot_map cf _ hNleM hcard5M⟩
  -- the injective family from `Fin maxIdxs.length`
  let f : Fin fc.maxIdxs.length → B :=
    fun i => bB ⟨fc.maxIdxs.get i, fc.maxIdxs.get_mem i⟩
  haveI : Fintype B := Fintype.ofFinite B
  have hfinj : Function.Injective f := by
    intro i i' hii
    have h1 : Subgroup.map mkN ((subAt (fc.maxIdxs.get i)).subgroupOf (subAt h))
        = Subgroup.map mkN ((subAt (fc.maxIdxs.get i')).subgroupOf (subAt h)) :=
      congrArg Subtype.val hii
    have h2 : (subAt (fc.maxIdxs.get i)).subgroupOf (subAt h)
        = (subAt (fc.maxIdxs.get i')).subgroupOf (subAt h) := by
      have e1 := Subgroup.comap_map_eq_self (f := mkN)
        (H := (subAt (fc.maxIdxs.get i)).subgroupOf (subAt h))
        (hkerN.le.trans (hNleMax (fc.maxIdxs.get_mem i)))
      have e2 := Subgroup.comap_map_eq_self (f := mkN)
        (H := (subAt (fc.maxIdxs.get i')).subgroupOf (subAt h))
        (hkerN.le.trans (hNleMax (fc.maxIdxs.get_mem i')))
      rw [← e1, ← e2, h1]
    have h3 : subAt (fc.maxIdxs.get i) = subAt (fc.maxIdxs.get i') := by
      rw [← Subgroup.map_subgroupOf_eq_of_le (subAt_le_H cf (fc.maxIdxs.get_mem i)),
        ← Subgroup.map_subgroupOf_eq_of_le (subAt_le_H cf (fc.maxIdxs.get_mem i')), h2]
    have h4 : fc.maxIdxs.get i = fc.maxIdxs.get i' := by
      by_contra hne
      exact subAt_ne (cf.hmaxlt _ (fc.maxIdxs.get_mem i))
        (cf.hmaxlt _ (fc.maxIdxs.get_mem i')) hne h3
    exact List.nodup_iff_injective_get.mp cf.hnodup h4
  -- injective family between types of equal card ⟹ surjective ⟹ `bM` is hit
  have hcardeq : Fintype.card (Fin fc.maxIdxs.length) = Fintype.card B := by
    rw [Fintype.card_fin, ← Nat.card_eq_fintype_card, count_B cf]
  have hsurj : Function.Surjective f :=
    ((Fintype.bijective_iff_injective_and_card f).mpr ⟨hfinj, hcardeq⟩).surjective
  obtain ⟨i, hi⟩ := hsurj bM
  -- decode: `M = subAt (get i)`
  have h1 : Subgroup.map mkN ((subAt (fc.maxIdxs.get i)).subgroupOf (subAt h))
      = Subgroup.map mkN (M.subgroupOf (subAt h)) := congrArg Subtype.val hi
  have h2 : (subAt (fc.maxIdxs.get i)).subgroupOf (subAt h) = M.subgroupOf (subAt h) := by
    have e1 := Subgroup.comap_map_eq_self (f := mkN)
      (H := (subAt (fc.maxIdxs.get i)).subgroupOf (subAt h))
      (hkerN.le.trans (hNleMax (fc.maxIdxs.get_mem i)))
    have e2 := Subgroup.comap_map_eq_self (f := mkN) (H := M.subgroupOf (subAt h))
      (hkerN.le.trans hNleM)
    rw [← e1, ← e2, h1]
  have hMeq : M = subAt (fc.maxIdxs.get i) := by
    rw [← Subgroup.map_subgroupOf_eq_of_le hMlt.le,
      ← Subgroup.map_subgroupOf_eq_of_le (subAt_le_H cf (fc.maxIdxs.get_mem i)), h2]
  rw [hMeq]
  exact inInv_subAt _ (cf.hmaxlt _ (fc.maxIdxs.get_mem i))

/-! ## Now-unconditional consequences (relative only to certificate coverage) -/

/-- **Per-`H` closure on the certified pilot slice**, now unconditional: every
subgroup in `certified` has its normal index-`5` subgroups back in the inventory. -/
theorem inv_closed_on_certified_uncond :
    ∀ p ∈ certified, ∀ M : Subgroup (Coordinate 2), M < subAt p.1 →
      (M.subgroupOf (subAt p.1)).Normal → M.relIndex (subAt p.1) = 5 → InInv M :=
  inv_closed_on_certified fratDischarge

/-- **`NormalIndexFiveClosed` from full certificate coverage** (unconditional
relative to `coverage`; `FratDischarge` is now proved). -/
theorem normalIndexFiveClosed_of_coverage
    (coverage : ∀ h, h < 676 → ∃ fc, (h, fc) ∈ certified ∧ fratCertB h fc = true) :
    NormalIndexFiveClosed :=
  normalIndexFiveClosed_of_all_certified fratDischarge coverage

/-- **Inventory completeness from full certificate coverage** (unconditional
relative to `coverage`). -/
theorem allSubs_complete_of_coverage
    (coverage : ∀ h, h < 676 → ∃ fc, (h, fc) ∈ certified ∧ fratCertB h fc = true) :
    ∀ K : Subgroup (Coordinate 2), ∃ c ∈ allSubs, c.toSubgroup = K :=
  allSubs_complete_of_all_certified fratDischarge coverage

/-! ## Subgroup inventory, complete — the unconditional consequences

`coverage_full` (`LeanDring/P5/Certificate/SubgroupInventory/Twin2/FrattiniCert.lean`) discharges
the `coverage` hypothesis for all
`676` inventory indices by kernel `decide`. Combined with the now-proven
`FratDischarge`, this closes the subgroup inventory completely: the following are
**unconditional**. -/

/-- **`NormalIndexFiveClosed`, unconditional.** The inventory is closed under
passage to normal index-`5` subgroups. -/
theorem normalIndexFiveClosed : NormalIndexFiveClosed :=
  normalIndexFiveClosed_of_coverage coverage_full

/-- **`MaximalsClosed`, unconditional.** The inventory is closed under passage to
maximal proper subgroups. -/
theorem maximalsClosed : MaximalsClosed :=
  maximalsClosed_of_normalIndexFiveClosed normalIndexFiveClosed

/-- **Inventory completeness, unconditional.** Every subgroup of
`Coordinate 2` (the order-`5⁵` group) is presented by a member of the `676`-entry
inventory `allSubs`. -/
theorem allSubs_complete :
    ∀ K : Subgroup (Coordinate 2), ∃ c ∈ allSubs, c.toSubgroup = K :=
  allSubs_complete_of_coverage coverage_full

end Q2

/-! ## Top-level aliases (the twin q=2 headline names) -/

/-- The certified 676-subgroup inventory of `Coordinate 2` (SmallGroup(3125,69)). -/
def allSubs2 : List (Cgs 2 hq2) := Q2.allSubs

/-- **Inventory completeness, twin q=2: the q=2 twin, unconditional.**
Every subgroup of `Coordinate 2` is presented by a member of the 676-entry
inventory `allSubs2`. -/
theorem allSubs2_complete :
    ∀ K : Subgroup (Coordinate 2), ∃ c ∈ allSubs2, c.toSubgroup = K :=
  Q2.allSubs_complete

end LeanDring.P5Presentation
