/-
Copyright (c) 2026 Tilemachos Vassias. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tilemachos Vassias (formalization assisted by Claude)
-/
import LeanDring.Theory.Cyclotomic.CyclotomicCode

/-!
# Executable cyclotomic codes for the exponent-25 target

The published order-`5^5` pair has exponent `25`.  We therefore use the
power basis `1, ζ, ..., ζ^19` and the explicit relation

`Φ₂₅(ζ) = 1 + ζ⁵ + ζ¹⁰ + ζ¹⁵ + ζ²⁰ = 0`.

Unlike the generic proof layer in `CyclotomicCode`, a `Code` is just twenty
integers and has executable equality.  The reflection theorem below proves
that equality of these arrays is equivalent to equality after evaluation at
any primitive complex 25th root.  This file intentionally does not implement
a general cyclotomic computer: conductor 25 is the exact paper-facing target.
-/

namespace LeanDring.P5CyclotomicCode

open scoped BigOperators
open Polynomial

/-- Coefficients in the integral power basis `1, ζ, ..., ζ^19`. -/
abbrev Code := Fin 20 → ℤ

/-- The `i`th power-basis vector. -/
def basis (i : Fin 20) : Code := fun j => if j = i then 1 else 0

/-- Addition of exact codes. -/
def add (a b : Code) : Code := fun i => a i + b i

/-- Additive inverse of an exact code. -/
def neg (a : Code) : Code := fun i => -a i

/-- The explicit `Φ₂₅` reduction of `ζ^(20+s)`, for `0 ≤ s < 5`. -/
def highPower (s : Fin 5) : Code := fun i =>
  if (i : ℕ) % 5 = (s : ℕ) then -1 else 0

/-- Exact code for the `r`th power of a primitive 25th root. -/
def residuePower (r : Fin 25) : Code :=
  if h : (r : ℕ) < 20 then
    basis ⟨(r : ℕ), h⟩
  else
    highPower ⟨(r : ℕ) - 20, by omega⟩

/-- Exact code for an arbitrary natural power, reduced modulo 25. -/
def power (k : ℕ) : Code :=
  residuePower ⟨k % 25, Nat.mod_lt _ (by norm_num)⟩

/-- Sum exact root-of-unity codes.  This is the operation used for species
values, which are finite sums of linear-character values. -/
def sumPowers {ι : Type*} [Fintype ι] (e : ι → ℕ) : Code :=
  fun j => ∑ i, power (e i) j

/-- Kernel-executable comparison of two exponent-25 root-of-unity sums. -/
def equalSums {ι κ : Type*} [Fintype ι] [Fintype κ]
    (e : ι → ℕ) (f : κ → ℕ) : Bool :=
  decide (sumPowers e = sumPowers f)

/-- Interpret a code as a rational polynomial of degree below 20.  This is a
proof-layer definition; executable comparison uses array/function equality. -/
noncomputable def toPoly (a : Code) : ℚ[X] :=
  ∑ i : Fin 20, monomial (i : ℕ) (a i : ℚ)

/-- Evaluate an exact code in the power basis generated by `ζ`. -/
noncomputable def eval (ζ : ℂ) (a : Code) : ℂ :=
  ∑ i : Fin 20, (a i : ℂ) * ζ ^ (i : ℕ)

theorem eval_basis (ζ : ℂ) (i : Fin 20) : eval ζ (basis i) = ζ ^ (i : ℕ) := by
  classical
  simp [eval, basis]

theorem eval_add (ζ : ℂ) (a b : Code) :
    eval ζ (add a b) = eval ζ a + eval ζ b := by
  simp [eval, add, Finset.sum_add_distrib, add_mul]

theorem eval_neg (ζ : ℂ) (a : Code) : eval ζ (neg a) = -eval ζ a := by
  simp [eval, neg, Finset.sum_neg_distrib]

private theorem phi25_value_zero {ζ : ℂ} (hζ : IsPrimitiveRoot ζ 25) :
    1 + ζ ^ 5 + ζ ^ 10 + ζ ^ 15 + ζ ^ 20 = 0 := by
  have hz25 : ζ ^ 25 = 1 := hζ.pow_eq_one
  have hz5 : ζ ^ 5 ≠ 1 := by
    intro h
    have hdvd := (hζ.pow_eq_one_iff_dvd 5).mp h
    norm_num at hdvd
  have hm : (ζ ^ 5 - 1) * (1 + ζ ^ 5 + ζ ^ 10 + ζ ^ 15 + ζ ^ 20) = 0 := by
    rw [← sub_eq_zero.mpr hz25]
    ring
  exact (mul_eq_zero.mp hm).resolve_left (sub_ne_zero.mpr hz5)

theorem eval_highPower {ζ : ℂ} (hζ : IsPrimitiveRoot ζ 25) (s : Fin 5) :
    eval ζ (highPower s) = ζ ^ (20 + (s : ℕ)) := by
  have hΦ := phi25_value_zero hζ
  fin_cases s <;>
    norm_num [eval, highPower, Fin.sum_univ_succ] <;>
    ring_nf at hΦ ⊢
  · linear_combination -hΦ
  · linear_combination -ζ * hΦ
  · linear_combination -(ζ ^ 2) * hΦ
  · linear_combination -(ζ ^ 3) * hΦ
  · linear_combination -(ζ ^ 4) * hΦ

theorem eval_residuePower {ζ : ℂ} (hζ : IsPrimitiveRoot ζ 25) (r : Fin 25) :
    eval ζ (residuePower r) = ζ ^ (r : ℕ) := by
  rw [residuePower]
  split_ifs with h
  · exact eval_basis ζ ⟨(r : ℕ), h⟩
  · rw [eval_highPower hζ]
    change ζ ^ (20 + ((r : ℕ) - 20)) = ζ ^ (r : ℕ)
    congr 1
    omega

theorem eval_power {ζ : ℂ} (hζ : IsPrimitiveRoot ζ 25) (k : ℕ) :
    eval ζ (power k) = ζ ^ k := by
  rw [power, eval_residuePower hζ]
  exact (pow_eq_pow_mod k hζ.pow_eq_one).symm

theorem eval_sumPowers {ι : Type*} [Fintype ι] {ζ : ℂ}
    (hζ : IsPrimitiveRoot ζ 25) (e : ι → ℕ) :
    eval ζ (sumPowers e) = ∑ i, ζ ^ e i := by
  classical
  calc
    eval ζ (sumPowers e) =
        ∑ j : Fin 20, ∑ i : ι, (power (e i) j : ℂ) * ζ ^ (j : ℕ) := by
      simp_rw [eval, sumPowers, Int.cast_sum, Finset.sum_mul]
    _ = ∑ i : ι, ∑ j : Fin 20, (power (e i) j : ℂ) * ζ ^ (j : ℕ) := by
      rw [Finset.sum_comm]
    _ = ∑ i, ζ ^ e i := by
      apply Finset.sum_congr rfl
      intro i _
      exact eval_power hζ (e i)

theorem eval_toPoly (ζ : ℂ) (a : Code) :
    CyclotomicCode.eval ζ (toPoly a) = eval ζ a := by
  classical
  rw [CyclotomicCode.eval, toPoly, eval, eval₂_finsetSum]
  apply Finset.sum_congr rfl
  intro i _
  simp [eval₂_monomial]

theorem coeff_toPoly (a : Code) (i : Fin 20) :
    (toPoly a).coeff i = (a i : ℚ) := by
  classical
  rw [toPoly]
  rw [finsetSum_coeff]
  have hi : ((monomial (i : ℕ) (a i : ℚ)).coeff i) = (a i : ℚ) := by
    simp
  rw [← hi]
  apply Finset.sum_eq_single_of_mem i (Finset.mem_univ i)
  · intro j _ hji
    simp only [coeff_monomial]
    split_ifs with h
    · exact (hji (Fin.ext h)).elim
    · rfl

theorem degree_toPoly_lt (a : Code) : (toPoly a).degree < 20 := by
  apply (degree_lt_iff_coeff_zero (toPoly a) 20).2
  intro n hn
  classical
  rw [toPoly]
  rw [finsetSum_coeff]
  apply Finset.sum_eq_zero
  intro i _
  simp only [coeff_monomial]
  split_ifs with h
  · omega
  · rfl

/-- Evaluation in a primitive 25th root is injective on the 20-coordinate
power-basis codes. -/
theorem eval_injective {ζ : ℂ} (hζ : IsPrimitiveRoot ζ 25) :
    Function.Injective (eval ζ) := by
  intro a b hab
  have hroot : Polynomial.aeval ζ (toPoly a - toPoly b) = 0 := by
    rw [aeval_def, eval₂_sub]
    change CyclotomicCode.eval ζ (toPoly a) -
      CyclotomicCode.eval ζ (toPoly b) = 0
    rw [eval_toPoly, eval_toPoly, hab, sub_self]
  have hirr : Irreducible (cyclotomic 25 ℚ) :=
    cyclotomic.irreducible_rat (by norm_num)
  have hmin : minpoly ℚ ζ = cyclotomic 25 ℚ :=
    (hζ.minpoly_eq_cyclotomic_of_irreducible hirr).symm
  have hdvd : cyclotomic 25 ℚ ∣ toPoly a - toPoly b := by
    rw [← hmin]
    exact minpoly.dvd ℚ ζ hroot
  have hpzero : toPoly a - toPoly b = 0 := by
    by_contra hp
    have hdeg := natDegree_le_of_dvd hdvd hp
    have hlt : (toPoly a - toPoly b).natDegree < 20 := by
      apply (natDegree_lt_iff_degree_lt hp).mpr
      exact (degree_sub_le _ _).trans_lt
        (max_lt (degree_toPoly_lt a) (degree_toPoly_lt b))
    rw [natDegree_cyclotomic] at hdeg
    have ht : Nat.totient 25 = 20 := by
      rw [show 25 = 5 ^ 2 by norm_num,
        Nat.totient_prime_pow Nat.prime_five (by norm_num)]
      norm_num
    rw [ht] at hdeg
    omega
  apply _root_.funext
  intro i
  have hc := congrArg (fun p : ℚ[X] => p.coeff i) hpzero
  have hc' : (a i : ℚ) - (b i : ℚ) = 0 := by
    simpa only [coeff_sub, coeff_zero, coeff_toPoly] using hc
  exact_mod_cast (sub_eq_zero.mp hc')

/-- Executable code equality exactly reflects complex equality at a primitive
25th root. -/
theorem code_eq_iff_eval_eq {ζ : ℂ} (hζ : IsPrimitiveRoot ζ 25) (a b : Code) :
    a = b ↔ eval ζ a = eval ζ b := by
  constructor
  · exact congrArg _
  · exact fun h => eval_injective hζ h

/-- The executable comparison is sound and complete for equality of the
corresponding complex root-of-unity sums. -/
theorem equalSums_eq_true_iff {ι κ : Type*} [Fintype ι] [Fintype κ]
    {ζ : ℂ} (hζ : IsPrimitiveRoot ζ 25) (e : ι → ℕ) (f : κ → ℕ) :
    equalSums e f = true ↔ (∑ i, ζ ^ e i) = ∑ j, ζ ^ f j := by
  rw [equalSums, decide_eq_true_eq, code_eq_iff_eval_eq hζ,
    eval_sumPowers hζ, eval_sumPowers hζ]

/-- Adapter used when constructing a `SpeciesTableEncoding`: once each
species entry has been proved to be the indicated finite sum of 25th-root
powers, equality of the executable codes is exactly equality of species
values.  The two representation equalities remain explicit proof obligations;
this theorem does not trust an external table silently. -/
theorem sumPowers_eq_iff_value_eq {ι κ : Type*} [Fintype ι] [Fintype κ]
    {ζ x y : ℂ} (hζ : IsPrimitiveRoot ζ 25) (e : ι → ℕ) (f : κ → ℕ)
    (hx : x = ∑ i, ζ ^ e i) (hy : y = ∑ j, ζ ^ f j) :
    sumPowers e = sumPowers f ↔ x = y := by
  rw [code_eq_iff_eval_eq hζ, eval_sumPowers hζ, eval_sumPowers hζ, ← hx, ← hy]

/-- Hand-checkable positive regression: the five terms of `Φ₂₅` sum to zero. -/
theorem phi25_regression :
    equalSums (fun i : Fin 5 => (i : ℕ) * 5) (fun i : Fin 0 => (i : ℕ)) = true := by
  decide

/-- Hand-checkable negative regression: `1` and `ζ` have different codes. -/
theorem one_ne_zeta_regression :
    equalSums (fun _ : Fin 1 => 0) (fun _ : Fin 1 => 1) = false := by
  decide

end LeanDring.P5CyclotomicCode
