/-
Copyright (c) 2026 Tilemachos Vassias. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tilemachos Vassias (formalization assisted by Claude)
-/
-- Hand-written P5 certificate machinery
import LeanDring.P5.Certificate.SubgroupInventory.Twin1.AllSubgroups
import LeanDring.P5.Certificate.SubgroupInventory.Twin2.AllSubgroups
import LeanDring.P5.Certificate.SubgroupInventory.Twin1.AllSubgroupsProofs
import LeanDring.P5.Certificate.SubgroupInventory.Twin2.AllSubgroupsProofs
import LeanDring.P5.Certificate.RingIsomorphism.Twin1.Assembly
import LeanDring.P5.Certificate.ComputableModel.Twin1.Cgs
import LeanDring.P5.Certificate.Characters.Twin2.CharAlign
import LeanDring.P5.Certificate.Characters.Twin1.CharAssembly
import LeanDring.P5.Certificate.Characters.Twin2.CharAssembly
import LeanDring.P5.Certificate.Characters.Twin1.CharBasis.Chunk01
import LeanDring.P5.Certificate.Characters.Twin1.CharBasis.Chunk02
import LeanDring.P5.Certificate.Characters.Twin1.CharBasis.Chunk03
import LeanDring.P5.Certificate.Characters.Twin2.CharBasis.Chunk01
import LeanDring.P5.Certificate.Characters.Twin2.CharBasis.Chunk02
import LeanDring.P5.Certificate.Characters.Twin2.CharBasis.Chunk03
import LeanDring.P5.Certificate.Characters.Twin2.CharBasis.Chunk04
import LeanDring.P5.Certificate.Characters.Twin1.CharBasis.Chunk04
import LeanDring.P5.Certificate.Characters.Twin1.CharBox
import LeanDring.P5.Certificate.Characters.Twin2.CharBox
import LeanDring.P5.Certificate.Characters.Twin1.CharBoxReps
import LeanDring.P5.Certificate.Characters.Twin2.CharBoxReps
import LeanDring.P5.Certificate.Characters.Twin1.CharCert
import LeanDring.P5.Certificate.Characters.Twin2.CharCert
import LeanDring.P5.Certificate.Characters.Twin1.CharComplete
import LeanDring.P5.Certificate.Characters.Twin2.CharComplete
import LeanDring.P5.Certificate.Characters.Twin2.CharCompleteFull
import LeanDring.P5.Certificate.Characters.Twin2.CharComplete.Chunk01
import LeanDring.P5.Certificate.Characters.Twin2.CharComplete.Chunk02
import LeanDring.P5.Certificate.Characters.Twin2.CharComplete.Chunk03
import LeanDring.P5.Certificate.Characters.Twin2.CharComplete.Chunk04
import LeanDring.P5.Certificate.Characters.Twin2.CharComplete.Chunk05
import LeanDring.P5.Certificate.Characters.Twin2.CharComplete.Chunk06
import LeanDring.P5.Certificate.Characters.Twin2.CharComplete.Chunk07
import LeanDring.P5.Certificate.Characters.Twin2.CharComplete.Chunk08
import LeanDring.P5.Certificate.Characters.Twin1.CharCompleteStage3
import LeanDring.P5.Certificate.Characters.Twin1.CharComplete.Chunk01
import LeanDring.P5.Certificate.Characters.Twin1.CharComplete.Chunk02
import LeanDring.P5.Certificate.Characters.Twin1.CharComplete.Chunk03
import LeanDring.P5.Certificate.Characters.Twin1.CharComplete.Chunk04
import LeanDring.P5.Certificate.Characters.Twin1.CharComplete.Chunk05
import LeanDring.P5.Certificate.Characters.Twin1.CharComplete.Chunk06
import LeanDring.P5.Certificate.Characters.Twin1.CharComplete.Chunk07
import LeanDring.P5.Certificate.Characters.Twin1.CharComplete.Chunk08
import LeanDring.P5.Certificate.Characters.Twin1.CharCompleteFinal
import LeanDring.P5.Certificate.Characters.Twin1.CharCount
import LeanDring.P5.Certificate.Characters.Twin2.CharCount
import LeanDring.P5.Certificate.Characters.Twin1.CharData
import LeanDring.P5.Certificate.Characters.Twin2.CharData
import LeanDring.P5.Certificate.Characters.Twin1.CharExhaust
import LeanDring.P5.Certificate.Characters.Twin2.CharExhaust
import LeanDring.P5.Certificate.Characters.Twin1.CharExp
import LeanDring.P5.Certificate.Characters.Twin2.CharExp
import LeanDring.P5.Certificate.Characters.Twin1.CharExtend
import LeanDring.P5.Certificate.Characters.Twin2.CharExtend
import LeanDring.P5.Certificate.Characters.Twin1.CharNodup
import LeanDring.P5.Certificate.Characters.Twin2.CharNodup
import LeanDring.P5.Certificate.Characters.Twin1.CharRows.Chunk01
import LeanDring.P5.Certificate.Characters.Twin1.CharRows.Chunk02
import LeanDring.P5.Certificate.Characters.Twin1.CharRows.Chunk03
import LeanDring.P5.Certificate.Characters.Twin2.CharRows.Chunk01
import LeanDring.P5.Certificate.Characters.Twin2.CharRows.Chunk02
import LeanDring.P5.Certificate.Characters.Twin2.CharRows.Chunk03
import LeanDring.P5.Certificate.Characters.Twin2.CharRows.Chunk04
import LeanDring.P5.Certificate.Characters.Twin2.CharRows.Chunk05
import LeanDring.P5.Certificate.Characters.Twin2.CharRows.Chunk06
import LeanDring.P5.Certificate.Characters.Twin2.CharRows.Chunk07
import LeanDring.P5.Certificate.Characters.Twin2.CharRows.Chunk08
import LeanDring.P5.Certificate.Characters.Twin1.CharRows.Chunk04
import LeanDring.P5.Certificate.Characters.Twin1.CharValid
import LeanDring.P5.Certificate.Characters.Twin2.CharValid
import LeanDring.P5.Certificate.Characters.Twin1.CharVecLen
import LeanDring.P5.Certificate.Characters.Twin2.CharVecLen
import LeanDring.P5.Certificate.SpeciesTable.Twin1.ColCert
import LeanDring.P5.Certificate.SpeciesTable.Twin1.ColDataGap
import LeanDring.P5.Certificate.SubgroupInventory.Twin1.Complete
import LeanDring.P5.Certificate.SubgroupInventory.Twin2.Complete
import LeanDring.P5.Certificate.ComputableModel.Twin1.ComputableGroup
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.ConjAux
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.ConjBound
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.ConjCount
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.ConjR.Chunk01
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.ConjR.Chunk02
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.ConjR.Chunk03
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.ConjR.Chunk04
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.ConjR.Chunk05
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.ConjTree
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.ConjAux
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.ConjBound
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.ConjClasses
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.ConjClasses
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.ConjCount
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.ConjData
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.ConjData
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.ConjR.Chunk01
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.ConjR.Chunk02
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.ConjR.Chunk03
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.ConjR.Chunk04
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.ConjR.Chunk05
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.ConjTree
import LeanDring.P5.Certificate.Support.Counterexample
import LeanDring.P5.Certificate.Support.CyclotomicCode
import LeanDring.P5.Certificate.SpeciesTable.Twin1.EntryCore
import LeanDring.P5.Certificate.SpeciesTable.Twin2.EntryCore
import LeanDring.P5.Certificate.SpeciesTable.Twin1.EntryData
import LeanDring.P5.Certificate.SpeciesTable.Twin2.EntryDataGap
import LeanDring.P5.Certificate.SpeciesTable.EntryFast
import LeanDring.P5.Certificate.SpeciesTable.Twin1.EntryFix
import LeanDring.P5.Certificate.SpeciesTable.EntrySupport
import LeanDring.P5.Certificate.SpeciesTable.EntryTransA
import LeanDring.P5.Certificate.SubgroupInventory.Twin1.FratDischarge
import LeanDring.P5.Certificate.SubgroupInventory.Twin2.FratDischarge
import LeanDring.P5.Certificate.SubgroupInventory.Twin1.FrattiniCert
import LeanDring.P5.Certificate.SubgroupInventory.Twin2.FrattiniCert
import LeanDring.P5.Certificate.Support.IndexCount
import LeanDring.P5.Certificate.SubgroupInventory.Twin1.Inj625
import LeanDring.P5.Certificate.RingIsomorphism.MatchAll
import LeanDring.P5.Certificate.RingIsomorphism.MatchCore
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.NormCard
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.NormCard
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.NormChunk.Chunk01
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.NormChunk.Chunk01
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.NormChunk.Chunk02
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.NormChunk.Chunk02
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.NormChunk.Chunk03
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.NormChunk.Chunk03
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.NormChunk.Chunk04
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.NormChunk.Chunk04
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.NormLink1
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.NormLink1
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.NormLink
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.NormLink2Data
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.NormLink2Data
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.NormLink
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.NormOrbitData
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.NormOrbitData
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.NormOrbits
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.NormOrbits
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.PairClass
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.PairClass
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.PairClassInj
import LeanDring.P5.Certificate.ConjugacyClasses.Twin2.PairClassInj
import LeanDring.P5.Certificate.Presentation.Presentation
import LeanDring.P5.Certificate.RingIsomorphism.Twin2.Sigma
import LeanDring.P5.Certificate.SpeciesTable.Twin1.SpeciesColumn
import LeanDring.P5.Certificate.SpeciesTable.Twin2.SpeciesColumn
import LeanDring.P5.Certificate.SpeciesTable.Twin1.SpeciesComplete
import LeanDring.P5.Certificate.SpeciesTable.Twin2.SpeciesComplete
import LeanDring.P5.Certificate.SpeciesTable.Twin1.SpeciesCosets
import LeanDring.P5.Certificate.SpeciesTable.Twin2.SpeciesCosets
import LeanDring.P5.Certificate.SpeciesTable.Twin1.SpeciesLink
import LeanDring.P5.Certificate.SpeciesTable.Twin2.SpeciesLink
import LeanDring.P5.Certificate.SpeciesTable.Twin1.SpeciesOrbitData
import LeanDring.P5.Certificate.SpeciesTable.Twin2.SpeciesOrbitData
import LeanDring.P5.Certificate.SpeciesTable.Twin1.SpeciesOrbits
import LeanDring.P5.Certificate.SpeciesTable.Twin2.SpeciesOrbits
import LeanDring.P5.Certificate.SpeciesTable.Twin2.SpeciesTau.Chunk01
import LeanDring.P5.Certificate.SpeciesTable.Twin2.SpeciesTau.Chunk02
import LeanDring.P5.Certificate.SpeciesTable.Twin2.SpeciesTau.Chunk03
import LeanDring.P5.Certificate.Support.Stage5Core

-- Machine-emitted P5 data families (one index per family)
import LeanDring.P5.Data.ColCdd
import LeanDring.P5.Data.ColRestCheap
import LeanDring.P5.Data.ColRestHeavy
import LeanDring.P5.Data.ColTau
import LeanDring.P5.Data.EntryA
import LeanDring.P5.Data.EntryK
import LeanDring.P5.Data.FixZero
import LeanDring.P5.Data.MatchLeaf
import LeanDring.P5.Data.MatchMaster
import LeanDring.P5.Data.MatchPair
import LeanDring.P5.Data.SpeciesAlign
import LeanDring.P5.Data.SpeciesDiv
import LeanDring.P5.Data.SpeciesOrbitChunk

/-!
# LeanDring.P5

Aggregator for the order-3125 (5⁵) D-ring rigidity/counterexample
development: hand-written machinery in `P5/Certificate/` plus the
machine-emitted data families indexed in `P5/Data/`.
-/
