/-
Copyright (c) 2026 Tilemachos Vassias. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tilemachos Vassias (formalization assisted by Claude)
-/
import Mathlib.NumberTheory.Cyclotomic.PrimitiveRoots

/-!
# A primitive `p²`-th root of unity is not in `ℤ[ζ_p]`

`zetaP2_not_mem_adjoin_zetaP`: for `p` prime, a primitive `p²`-th root of unity
does not lie in the subring `ℤ[ζ_p]` generated by a primitive `p`-th root. This
is the cyclotomic core of the order-`p⁴` twin separation: the `G₂` distinguished
species entry `z` carries a `ζ_{p²}` factor, so it falls outside `ℤ[ζ_p]` and
therefore cannot be one of the `ℤ[ζ_p]`-valued (non-order-`p²`) A-block entries.

The proof is a degree count: with `L₁ = ℚ(ζ_p)`, `L₂ = ℚ(ζ_{p²})`, membership
`ζ_{p²} ∈ ℤ[ζ_p] ⊆ L₁` gives `L₂ ≤ L₁`, hence
`φ(p²) = [L₂:ℚ] ≤ [L₁:ℚ] = φ(p)`, i.e. `p(p-1) ≤ p-1` — impossible for `p > 1`.

-/

namespace LeanDring.P4

/-- A primitive `p²`-th root of unity is not in the ring `ℤ[ζ]` generated by a
primitive `p`-th root, for `p` prime.  (In `ℂ`; `ζp2` a primitive `p²`-th root,
`ζp` a primitive `p`-th root.) -/
theorem zetaP2_not_mem_adjoin_zetaP
    {p : ℕ} (hp : p.Prime) (_hodd : Odd p)
    {ζp2 ζp : ℂ} (hζp2 : IsPrimitiveRoot ζp2 (p ^ 2)) (hζp : IsPrimitiveRoot ζp p) :
    ζp2 ∉ (Algebra.adjoin ℤ {ζp} : Subalgebra ℤ ℂ) := by
  intro h
  have hpos : 0 < p := hp.pos
  haveI : NeZero (p ^ 2) := ⟨by positivity⟩
  haveI : NeZero p := ⟨hp.pos.ne'⟩
  let L1 : Subalgebra ℚ ℂ := Algebra.adjoin ℚ {ζp}
  let L2 : Subalgebra ℚ ℂ := Algebra.adjoin ℚ {ζp2}
  have h1 : ζp2 ∈ L1 := by
    have H : (Algebra.adjoin ℤ {ζp} : Subalgebra ℤ ℂ) ≤ L1.restrictScalars ℤ := by
      rw [Algebra.adjoin_le_iff]
      simp [L1, Algebra.subset_adjoin]
    exact H h
  have h2 : L2 ≤ L1 := by
    rw [Algebra.adjoin_le_iff]
    intro x hx
    cases hx
    exact h1
  have h2_submod : L2.toSubmodule ≤ L1.toSubmodule := h2
  haveI : IsCyclotomicExtension {p} ℚ L1 := hζp.adjoin_isCyclotomicExtension ℚ
  haveI : IsCyclotomicExtension {p ^ 2} ℚ L2 := hζp2.adjoin_isCyclotomicExtension ℚ
  haveI : Module.Finite ℚ L1 := IsCyclotomicExtension.finiteDimensional {p} ℚ L1
  have h3 : Module.finrank ℚ L2 ≤ Module.finrank ℚ L1 := Submodule.finrank_mono h2_submod
  have h4 : Module.finrank ℚ L2 = p * (p - 1) := by
    have hirr : Irreducible (Polynomial.cyclotomic (p ^ 2) ℚ) :=
      Polynomial.cyclotomic.irreducible_rat (by positivity)
    rw [IsCyclotomicExtension.finrank L2 hirr]
    have htot : (p ^ 2).totient = p ^ (2 - 1) * (p - 1) := Nat.totient_prime_pow hp (by omega)
    rw [htot]
    congr 1
    exact pow_one p
  have h5 : Module.finrank ℚ L1 = p - 1 := by
    have hirr : Irreducible (Polynomial.cyclotomic p ℚ) :=
      Polynomial.cyclotomic.irreducible_rat hp.pos
    rw [IsCyclotomicExtension.finrank L1 hirr]
    exact Nat.totient_prime hp
  rw [h4, h5] at h3
  have h3' : p * (p - 1) ≤ 1 * (p - 1) := by
    calc p * (p - 1)
      _ ≤ p - 1 := h3
      _ = 1 * (p - 1) := (Nat.one_mul _).symm
  have h_pos : 0 < p - 1 := Nat.sub_pos_of_lt hp.one_lt
  have h_le : p ≤ 1 := Nat.le_of_mul_le_mul_right h3' h_pos
  omega

/-- Every `p`-th root of unity lies in `ℤ[ζ_p]`. -/
theorem mem_adjoin_of_pow_eq_one {p : ℕ} (hp : p.Prime) {ζp w : ℂ}
    (hζp : IsPrimitiveRoot ζp p) (hw : w ^ p = 1) :
    w ∈ (Algebra.adjoin ℤ {ζp} : Subalgebra ℤ ℂ) := by
  haveI : NeZero p := ⟨hp.ne_zero⟩
  obtain ⟨i, _, rfl⟩ := hζp.eq_pow_of_pow_eq_one hw
  exact Subalgebra.pow_mem _ (Algebra.subset_adjoin (Set.mem_singleton _)) i

/-- If `b` and `b·ζ_{p²}` are both in `ℤ[ζ_p]`, then `b = 0` (else `ζ_{p²}` would
lie in the field `ℚ(ζ_p)`, contradicting the degree count). -/
theorem eq_zero_of_mul_zetaP2_mem {p : ℕ} (hp : p.Prime) (_hodd : Odd p)
    {ζp2 ζp : ℂ} (hζp2 : IsPrimitiveRoot ζp2 (p ^ 2)) (hζp : IsPrimitiveRoot ζp p)
    {b : ℂ} (hb : b ∈ (Algebra.adjoin ℤ {ζp} : Subalgebra ℤ ℂ))
    (hbz : b * ζp2 ∈ (Algebra.adjoin ℤ {ζp} : Subalgebra ℤ ℂ)) :
    b = 0 := by
  by_contra hb0
  have hpos : 0 < p := hp.pos
  haveI : NeZero (p ^ 2) := ⟨by positivity⟩
  haveI : NeZero p := ⟨hp.pos.ne'⟩
  let L1 : Subalgebra ℚ ℂ := Algebra.adjoin ℚ {ζp}
  let L2 : Subalgebra ℚ ℂ := Algebra.adjoin ℚ {ζp2}
  have H : (Algebra.adjoin ℤ {ζp} : Subalgebra ℤ ℂ) ≤ L1.restrictScalars ℤ := by
    rw [Algebra.adjoin_le_iff]
    simp [L1, Algebra.subset_adjoin]
  have hb_L : b ∈ L1 := H hb
  have hbz_L : b * ζp2 ∈ L1 := H hbz
  haveI : IsCyclotomicExtension {p} ℚ L1 := hζp.adjoin_isCyclotomicExtension ℚ
  haveI : Algebra.IsIntegral ℚ L1 := IsCyclotomicExtension.integral {p} ℚ L1
  have h_int_subtype : IsIntegral ℚ (⟨b, hb_L⟩ : L1) := Algebra.IsIntegral.isIntegral _
  have h_int_b : IsIntegral ℚ b := h_int_subtype.map L1.val
  have h_alg_b : IsAlgebraic ℚ b := h_int_b.isAlgebraic
  have h_inv : b ⁻¹ ∈ L1 := Subalgebra.inv_mem_of_algebraic L1 (x := ⟨b, hb_L⟩) h_alg_b
  have h_zeta : (b * ζp2) * b ⁻¹ ∈ L1 := L1.mul_mem hbz_L h_inv
  have h_zeta_simp : (b * ζp2) * b ⁻¹ = ζp2 := by
    calc (b * ζp2) * b ⁻¹
      _ = ζp2 * (b * b ⁻¹) := by ring
      _ = ζp2 * 1 := by rw [mul_inv_cancel₀ hb0]
      _ = ζp2 := mul_one ζp2
  have h1 : ζp2 ∈ L1 := h_zeta_simp ▸ h_zeta
  have h2 : L2 ≤ L1 := by
    rw [Algebra.adjoin_le_iff]
    intro x hx
    cases hx
    exact h1
  have h2_submod : L2.toSubmodule ≤ L1.toSubmodule := h2
  haveI : IsCyclotomicExtension {p ^ 2} ℚ L2 := hζp2.adjoin_isCyclotomicExtension ℚ
  haveI : Module.Finite ℚ L1 := IsCyclotomicExtension.finiteDimensional {p} ℚ L1
  have h3 : Module.finrank ℚ L2 ≤ Module.finrank ℚ L1 := Submodule.finrank_mono h2_submod
  have h4 : Module.finrank ℚ L2 = p * (p - 1) := by
    have hirr : Irreducible (Polynomial.cyclotomic (p ^ 2) ℚ) :=
      Polynomial.cyclotomic.irreducible_rat (by positivity)
    rw [IsCyclotomicExtension.finrank L2 hirr]
    have htot : (p ^ 2).totient = p ^ (2 - 1) * (p - 1) := Nat.totient_prime_pow hp (by omega)
    rw [htot]
    congr 1
    exact pow_one p
  have h5 : Module.finrank ℚ L1 = p - 1 := by
    have hirr : Irreducible (Polynomial.cyclotomic p ℚ) :=
      Polynomial.cyclotomic.irreducible_rat hp.pos
    rw [IsCyclotomicExtension.finrank L1 hirr]
    exact Nat.totient_prime hp
  rw [h4, h5] at h3
  have h3' : p * (p - 1) ≤ 1 * (p - 1) := by
    calc p * (p - 1)
      _ ≤ p - 1 := h3
      _ = 1 * (p - 1) := (Nat.one_mul _).symm
  have h_pos : 0 < p - 1 := Nat.sub_pos_of_lt hp.one_lt
  have h_le : p ≤ 1 := Nat.le_of_mul_le_mul_right h3' h_pos
  have h_gt : 1 < p := hp.one_lt
  omega

/-- A `p²`-th root of unity lies in `ℤ[ζ_p]` iff it is already a `p`-th root. -/
theorem pow_p2_root_mem_adjoin_iff {p : ℕ} (hp : p.Prime) (hodd : Odd p)
    {ζp w : ℂ} (hζp : IsPrimitiveRoot ζp p) (hw : w ^ (p ^ 2) = 1) :
    w ∈ (Algebra.adjoin ℤ {ζp} : Subalgebra ℤ ℂ) ↔ w ^ p = 1 := by
  constructor
  · intro hw_in
    by_contra hw_p
    haveI : Fact p.Prime := ⟨hp⟩
    have h_prim : IsPrimitiveRoot w (p ^ 2) := by
      rw [IsPrimitiveRoot.iff_orderOf]
      have hw_p_1 : ¬w ^ (p ^ 1) = 1 := by
        rw [pow_one]
        exact hw_p
      have hw_p_2 : w ^ (p ^ (1 + 1)) = 1 := by
        exact hw
      exact orderOf_eq_prime_pow hw_p_1 hw_p_2
    exact zetaP2_not_mem_adjoin_zetaP hp hodd h_prim hζp hw_in
  · intro hw_p
    exact mem_adjoin_of_pow_eq_one hp hζp hw_p

/-- If `w·a = ζ_{p²}·b` with `w, ζ_{p²}` both `p²`-th roots of unity and
`a, b ∈ ℤ[ζ_p]`, `a ≠ 0`, then `w^p = ζ_{p²}^p` (the character exponent is
`≡ 1 mod p`). -/
theorem eq_pow_of_mul_eq_zetaP2_mul {p : ℕ} (hp : p.Prime) (hodd : Odd p)
    {ζp2 ζp w a b : ℂ} (hζp2 : IsPrimitiveRoot ζp2 (p ^ 2)) (hζp : IsPrimitiveRoot ζp p)
    (hw : w ^ (p ^ 2) = 1)
    (ha : a ∈ (Algebra.adjoin ℤ {ζp} : Subalgebra ℤ ℂ))
    (hb : b ∈ (Algebra.adjoin ℤ {ζp} : Subalgebra ℤ ℂ))
    (ha0 : a ≠ 0) (heq : w * a = ζp2 * b) :
    w ^ p = ζp2 ^ p := by
  by_contra hwp
  let x := w * ζp2⁻¹
  have hp_pos : p > 0 := hp.pos
  have hp_ne_zero : p ≠ 0 := hp.ne_zero
  have hp2_ne_zero : p ^ 2 ≠ 0 := pow_ne_zero 2 hp.ne_zero
  have hz_ne_zero : ζp2 ≠ 0 := hζp2.ne_zero hp2_ne_zero
  have hz_pow_p2 : ζp2 ^ (p ^ 2) = 1 := hζp2.pow_eq_one
  haveI : Fact p.Prime := ⟨hp⟩
  have h_x_p2 : x ^ (p ^ 2) = 1 := by
    calc x ^ (p ^ 2) = w ^ (p ^ 2) * (ζp2⁻¹) ^ (p ^ 2) := mul_pow w ζp2⁻¹ (p ^ 2)
      _ = 1 * (ζp2 ^ (p ^ 2))⁻¹ := by rw [hw, inv_pow]
      _ = 1 * 1⁻¹ := by rw [hz_pow_p2]
      _ = 1 := by norm_num
  have h_x_p : x ^ p ≠ 1 := by
    intro h
    have h_pow : x ^ p = w ^ p * (ζp2 ^ p)⁻¹ := by
      calc x ^ p = w ^ p * (ζp2⁻¹) ^ p := mul_pow w ζp2⁻¹ p
        _ = w ^ p * (ζp2 ^ p)⁻¹ := by rw [inv_pow]
    rw [h_pow] at h
    have h_eq : w ^ p = ζp2 ^ p := by
      calc w ^ p = w ^ p * 1 := by rw [mul_one]
        _ = w ^ p * ((ζp2 ^ p)⁻¹ * ζp2 ^ p) := by
          have hz_p_ne : ζp2 ^ p ≠ 0 := pow_ne_zero p hz_ne_zero
          rw [inv_mul_cancel₀ hz_p_ne]
        _ = (w ^ p * (ζp2 ^ p)⁻¹) * ζp2 ^ p := by rw [← mul_assoc]
        _ = 1 * ζp2 ^ p := by rw [h]
        _ = ζp2 ^ p := one_mul _
    exact hwp h_eq
  have h_x_prim : IsPrimitiveRoot x (p ^ 2) := by
    rw [IsPrimitiveRoot.iff_orderOf]
    have hw_p_1 : ¬x ^ (p ^ 1) = 1 := by
      rw [pow_one]
      exact h_x_p
    have hw_p_2 : x ^ (p ^ (1 + 1)) = 1 := h_x_p2
    exact orderOf_eq_prime_pow hw_p_1 hw_p_2
  have heq2 : x * a = b := by
    calc x * a = w * ζp2⁻¹ * a := rfl
      _ = w * a * ζp2⁻¹ := by ring
      _ = ζp2 * b * ζp2⁻¹ := by rw [heq]
      _ = b * (ζp2 * ζp2⁻¹) := by ring
      _ = b * 1 := by rw [mul_inv_cancel₀ hz_ne_zero]
      _ = b := mul_one b
  have heq3 : a * x = b := by
    calc a * x = x * a := mul_comm a x
      _ = b := heq2
  have h_ax_mem : a * x ∈ (Algebra.adjoin ℤ {ζp} : Subalgebra ℤ ℂ) := by
    rw [heq3]
    exact hb
  have h_a_eq_zero : a = 0 := eq_zero_of_mul_zetaP2_mem hp hodd h_x_prim hζp ha h_ax_mem
  exact ha0 h_a_eq_zero

end LeanDring.P4
