/-
Copyright (c) 2026 Tilemachos Vassias. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tilemachos Vassias (formalization assisted by Claude)
-/
import LeanDring.P5.Certificate.Characters.Twin1.CharCert
import LeanDring.P5.Certificate.Characters.Twin1.CharRows.Chunk01
import LeanDring.P5.Certificate.Characters.Twin1.CharRows.Chunk02
import LeanDring.P5.Certificate.Characters.Twin1.CharRows.Chunk03
import LeanDring.P5.Certificate.Characters.Twin1.CharRows.Chunk04
import LeanDring.P5.Certificate.Characters.Twin1.CharBasis.Chunk01
import LeanDring.P5.Certificate.Characters.Twin1.CharBasis.Chunk02
import LeanDring.P5.Certificate.Characters.Twin1.CharBasis.Chunk03
import LeanDring.P5.Certificate.Characters.Twin1.CharBasis.Chunk04
import LeanDring.P5.Certificate.Characters.Twin1.CharValid
import LeanDring.P5.Certificate.Characters.Twin1.CharNodup
import LeanDring.P5.Certificate.Characters.Twin1.CharCount
import LeanDring.P5.Certificate.ConjugacyClasses.Twin1.ConjClasses

/-!
# Assembly of the per-representative character certification

The sibling `CharRows.Chunk01`–`Chunk04`, `CharBasis.Chunk01`–`Chunk04`,
`CharValid`, `CharNodup` and `CharCount` modules (all under
`LeanDring.P5.Certificate.Characters.Twin1`) kernel-check, chunk by
chunk, that for every representative `r` the embedded data
(`repBases/repPR/repCR/repChars r`) is internally consistent. Here we glue the
four 37-rep chunks of each check into a single `(List.range 148).all _ = true`
fact and expose a clean per-`r` API:

* `charsAt_valid`  — every listed vector is a genuine `charOK`-valid character;
* `charsAt_nodup`  — the list is duplicate-free;
* `charsAt_count`  — its length is the aggregate `charCounts r` entry;
* `basisAt_eq`     — the embedded basis is `reps r`'s echelon basis, so
  `reps r = ⟨basisAt r⟩`.

`charsTotal_certified` then rederives the headline total `5236` as the sum of the
*certified* per-representative counts.
-/

namespace LeanDring.P5Presentation

open Fin.NatCast

set_option maxRecDepth 100000

/-! ## Gluing the chunks into whole-range checks -/

theorem checkRows_all : (List.range 148).all checkRows = true :=
  all148_of_chunks checkRows rowsChunk0 rowsChunk1 rowsChunk2 rowsChunk3

theorem checkBasis_all : (List.range 148).all checkBasis = true :=
  all148_of_chunks checkBasis basisChunk0 basisChunk1 basisChunk2 basisChunk3

theorem checkValid_all : (List.range 148).all checkValid = true :=
  all148_of_chunks checkValid validChunk0 validChunk1 validChunk2 validChunk3

theorem checkNodup_all : (List.range 148).all checkNodup = true :=
  all148_of_chunks checkNodup nodupChunk0 nodupChunk1 nodupChunk2 nodupChunk3

theorem checkCount_all : (List.range 148).all checkCount = true :=
  all148_of_chunks checkCount countChunk0 countChunk1 countChunk2 countChunk3

/-- Extract a single `checker r = true` from the whole-range check. -/
theorem checker_at {f : ℕ → Bool} (h : (List.range 148).all f = true)
    (r : Fin 148) : f r.val = true :=
  (List.all_eq_true.mp h) r.val (List.mem_range.mpr r.isLt)

/-! ## The per-representative API -/

/-- The echelon basis of `reps r`, as embedded. -/
def basisAt (r : Fin 148) : List Coordinates := repBases.getD r.val []

/-- The linear-character exponent vectors of `reps r`, as embedded. -/
def charsAt (r : Fin 148) : List (List (ZMod 25)) := repChars.getD r.val []

/-- **Validity.** Every embedded vector of `reps r` is a genuine `charOK`-valid
character (kills every collection relator of the echelon basis). -/
theorem charsAt_valid (r : Fin 148) : (charsAt r).all (charOK (basisAt r)) = true := by
  have hrows := checker_at checkRows_all r
  have hvalid := checker_at checkValid_all r
  simp only [checkRows, Bool.and_eq_true, decide_eq_true_eq] at hrows
  obtain ⟨hPR, hCR⟩ := hrows
  exact all_charOK_of_rows (basisAt r) (charsAt r) _ _ hPR hCR hvalid

/-- **Distinctness.** The embedded character list of `reps r` is duplicate-free. -/
theorem charsAt_nodup (r : Fin 148) : (charsAt r).Nodup := by
  have h := checker_at checkNodup_all r
  simp only [checkNodup] at h
  exact of_decide_eq_true h

/-- **Count.** The number of embedded characters of `reps r` is the aggregate
`charCounts` entry (`= |H^ab|`, per the generator + GAP cross-check). -/
theorem charsAt_count (r : Fin 148) : (charsAt r).length = charCounts.getD r.val 0 := by
  have h := checker_at checkCount_all r
  simp only [checkCount] at h
  exact Nat.eq_of_beq_eq_true h

/-- **Basis identification.** The embedded basis is the genuine echelon basis of
`reps r` (`getB` at the representative's `classRepsData` index). -/
theorem basisAt_eq (r : Fin 148) : basisAt r = getB (classRepsData.getD r.val 0) := by
  have h := checker_at checkBasis_all r
  simp only [checkBasis] at h
  exact of_decide_eq_true h

/-- `reps r` is generated by its embedded echelon basis. -/
theorem reps_eq_ofList (r : Fin 148) :
    reps r = ofList 1 hq1 (basisAt r) := by
  rw [basisAt_eq]; rfl

/-! ## Aggregate: the total `5236` from certified per-representative counts -/

/-- **Certified headline total.** The sum over the 148 representatives of the
*certified* character counts is `5236` — each summand `(charsAt r).length` is
kernel-verified equal to its `charCounts` entry, and those entries sum to
`5236`. This upgrades `charCount_total` from a bare `decide` on the aggregate
list to a consequence of the per-representative certifications. -/
theorem charsTotal_certified :
    ((List.range 148).map (fun r => (repChars.getD r []).length)).sum = 5236 := by
  have hmap : (List.range 148).map (fun r => (repChars.getD r []).length)
      = (List.range 148).map (fun r => charCounts.getD r 0) := by
    apply List.map_congr_left
    intro r hr
    have hr' : r < 148 := List.mem_range.mp hr
    have h := (List.all_eq_true.mp checkCount_all) r hr
    simp only [checkCount] at h
    exact Nat.eq_of_beq_eq_true h
  rw [hmap]
  decide

end LeanDring.P5Presentation
