# dring_tools2.g -- Step 2 addendum: p-local blocks of D(G) via Satz 2.2.7
# and the Theorem B5* separation checks.
#
# Syntax-loaded under GAP 4.15.1 on 2026-07-04, but not yet validated against
# `dring2.py`.  The Python reference passed all cross-checks through order 24,
# including literal agreement with [Mü, p.28f] for S3 at p=2.  This GAP addendum
# still needs a real regression harness before any survey output is trusted.
#
# Conventions follow dring_tools.g / the preprint (TableOfSpecies etc.):
# a species class is a record rec(H := subgroup, h := element)  meaning
# (H, hH'); pairs are compared up to G-conjugacy.

# O^p(H) = subgroup generated by the p'-elements of H.
OpResidual := function(H, p)
  return SubgroupNC(H, Filtered(Elements(H), x -> Order(x) mod p <> 0));
end;

# p'-part of a group element.
PPrimePart := function(g, p)
  local o, a, m, e;
  o := Order(g); a := 1; m := o;
  while m mod p = 0 do m := m / p; a := a * p; od;
  if m = 1 then return g^0; fi;
  e := a * (1/a mod m);        # e = 0 mod a, e = 1 mod m
  return g^e;
end;

# Block root beta_p(H, hH') = (K, h_{p',c} K') per Satz 2.2.7 / law (R):
# K = O^p(H); decompose Kbar = C_Kbar(Hbar) (+) [Kbar, Hbar] in K/K'
# and take the C-component of the p'-part of h.
BlockRootD := function(G, H, h, p)
  local K, Kp, nat, Kbar, Hgens, C, B, hp, x, c, cand;
  K   := OpResidual(H, p);
  Kp  := DerivedSubgroup(K);
  nat := NaturalHomomorphismByNormalSubgroupNC(K, Kp);
  Kbar := Image(nat);
  Hgens := GeneratorsOfGroup(H);
  # C = elements of Kbar fixed by conjugation by H (action descends since
  # K char H and Kp char K)
  C := Filtered(Elements(Kbar),
        y -> ForAll(Hgens,
             u -> Image(nat, (PreImagesRepresentative(nat, y))^u) = y));
  C := SubgroupNC(Kbar, C);
  # B = [Kbar, Hbar] = image of [K, H]
  B := SubgroupNC(Kbar,
        List(Cartesian(GeneratorsOfGroup(K), Hgens),
             pr -> Image(nat, Comm(pr[1], pr[2]))));
  hp := PPrimePart(h, p);
  if not hp in K then Error("p'-part not in O^p(H)"); fi;
  x := Image(nat, hp);
  cand := Filtered(Elements(C), c -> c^-1 * x in B);
  if Length(cand) <> 1 then Error("C (+) B decomposition failed"); fi;
  return rec(K := K, c := PreImagesRepresentative(nat, cand[1]));
end;

# Are two pairs (K1,k1K1'), (K2,k2K2') G-conjugate?
PairsConjugateD := function(G, r1, r2)
  local rc, g, K, k;
  if Size(r1.K) <> Size(r2.K) then return false; fi;
  rc := RepresentativeAction(G, r1.K, r2.K);
  if rc = fail then return false; fi;
  K := r2.K; k := r1.c ^ rc;
  # now compare fibre cosets under N_G(K)
  return ForAny(Elements(Normalizer(G, K)),
           n -> (k^n) * r2.c^-1 in DerivedSubgroup(K));
end;

# Partition of the species classes of D(G) into p-blocks.
# species: list of rec(H, h) as produced by TableOfSpecies conventions.
BlockPartitionD := function(G, species, p)
  local roots, part, i, j, placed;
  roots := List(species, s -> BlockRootD(G, s.H, s.h, p));
  part := []; placed := [];
  for i in [1..Length(species)] do
    if i in placed then continue; fi;
    Add(part, [i]); AddSet(placed, i);
    for j in [i+1..Length(species)] do
      if not j in placed and PairsConjugateD(G, roots[i], roots[j]) then
        Add(part[Length(part)], j); AddSet(placed, j);
      fi;
    od;
  od;
  return part;
end;

# Theorem B5* report: for every involution pair ((H,1),(H,t)) and every
# odd p | |G|, verify separation; and check the fibre-collapse law (i).
InvolutionSeparationReport := function(G, species)
  local ps, p, part, blk, i, j, s, t, ordfib, ok;
  ps := Filtered(PrimeDivisors(Size(G)), q -> q <> 2);
  ok := true;
  for p in ps do
    part := BlockPartitionD(G, species, p);
    blk := [];
    for i in [1..Length(part)] do
      for j in part[i] do blk[j] := i; od;
    od;
    for i in [1..Length(species)] do
      s := species[i];
      ordfib := Order(Image(NaturalHomomorphismByNormalSubgroupNC(
                  s.H, DerivedSubgroup(s.H)), s.h));
      for j in [1..Length(species)] do
        t := species[j];
        if i <> j and t.H = s.H and Order(Image(
             NaturalHomomorphismByNormalSubgroupNC(t.H,
             DerivedSubgroup(t.H)), t.h)) = 1 then
          # (H,1) vs (H, s.h): same block iff fibre has p-power order (B5*)
          if (blk[i] = blk[j]) <> (ordfib = p^Valuation(ordfib, p)) then
            Print("B5* VIOLATION: |H|=", Size(s.H), " fibre order ",
                  ordfib, " p=", p, "\n");
            ok := false;
          fi;
        fi;
      od;
    od;
  od;
  if ok then Print("B5* law confirmed for ", Name(G), "\n"); fi;
  return ok;
end;
