
HypergroupDataUnnormalized := function(A, W)
    local orbs, n, i, j, k, x, y, S, tally, z, pos, A_elms;
    A_elms := Elements(A);
    orbs := ShallowCopy(OrbitsDomain(W, A_elms, OnPoints));
    n := Length(orbs);
    Sort(orbs, function(a,b) return Length(a) < Length(b); end);
    S := [];
    for i in [1..n] do
        S[i] := [];
        for j in [1..n] do
            tally := List([1..n], x -> 0);
            for x in orbs[i] do
                for y in orbs[j] do
                    z := x * y;
                    pos := PositionProperty(orbs, o -> z in o);
                    tally[pos] := tally[pos] + 1;
                od;
            od;
            S[i][j] := tally;
        od;
    od;
    return [List(orbs, Length), S];
end;

Print("[\n");
first := true;

A := SmallGroup(9, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[10]);
W2 := Representative(ccW[12]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [9, 2], \"W1_order\": 8, \"W1_class\": 10, \"W2_class\": 12, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(12, 5);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[7]);
W2 := Representative(ccW[9]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [12, 5], \"W1_order\": 6, \"W1_class\": 7, \"W2_class\": 9, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[29]);
W2 := Representative(ccW[30]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 8, \"W1_class\": 29, \"W2_class\": 30, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[29]);
W2 := Representative(ccW[31]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 8, \"W1_class\": 29, \"W2_class\": 31, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[29]);
W2 := Representative(ccW[40]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 8, \"W1_class\": 29, \"W2_class\": 40, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[30]);
W2 := Representative(ccW[31]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 8, \"W1_class\": 30, \"W2_class\": 31, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[30]);
W2 := Representative(ccW[40]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 8, \"W1_class\": 30, \"W2_class\": 40, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[31]);
W2 := Representative(ccW[40]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 8, \"W1_class\": 31, \"W2_class\": 40, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[47]);
W2 := Representative(ccW[48]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 16, \"W1_class\": 47, \"W2_class\": 48, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[47]);
W2 := Representative(ccW[49]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 16, \"W1_class\": 47, \"W2_class\": 49, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[47]);
W2 := Representative(ccW[50]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 16, \"W1_class\": 47, \"W2_class\": 50, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[47]);
W2 := Representative(ccW[53]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 16, \"W1_class\": 47, \"W2_class\": 53, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[48]);
W2 := Representative(ccW[49]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 16, \"W1_class\": 48, \"W2_class\": 49, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[48]);
W2 := Representative(ccW[50]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 16, \"W1_class\": 48, \"W2_class\": 50, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[48]);
W2 := Representative(ccW[53]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 16, \"W1_class\": 48, \"W2_class\": 53, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[49]);
W2 := Representative(ccW[50]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 16, \"W1_class\": 49, \"W2_class\": 50, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[49]);
W2 := Representative(ccW[53]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 16, \"W1_class\": 49, \"W2_class\": 53, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[50]);
W2 := Representative(ccW[53]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 16, \"W1_class\": 50, \"W2_class\": 53, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[45]);
W2 := Representative(ccW[57]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 45, \"W2_class\": 57, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[62]);
W2 := Representative(ccW[63]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 16, \"W1_class\": 62, \"W2_class\": 63, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[62]);
W2 := Representative(ccW[65]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 16, \"W1_class\": 62, \"W2_class\": 65, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[63]);
W2 := Representative(ccW[65]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 16, \"W1_class\": 63, \"W2_class\": 65, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[88]);
W2 := Representative(ccW[89]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 32, \"W1_class\": 88, \"W2_class\": 89, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[88]);
W2 := Representative(ccW[91]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 32, \"W1_class\": 88, \"W2_class\": 91, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[88]);
W2 := Representative(ccW[92]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 32, \"W1_class\": 88, \"W2_class\": 92, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[89]);
W2 := Representative(ccW[91]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 32, \"W1_class\": 89, \"W2_class\": 91, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[89]);
W2 := Representative(ccW[92]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 32, \"W1_class\": 89, \"W2_class\": 92, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[91]);
W2 := Representative(ccW[92]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 32, \"W1_class\": 91, \"W2_class\": 92, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[32]);
W2 := Representative(ccW[34]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 8, \"W1_class\": 32, \"W2_class\": 34, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[50]);
W2 := Representative(ccW[56]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 16, \"W1_class\": 50, \"W2_class\": 56, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[50]);
W2 := Representative(ccW[57]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 16, \"W1_class\": 50, \"W2_class\": 57, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[56]);
W2 := Representative(ccW[57]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 16, \"W1_class\": 56, \"W2_class\": 57, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[83]);
W2 := Representative(ccW[84]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 32, \"W1_class\": 83, \"W2_class\": 84, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[83]);
W2 := Representative(ccW[85]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 32, \"W1_class\": 83, \"W2_class\": 85, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[83]);
W2 := Representative(ccW[86]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 32, \"W1_class\": 83, \"W2_class\": 86, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[84]);
W2 := Representative(ccW[85]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 32, \"W1_class\": 84, \"W2_class\": 85, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[84]);
W2 := Representative(ccW[86]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 32, \"W1_class\": 84, \"W2_class\": 86, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[85]);
W2 := Representative(ccW[86]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 32, \"W1_class\": 85, \"W2_class\": 86, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[11]);
W2 := Representative(ccW[13]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 4, \"W1_class\": 11, \"W2_class\": 13, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[34]);
W2 := Representative(ccW[37]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 8, \"W1_class\": 34, \"W2_class\": 37, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[34]);
W2 := Representative(ccW[42]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 8, \"W1_class\": 34, \"W2_class\": 42, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[37]);
W2 := Representative(ccW[42]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 8, \"W1_class\": 37, \"W2_class\": 42, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[42]);
W2 := Representative(ccW[56]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 42, \"W2_class\": 56, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[12]);
W2 := Representative(ccW[18]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 4, \"W1_class\": 12, \"W2_class\": 18, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[10]);
W2 := Representative(ccW[17]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 4, \"W1_class\": 10, \"W2_class\": 17, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[10]);
W2 := Representative(ccW[22]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 4, \"W1_class\": 10, \"W2_class\": 22, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[17]);
W2 := Representative(ccW[22]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 4, \"W1_class\": 17, \"W2_class\": 22, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[13]);
W2 := Representative(ccW[15]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 4, \"W1_class\": 13, \"W2_class\": 15, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[13]);
W2 := Representative(ccW[24]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 4, \"W1_class\": 13, \"W2_class\": 24, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[15]);
W2 := Representative(ccW[24]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 4, \"W1_class\": 15, \"W2_class\": 24, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[36]);
W2 := Representative(ccW[44]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 36, \"W2_class\": 44, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[36]);
W2 := Representative(ccW[52]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 36, \"W2_class\": 52, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[44]);
W2 := Representative(ccW[52]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 44, \"W2_class\": 52, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[32]);
W2 := Representative(ccW[41]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 8, \"W1_class\": 32, \"W2_class\": 41, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 5);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[21]);
W2 := Representative(ccW[26]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 5], \"W1_order\": 8, \"W1_class\": 21, \"W2_class\": 26, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[33]);
W2 := Representative(ccW[40]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 33, \"W2_class\": 40, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[33]);
W2 := Representative(ccW[48]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 33, \"W2_class\": 48, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[40]);
W2 := Representative(ccW[48]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 40, \"W2_class\": 48, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[68]);
W2 := Representative(ccW[70]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 16, \"W1_class\": 68, \"W2_class\": 70, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[23]);
W2 := Representative(ccW[25]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 8, \"W1_class\": 23, \"W2_class\": 25, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[23]);
W2 := Representative(ccW[29]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 8, \"W1_class\": 23, \"W2_class\": 29, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[25]);
W2 := Representative(ccW[29]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 8, \"W1_class\": 25, \"W2_class\": 29, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[55]);
W2 := Representative(ccW[58]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 16, \"W1_class\": 55, \"W2_class\": 58, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[43]);
W2 := Representative(ccW[44]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 12, \"W1_class\": 43, \"W2_class\": 44, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[43]);
W2 := Representative(ccW[46]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 12, \"W1_class\": 43, \"W2_class\": 46, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[44]);
W2 := Representative(ccW[46]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 12, \"W1_class\": 44, \"W2_class\": 46, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[54]);
W2 := Representative(ccW[55]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 24, \"W1_class\": 54, \"W2_class\": 55, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[54]);
W2 := Representative(ccW[56]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 24, \"W1_class\": 54, \"W2_class\": 56, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[54]);
W2 := Representative(ccW[57]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 24, \"W1_class\": 54, \"W2_class\": 57, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[55]);
W2 := Representative(ccW[56]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 24, \"W1_class\": 55, \"W2_class\": 56, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[55]);
W2 := Representative(ccW[57]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 24, \"W1_class\": 55, \"W2_class\": 57, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[56]);
W2 := Representative(ccW[57]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 24, \"W1_class\": 56, \"W2_class\": 57, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[59]);
W2 := Representative(ccW[60]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 48, \"W1_class\": 59, \"W2_class\": 60, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[59]);
W2 := Representative(ccW[61]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 48, \"W1_class\": 59, \"W2_class\": 61, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 2);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[60]);
W2 := Representative(ccW[61]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 2], \"W1_order\": 48, \"W1_class\": 60, \"W2_class\": 61, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[38]);
W2 := Representative(ccW[41]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 12, \"W1_class\": 38, \"W2_class\": 41, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[38]);
W2 := Representative(ccW[45]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 12, \"W1_class\": 38, \"W2_class\": 45, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[41]);
W2 := Representative(ccW[45]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 12, \"W1_class\": 41, \"W2_class\": 45, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[64]);
W2 := Representative(ccW[71]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 24, \"W1_class\": 64, \"W2_class\": 71, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[64]);
W2 := Representative(ccW[76]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 24, \"W1_class\": 64, \"W2_class\": 76, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[71]);
W2 := Representative(ccW[76]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 24, \"W1_class\": 71, \"W2_class\": 76, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[93]);
W2 := Representative(ccW[94]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 48, \"W1_class\": 93, \"W2_class\": 94, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[93]);
W2 := Representative(ccW[95]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 48, \"W1_class\": 93, \"W2_class\": 95, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[94]);
W2 := Representative(ccW[95]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 48, \"W1_class\": 94, \"W2_class\": 95, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[127]);
W2 := Representative(ccW[128]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 288, \"W1_class\": 127, \"W2_class\": 128, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[127]);
W2 := Representative(ccW[129]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 288, \"W1_class\": 127, \"W2_class\": 129, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[128]);
W2 := Representative(ccW[129]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 288, \"W1_class\": 128, \"W2_class\": 129, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[37]);
W2 := Representative(ccW[38]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 37, \"W2_class\": 38, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[37]);
W2 := Representative(ccW[46]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 37, \"W2_class\": 46, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[37]);
W2 := Representative(ccW[50]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 37, \"W2_class\": 50, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[38]);
W2 := Representative(ccW[46]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 38, \"W2_class\": 46, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[38]);
W2 := Representative(ccW[50]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 38, \"W2_class\": 50, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[46]);
W2 := Representative(ccW[50]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 46, \"W2_class\": 50, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[71]);
W2 := Representative(ccW[75]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 16, \"W1_class\": 71, \"W2_class\": 75, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[27]);
W2 := Representative(ccW[30]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 8, \"W1_class\": 27, \"W2_class\": 30, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[35]);
W2 := Representative(ccW[41]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 35, \"W2_class\": 41, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[35]);
W2 := Representative(ccW[49]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 35, \"W2_class\": 49, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[35]);
W2 := Representative(ccW[51]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 35, \"W2_class\": 51, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[41]);
W2 := Representative(ccW[49]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 41, \"W2_class\": 49, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[41]);
W2 := Representative(ccW[51]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 41, \"W2_class\": 51, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[49]);
W2 := Representative(ccW[51]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 8, \"W1_class\": 49, \"W2_class\": 51, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[69]);
W2 := Representative(ccW[72]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 16, \"W1_class\": 69, \"W2_class\": 72, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[26]);
W2 := Representative(ccW[33]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 8, \"W1_class\": 26, \"W2_class\": 33, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[30]);
W2 := Representative(ccW[32]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 6, \"W1_class\": 30, \"W2_class\": 32, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[18]);
W2 := Representative(ccW[19]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 6, \"W1_class\": 18, \"W2_class\": 19, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[64]);
W2 := Representative(ccW[73]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 16, \"W1_class\": 64, \"W2_class\": 73, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[66]);
W2 := Representative(ccW[74]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 16, \"W1_class\": 66, \"W2_class\": 74, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[76]);
W2 := Representative(ccW[80]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 24, \"W1_class\": 76, \"W2_class\": 80, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[66]);
W2 := Representative(ccW[69]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 24, \"W1_class\": 66, \"W2_class\": 69, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[77]);
W2 := Representative(ccW[83]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 24, \"W1_class\": 77, \"W2_class\": 83, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[73]);
W2 := Representative(ccW[74]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 24, \"W1_class\": 73, \"W2_class\": 74, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[79]);
W2 := Representative(ccW[84]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 24, \"W1_class\": 79, \"W2_class\": 84, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[79]);
W2 := Representative(ccW[85]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 24, \"W1_class\": 79, \"W2_class\": 85, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 10);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[84]);
W2 := Representative(ccW[85]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 10], \"W1_order\": 24, \"W1_class\": 84, \"W2_class\": 85, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[65]);
W2 := Representative(ccW[67]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 24, \"W1_class\": 65, \"W2_class\": 67, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[65]);
W2 := Representative(ccW[75]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 24, \"W1_class\": 65, \"W2_class\": 75, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[67]);
W2 := Representative(ccW[75]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 24, \"W1_class\": 67, \"W2_class\": 75, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[59]);
W2 := Representative(ccW[60]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 18, \"W1_class\": 59, \"W2_class\": 60, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[101]);
W2 := Representative(ccW[103]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 60, \"W1_class\": 101, \"W2_class\": 103, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[130]);
W2 := Representative(ccW[131]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 360, \"W1_class\": 130, \"W2_class\": 131, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[87]);
W2 := Representative(ccW[88]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 36, \"W1_class\": 87, \"W2_class\": 88, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[109]);
W2 := Representative(ccW[111]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 96, \"W1_class\": 109, \"W2_class\": 111, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[110]);
W2 := Representative(ccW[113]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 96, \"W1_class\": 110, \"W2_class\": 113, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[119]);
W2 := Representative(ccW[121]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 168, \"W1_class\": 119, \"W2_class\": 121, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

A := SmallGroup(16, 14);
AutA := AutomorphismGroup(A);
ccW := ConjugacyClassesSubgroups(AutA);
W1 := Representative(ccW[118]);
W2 := Representative(ccW[120]);
hd1 := HypergroupDataUnnormalized(A, W1);
hd2 := HypergroupDataUnnormalized(A, W2);
if not first then Print(",\n"); fi;
first := false;
Print("{\"A\": [16, 14], \"W1_order\": 168, \"W1_class\": 118, \"W2_class\": 120, ");
Print("\"S1\": ", hd1[2], ", \"S2\": ", hd2[2], "}");

Print("]\n");
quit;
