# Exact rational-species lattice check for the candidate depth isometry.
# Input is generated by python/order128_export_rational_lattices.py.

Read("results/order128_pairs/g128_1597_1598_rational_matrices.g");;
Print("computing HNF A: ", Length(MA), "x", RANK, "\n");
HA := HermiteNormalFormIntegerMat(MA);;
Print("computing HNF B\n");
HB := HermiteNormalFormIntegerMat(MB);;
Print("RATIONAL_HNF_EQUAL=", HA = HB, "\n");
Print("HNF_ROWS_A=", Length(HA), " HNF_ROWS_B=", Length(HB), "\n");
QUIT;
