# Extract exact HNF-dual functionals for the two untransported rational
# species lattices.  Input is generated by order128_export_rational_lattices.py.

Read("results/order128_pairs/g128_1597_rational_hnf.g");;
Read("results/order128_pairs/g128_1598_rational_hnf.g");;

DualFunctionals := function(H)
  local I, m, out, c, den, f;
  I := H ^ -1;
  m := Length(H);
  out := [];
  for c in [1..m] do
    den := Lcm(List([1..m], r -> DenominatorRat(I[r][c])));
    if den > 1 then
      f := List([1..m], r -> RemInt(Int(I[r][c] * den), den));
      Add(out, [den, f]);
    fi;
  od;
  return out;
end;

RANK := Length(HA0);;
if Length(HB) <> RANK then Error("rank mismatch"); fi;
Print("RATIONAL_INDEX_A=", AbsInt(DeterminantMat(HA0)),
      " RATIONAL_INDEX_B=", AbsInt(DeterminantMat(HB)), "\n");
Print("extracting dual functionals A\n");
FA := DualFunctionals(HA0);;
Print("extracting dual functionals B\n");
FB := DualFunctionals(HB);;
out := OutputTextFile("results/order128_pairs/g128_1597_rational_functionals.g",
                      false);;
SetPrintFormattingStatus(out, false);; AppendTo(out, FA, "\n");;
CloseStream(out);;
out := OutputTextFile("results/order128_pairs/g128_1598_rational_functionals.g",
                      false);;
SetPrintFormattingStatus(out, false);; AppendTo(out, FB, "\n");;
CloseStream(out);;
Print("FUNCTIONALS_A=", Length(FA), " FUNCTIONALS_B=", Length(FB), "\n");
QUIT;
